import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'et'
period = '13TeV'
sqrts = 13

def positivize(histogram):
    output = histogram.Clone()
    for i in range(output.GetSize()):
        if output.GetArray()[i] < 0:
            output.AddAt(0, i)
    return output

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'GluGluHToWW*', 'VBFHToWW*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('../results/%s/AnalyzeETauSysBDT/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('../inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = '../plots/%s/AnalyzeETauSysBDT/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'shapes/shapesETauBDT.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') or x.startswith('DYJetsToLL_M-10to50'), mc_samples )]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('EWK') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGluHToTauTau') or x.startswith('GluGluHToWW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBFHToTauTau') or x.startswith('VBFHToWW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('WminusHToTauTau') or x.startswith('WplusHToTauTau') or x.startswith('ZHToTauTau') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGlu_LFV') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBF_LFV') , mc_samples)])
]

b = ['Zll', 'EWK', 'GluGluH', 'VBFH', 'VH', 'TT', 'ST', 'EWKDiboson', 'GluGlu125', 'VBF125']

for di in dirs:

    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    data = DataTotal.Get('TightOS'+di+'/bdtDiscriminator')
    data.SetName('data_obs')
    
    embed = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    emball = embed.Get('TightOS'+di+'/bdtDiscriminator')
    embtfakes = embed.Get('TauLooseOS'+di+'/bdtDiscriminator')
    embefakes = embed.Get('EleLooseOS'+di+'/bdtDiscriminator')
    embetfakes = embed.Get('EleLooseTauLooseOS'+di+'/bdtDiscriminator')
    embfakes = embtfakes.Clone()
    embfakes.Add(embefakes)
    embfakes.Add(embetfakes, -1)
    embfakes = positivize(embfakes)
    emb = emball.Clone()
    emb.Add(embfakes, -1)
    emb = positivize(emb)
    emb.SetName('embed')

    embtrkup = embed.Get('TightOS'+di+'/embtrkUp/bdtDiscriminator')
    embtrkup.Add(embfakes, -1)
    embtrkup = positivize(embtrkup)
    embtrkup.SetName('embed_CMS_tracking_tauUp')
    embtrkdown = embed.Get('TightOS'+di+'/embtrkDown/bdtDiscriminator')
    embtrkdown.Add(embfakes, -1)
    embtrkdown = positivize(embtrkdown)
    embtrkdown.SetName('embed_CMS_tracking_tauDown')

    embtes0up = embed.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
    embtes0up.Add(embfakes, -1)
    embtes0up = positivize(embtes0up)
    embtes0up.SetName('embed_CMS_scale_t_1prong_13TeVUp')
    embtes0down = embed.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
    embtes0down.Add(embfakes, -1)
    embtes0down = positivize(embtes0down)
    embtes0down.SetName('embed_CMS_scale_t_1prong_13TeVDown')

    embtes1up = embed.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
    embtes1up.Add(embfakes, -1)
    embtes1up = positivize(embtes1up)
    embtes1up.SetName('embed_CMS_scale_t_1prong1pizero_13TeVUp')
    embtes1down = embed.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
    embtes1down.Add(embfakes, -1)
    embtes1down = positivize(embtes1down)
    embtes1down.SetName('embed_CMS_scale_t_1prong1pizero_13TeVDown')

    embtes10up = embed.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
    embtes10up.Add(embfakes, -1)
    embtes10up = positivize(embtes10up)
    embtes10up.SetName('embed_CMS_scale_t_3prong_13TeVUp')
    embtes10down = embed.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
    embtes10down.Add(embfakes, -1)
    embtes10down = positivize(embtes10down)
    embtes10down.SetName('embed_CMS_scale_t_3prong_13TeVDown')

    embtb0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    embtb0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    embtb1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    embtb1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    embtb10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    embtb10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    embte0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    embte0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    embte1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    embte1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    embte10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    embte10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    embefakesup = embed.Get('EleLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
    embefakesdown = embed.Get('EleLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
    embettb0fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    embettb0fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    embettb1fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    embettb1fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    embettb10fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    embettb10fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    embette0fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    embette0fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    embette1fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    embette1fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    embette10fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    embette10fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    embetefakesup = embed.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
    embetefakesdown = embed.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
    emb1b0 = emball.Clone()
    emb1tb0 = embtb0fakesup.Clone()
    emb1tb0.add(embefakes)
    emb1tb0.add(embettb0fakesup, -1)
    emb1tb0 = positivize(emb1tb0)
    emb1b0.add(emb1tb0, -1)
    emb1b0 = positivize(emb1b0)
    emb1b0.SetName('embed_CMS_TauFakeRate_EB_DM0_13TeVUp')
    emb2b0 = emball.Clone()
    emb2tb0 = embtb0fakesdown.Clone()
    emb2tb0.add(embefakes)
    emb2tb0.add(embettb0fakesdown, -1)
    emb2tb0 = positivize(emb2tb0)
    emb2b0.add(emb2tb0, -1)
    emb2b0 = positivize(emb2b0)
    emb2b0.SetName('embed_CMS_TauFakeRate_EB_DM0_13TeVDown')
    emb1b1 = emball.Clone()
    emb1tb1 = embtb1fakesup.Clone()
    emb1tb1.add(embefakes)
    emb1tb1.add(embettb1fakesup, -1)
    emb1tb1 = positivize(emb1tb1)
    emb1b1.add(emb1tb1, -1)
    emb1b1 = positivize(emb1b1)
    emb1b1.SetName('embed_CMS_TauFakeRate_EB_DM1_13TeVUp')
    emb2b1 = emball.Clone()
    emb2tb1 = embtb1fakesdown.Clone()
    emb2tb1.add(embefakes)
    emb2tb1.add(embettb1fakesdown, -1)
    emb2tb1 = positivize(emb2tb1)
    emb2b1.add(emb2tb1, -1)
    emb2b1 = positivize(emb2b1)
    emb2b1.SetName('embed_CMS_TauFakeRate_EB_DM1_13TeVDown')
    emb1b10 = emball.Clone()
    emb1tb10 = embtb10fakesup.Clone()
    emb1tb10.add(embefakes)
    emb1tb10.add(embettb10fakesup, -1)
    emb1tb10 = positivize(emb1tb10)
    emb1b10.add(emb1tb10, -1)
    emb1b10 = positivize(emb1b10)
    emb1b10.SetName('embed_CMS_TauFakeRate_EB_DM10_13TeVUp')
    emb2b10 = emball.Clone()
    emb2tb10 = embtb10fakesdown.Clone()
    emb2tb10.add(embefakes)
    emb2tb10.add(embettb10fakesdown, -1)
    emb2tb10 = positivize(emb2tb10)
    emb2b10.add(emb2tb10, -1)
    emb2b10 = positivize(emb2b10)
    emb2b10.SetName('embed_CMS_TauFakeRate_EB_DM10_13TeVDown')
    emb1e0 = emball.Clone()
    emb1te0 = embte0fakesup.Clone()
    emb1te0.add(embefakes)
    emb1te0.add(embette0fakesup, -1)
    emb1te0 = positivize(emb1te0)
    emb1e0.add(emb1te0, -1)
    emb1e0 = positivize(emb1e0)
    emb1e0.SetName('embed_CMS_TauFakeRate_EE_DM0_13TeVUp')
    emb2e0 = emball.Clone()
    emb2te0 = embte0fakesdown.Clone()
    emb2te0.add(embefakes)
    emb2te0.add(embette0fakesdown, -1)
    emb2te0 = positivize(emb2te0)
    emb2e0.add(emb2te0, -1)
    emb2e0 = positivize(emb2e0)
    emb2e0.SetName('embed_CMS_TauFakeRate_EE_DM0_13TeVDown')
    emb1e1 = emball.Clone()
    emb1te1 = embte1fakesup.Clone()
    emb1te1.add(embefakes)
    emb1te1.add(embette1fakesup, -1)
    emb1te1 = positivize(emb1te1)
    emb1e1.add(emb1te1, -1)
    emb1e1 = positivize(emb1e1)
    emb1e1.SetName('embed_CMS_TauFakeRate_EE_DM1_13TeVUp')
    emb2e1 = emball.Clone()
    emb2te1 = embte1fakesdown.Clone()
    emb2te1.add(embefakes)
    emb2te1.add(embette1fakesdown, -1)
    emb2te1 = positivize(emb2te1)
    emb2e1.add(emb2te1, -1)
    emb2e1 = positivize(emb2e1)
    emb2e1.SetName('embed_CMS_TauFakeRate_EE_DM1_13TeVDown')
    emb1e10 = emball.Clone()
    emb1te10 = embte10fakesup.Clone()
    emb1te10.add(embefakes)
    emb1te10.add(embette10fakesup, -1)
    emb1te10 = positivize(emb1te10)
    emb1e10.add(emb1te10, -1)
    emb1e10 = positivize(emb1e10)
    emb1e10.SetName('embed_CMS_TauFakeRate_EE_DM10_13TeVUp')
    emb2e10 = emball.Clone()
    emb2te10 = embte10fakesdown.Clone()
    emb2te10.add(embefakes)
    emb2te10.add(embette10fakesdown, -1)
    emb2te10 = positivize(emb2te10)
    emb2e10.add(emb2te10, -1)
    emb2e10 = positivize(emb2e10)
    emb2e10.SetName('embed_CMS_TauFakeRate_EE_DM10_13TeVDown')
    emb3 = emball.Clone()
    emb3t = embtfakes.Clone()
    emb3t.add(embefakesup)
    emb3t.add(embetefakesup, -1)
    emb3t = positivize(emb3t)
    emb3.add(emb3t, -1)
    emb3 = positivize(emb3)
    emb3.SetName('embed_CMS_EleFakeRate_13TeVUp')
    emb4 = emball.Clone()
    emb4t = embtfakes.Clone()
    emb4t.add(embefakesdown)
    emb4t.add(embetefakesdown, -1)
    emb4t = positivize(emb4t)
    emb4.add(emb4t, -1)
    emb4 = positivize(emb4)
    emb4.SetName('embed_CMS_EleFakeRate_13TeVDown')
    emball.Delete()
    emb1tb0.Delete()
    emb2tb0.Delete()
    emb1tb1.Delete()
    emb2tb1.Delete()
    emb1tb10.Delete()
    emb2tb10.Delete()
    emb1te0.Delete()
    emb2te0.Delete()
    emb1te1.Delete()
    emb2te1.Delete()
    emb1te10.Delete()
    emb2te10.Delete()    
    emb3t.Delete()
    emb4t.Delete()
    embfakes.Delete()
    embtfakes.Delete()
    embefakes.Delete()
    embetfakes.Delete()
    embte0fakesup.Delete()
    embte0fakesdown.Delete()
    embte1fakesup.Delete()
    embte1fakesdown.Delete()
    embte10fakesup.Delete()
    embte10fakesdown.Delete()
    embtb0fakesup.Delete()
    embtb0fakesdown.Delete()
    embtb1fakesup.Delete()
    embtb1fakesdown.Delete()
    embtb10fakesup.Delete()
    embtb10fakesdown.Delete()
    embefakesup.Delete()
    embefakesdown.Delete()
    embette0fakesup.Delete()
    embette0fakesdown.Delete()
    embette1fakesup.Delete()
    embette1fakesdown.Delete()
    embette10fakesup.Delete()
    embette10fakesdown.Delete()
    embettb0fakesup.Delete()
    embettb0fakesdown.Delete()
    embettb1fakesup.Delete()
    embettb1fakesdown.Delete()
    embettb10fakesup.Delete()
    embettb10fakesdown.Delete()
    embetefakesup.Delete()
    embetefakesdown.Delete()
    
    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    tfakes = QCD.Get('TauLooseOS'+di+'/bdtDiscriminator')
    efakes = QCD.Get('EleLooseOS'+di+'/bdtDiscriminator')
    etfakes = QCD.Get('EleLooseTauLooseOS'+di+'/bdtDiscriminator')
    qcd = tfakes.Clone()
    qcd.Add(efakes)
    qcd.Add(etfakes, -1)
    qcd = positivize(qcd)
    qcd.SetName('Fakes')
    te0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    te0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    te1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    te1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    te10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    te10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    tb0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    tb0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    tb1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    tb1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    tb10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    tb10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    efakesup = QCD.Get('EleLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
    efakesdown = QCD.Get('EleLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
    ette0fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    ette0fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    ette1fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    ette1fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    ette10fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    ette10fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    ettb0fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    ettb0fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    ettb1fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    ettb1fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    ettb10fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    ettb10fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    etefakesup = QCD.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
    etefakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
    f1e0 = te0fakesup.Clone()
    f1e0.add(efakes)
    f1e0.add(ette0fakesup, -1)
    f1e0 = positivize(f1e0)
    f1e0.SetName('Fakes_CMS_TauFakeRate_EE_DM0_13TeVUp')
    f2e0 = te0fakesdown.Clone()
    f2e0.add(efakes)
    f2e0.add(ette0fakesdown, -1)
    f2e0 = positivize(f2e0)
    f2e0.SetName('Fakes_CMS_TauFakeRate_EE_DM0_13TeVDown')
    f1e1 = te1fakesup.Clone()
    f1e1.add(efakes)
    f1e1.add(ette1fakesup, -1)
    f1e1 = positivize(f1e1)
    f1e1.SetName('Fakes_CMS_TauFakeRate_EE_DM1_13TeVUp')
    f2e1 = te1fakesdown.Clone()
    f2e1.add(efakes)
    f2e1.add(ette1fakesdown, -1)
    f2e1 = positivize(f2e1)
    f2e1.SetName('Fakes_CMS_TauFakeRate_EE_DM1_13TeVDown')
    f1e10 = te10fakesup.Clone()
    f1e10.add(efakes)
    f1e10.add(ette10fakesup, -1)
    f1e10 = positivize(f1e10)
    f1e10.SetName('Fakes_CMS_TauFakeRate_EE_DM10_13TeVUp')
    f2e10 = te10fakesdown.Clone()
    f2e10.add(efakes)
    f2e10.add(ette10fakesdown, -1)
    f2e10 = positivize(f2e10)
    f2e10.SetName('Fakes_CMS_TauFakeRate_EE_DM10_13TeVDown')
    f1b0 = tb0fakesup.Clone()
    f1b0.add(efakes)
    f1b0.add(ettb0fakesup, -1)
    f1b0 = positivize(f1b0)
    f1b0.SetName('Fakes_CMS_TauFakeRate_EB_DM0_13TeVUp')
    f2b0 = tb0fakesdown.Clone()
    f2b0.add(efakes)
    f2b0.add(ettb0fakesdown, -1)
    f2b0 = positivize(f2b0)
    f2b0.SetName('Fakes_CMS_TauFakeRate_EB_DM0_13TeVDown')
    f1b1 = tb1fakesup.Clone()
    f1b1.add(efakes)
    f1b1.add(ettb1fakesup, -1)
    f1b1 = positivize(f1b1)
    f1b1.SetName('Fakes_CMS_TauFakeRate_EB_DM1_13TeVUp')
    f2b1 = tb1fakesdown.Clone()
    f2b1.add(efakes)
    f2b1.add(ettb1fakesdown, -1)
    f2b1 = positivize(f2b1)
    f2b1.SetName('Fakes_CMS_TauFakeRate_EB_DM1_13TeVDown')
    f1b10 = tb10fakesup.Clone()
    f1b10.add(efakes)
    f1b10.add(ettb10fakesup, -1)
    f1b10 = positivize(f1b10)
    f1b10.SetName('Fakes_CMS_TauFakeRate_EB_DM10_13TeVUp')
    f2b10 = tb10fakesdown.Clone()
    f2b10.add(efakes)
    f2b10.add(ettb10fakesdown, -1)
    f2b10 = positivize(f2b10)
    f2b10.SetName('Fakes_CMS_TauFakeRate_EB_DM10_13TeVDown')
    f3 = tfakes.Clone()
    f3.add(efakesup)
    f3.add(etefakesup, -1)
    f3 = positivize(f3)
    f3.SetName('Fakes_CMS_EleFakeRate_13TeVUp')
    f4 = tfakes.Clone()
    f4.add(efakesdown)
    f4.add(etefakesdown, -1)
    f4 = positivize(f4)
    f4.SetName('Fakes_CMS_EleFakeRate_13TeVDown')
    tfakes.Delete()
    efakes.Delete()
    etfakes.Delete()
    te0fakesup.Delete()
    te0fakesdown.Delete()
    te1fakesup.Delete()
    te1fakesdown.Delete()
    te10fakesup.Delete()
    te10fakesdown.Delete()
    tb0fakesup.Delete()
    tb0fakesdown.Delete()
    tb1fakesup.Delete()
    tb1fakesdown.Delete()
    tb10fakesup.Delete()
    tb10fakesdown.Delete()
    efakesup.Delete()
    efakesdown.Delete()
    ette0fakesup.Delete()
    ette0fakesdown.Delete()
    ette1fakesup.Delete()
    ette1fakesdown.Delete()
    ette10fakesup.Delete()
    ette10fakesdown.Delete()
    ettb0fakesup.Delete()
    ettb0fakesdown.Delete()
    ettb1fakesup.Delete()
    ettb1fakesdown.Delete()
    ettb10fakesup.Delete()
    ettb10fakesdown.Delete()
    etefakesup.Delete()
    etefakesdown.Delete()

    for i in range(10):
        DY = v[i]
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dy.SetName(b[i])

            dypuup = DY.Get('TightOS'+di+'/puUp/bdtDiscriminator')
            dypuup.SetName(b[i]+'_CMS_Pileup_13TeVUp')
            dypudown = DY.Get('TightOS'+di+'/puDown/bdtDiscriminator')
            dypudown.SetName(b[i]+'_CMS_Pileup_13TeVDown')

            dytidup = DY.Get('TightOS'+di+'/tidUp/bdtDiscriminator')
            dytidup.SetName(b[i]+'_CMS_eff_tauUp')
            dytiddown = DY.Get('TightOS'+di+'/tidDown/bdtDiscriminator')
            dytiddown.SetName(b[i]+'_CMS_eff_tauDown')
        
            dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/bdtDiscriminator')
            dyrecrespup.SetName(b[i]+'_CMS_RecoilResponse_13TeVUp')
            dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/bdtDiscriminator')
            dyrecrespdown.SetName(b[i]+'_CMS_RecoilResponse_13TeVDown')

            dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/bdtDiscriminator')
            dyrecresoup.SetName(b[i]+'_CMS_RecoilResolution_13TeVUp')
            dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/bdtDiscriminator')
            dyrecresodown.SetName(b[i]+'_CMS_RecoilResolution_13TeVDown')

            dymtfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dymtfakeup.SetName(b[i]+'_CMS_scale_mfaketau_13TeVUp')
            dymtfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dymtfakedown.SetName(b[i]+'_CMS_scale_mfaketau_13TeVDown')

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dyetfakeup.SetName(b[i]+'_CMS_scale_efaketau_13TeVUp')
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dyetfakedown.SetName(b[i]+'_CMS_scale_efaketau_13TeVDown')

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/bdtDiscriminator')
            dyetefakeup.SetName(b[i]+'_CMS_scale_efaketaues_13TeVUp')
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/bdtDiscriminator')
            dyetefakedown.SetName(b[i]+'_CMS_scale_efaketaues_13TeVDown')

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
            dytes0up.SetName(b[i]+'_CMS_scale_t_1prong_13TeVUp')
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
            dytes0down.SetName(b[i]+'_CMS_scale_t_1prong_13TeVDown')

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
            dytes1up.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp')
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
            dytes1down.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown')

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
            dytes10up.SetName(b[i]+'_CMS_scale_t_3prong_13TeVUp')
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
            dytes10down.SetName(b[i]+'_CMS_scale_t_3prong_13TeVDown')

            #Electron Energy Scale
            dyeescup = DY.Get('TightOS'+di+'/eescUp/bdtDiscriminator')
            dyeescup.SetName(b[i]+'_CMS_EEScale_13TeVUp')
            dyeescdown = DY.Get('TightOS'+di+'/eescDown/bdtDiscriminator')
            dyeescdown.SetName(b[i]+'_CMS_EEScale_13TeVDown')

            #Electron Energy Sigma
            dyeesiup = DY.Get('TightOS'+di+'/eesiUp/bdtDiscriminator')
            dyeesiup.SetName(b[i]+'_CMS_EESigma_13TeVUp')
            dyeesidown = DY.Get('TightOS'+di+'/eesiDown/bdtDiscriminator')
            dyeesidown.SetName(b[i]+'_CMS_EESigma_13TeVDown')

        else:
            dyall = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dytfakes = DY.Get('TauLooseOS'+di+'/bdtDiscriminator')
            dyefakes = DY.Get('EleLooseOS'+di+'/bdtDiscriminator')
            dyetfakes = DY.Get('EleLooseTauLooseOS'+di+'/bdtDiscriminator')
            dyfakes = dytfakes.Clone()
            dyfakes.Add(dyefakes)
            dyfakes.Add(dyetfakes, -1)
            dyfakes = positivize(dyfakes)
            dyall.Add(dyfakes, -1)
            dy = positivize(dyall)
            dy.SetName(b[i])

            dypuup = DY.Get('TightOS'+di+'/puUp/bdtDiscriminator')
            dypuup.Add(dyfakes, -1)
            dypuup = positivize(dypuup)
            dypuup.SetName(b[i]+'_CMS_Pileup_13TeVUp')
            dypudown = DY.Get('TightOS'+di+'/puDown/bdtDiscriminator')
            dypudown.Add(dyfakes, -1)
            dypudown = positivize(dypudown)
            dypudown.SetName(b[i]+'_CMS_Pileup_13TeVDown')

            dytidup = DY.Get('TightOS'+di+'/tidUp/bdtDiscriminator')
            dytidup.Add(dyfakes, -1)
            dytidup = positivize(dytidup)
            dytidup.SetName(b[i]+'_CMS_eff_tauUp')
            dytiddown = DY.Get('TightOS'+di+'/tidDown/bdtDiscriminator')
            dytiddown.Add(dyfakes, -1)
            dytiddown = positivize(dytiddown)
            dytiddown.SetName(b[i]+'_CMS_eff_tauDown')
        
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/bdtDiscriminator')
                dyrecrespup.Add(dyfakes, -1)
                dyrecrespup = positivize(dyrecrespup)
                dyrecrespup.SetName(b[i]+'_CMS_RecoilResponse_13TeVUp')
                dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/bdtDiscriminator')
                dyrecrespdown.Add(dyfakes, -1)
                dyrecrespdown = positivize(dyrecrespdown)
                dyrecrespdown.SetName(b[i]+'_CMS_RecoilResponse_13TeVDown')

                dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/bdtDiscriminator')
                dyrecresoup.Add(dyfakes, -1)
                dyrecresoup = positivize(dyrecresoup)
                dyrecresoup.SetName(b[i]+'_CMS_RecoilResolution_13TeVUp')
                dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/bdtDiscriminator')
                dyrecresodown.Add(dyfakes, -1)
                dyrecresodown = positivize(dyrecresodown)
                dyrecresodown.SetName(b[i]+'_CMS_RecoilResolution_13TeVDown')

            if b[i]=='Zll':
                dyptup = DY.Get('TightOS'+di+'/DYptreweightUp/bdtDiscriminator')
                dyptup.Add(dyfakes, -1)
                dyptup = positivize(dyptup)
                dyptup.SetName(b[i]+'_CMS_DYpTreweight_13TeVUp')
                dyptdown = DY.Get('TightOS'+di+'/DYptreweightDown/bdtDiscriminator')
                dyptdown.Add(dyfakes, -1)
                dyptdown = positivize(dyptdown)
                dyptdown.SetName(b[i]+'_CMS_DYpTreweight_13TeVDown')

            if b[i]=='TT' or b[i]=='ST':
                dybtagup = DY.Get('TightOS'+di+'/bTagUp/bdtDiscriminator')
                dybtagup.Add(dyfakes, -1)
                dybtagup = positivize(dybtagup)
                dybtagup.SetName(b[i]+'_CMS_eff_btag_13TeVUp')
                dybtagdown = DY.Get('TightOS'+di+'/bTagDown/bdtDiscriminator')
                dybtagdown.Add(dyfakes, -1)
                dybtagdown = positivize(dybtagdown)
                dybtagdown.SetName(b[i]+'_CMS_eff_btag_13TeVDown')

            if b[i]=='TT':
                dytptup = DY.Get('TightOS'+di+'/TopptreweightUp/bdtDiscriminator')
                dytptup.Add(dyfakes, -1)
                dytptup = positivize(dytptup)
                dytptup.SetName(b[i]+'_CMS_ToppTreweight_13TeVUp')
                dytptdown = DY.Get('TightOS'+di+'/TopptreweightDown/bdtDiscriminator')
                dytptdown.Add(dyfakes, -1)
                dytptdown = positivize(dytptdown)
                dytptdown.SetName(b[i]+'_CMS_ToppTreweight_13TeVDown')

            dymtfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dymtfakeup.Add(dyfakes, -1)
            dymtfakeup = positivize(dymtfakeup)
            dymtfakeup.SetName(b[i]+'_CMS_scale_mfaketau_13TeVUp')
            dymtfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dymtfakedown.Add(dyfakes, -1)
            dymtfakedown = positivize(dymtfakedown)
            dymtfakedown.SetName(b[i]+'_CMS_scale_mfaketau_13TeVDown')
            
            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dyetfakeup.Add(dyfakes, -1)
            dyetfakeup = positivize(dyetfakeup)
            dyetfakeup.SetName(b[i]+'_CMS_scale_efaketau_13TeVUp')
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dyetfakedown.Add(dyfakes, -1)
            dyetfakedown = positivize(dyetfakedown)
            dyetfakedown.SetName(b[i]+'_CMS_scale_efaketau_13TeVDown')
            
            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/bdtDiscriminator')
            dyetefakeup.Add(dyfakes, -1)
            dyetefakeup = positivize(dyetefakeup)
            dyetefakeup.SetName(b[i]+'_CMS_scale_efaketaues_13TeVUp')
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/bdtDiscriminator')
            dyetefakedown.Add(dyfakes, -1)
            dyetefakedown = positivize(dyetefakedown)
            dyetefakedown.SetName(b[i]+'_CMS_scale_efaketaues_13TeVDown')

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
            dytes0up.Add(dyfakes, -1)
            dytes0up = positivize(dytes0up)
            dytes0up.SetName(b[i]+'_CMS_scale_t_1prong_13TeVUp')
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
            dytes0down.Add(dyfakes, -1)
            dytes0down = positivize(dytes0down)
            dytes0down.SetName(b[i]+'_CMS_scale_t_1prong_13TeVDown')

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
            dytes1up.Add(dyfakes, -1)
            dytes1up = positivize(dytes1up)
            dytes1up.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp')
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
            dytes1down.Add(dyfakes, -1)
            dytes1down = positivize(dytes1down)
            dytes1down.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown')
            
            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
            dytes10up.Add(dyfakes, -1)
            dytes10up = positivize(dytes10up)
            dytes10up.SetName(b[i]+'_CMS_scale_t_3prong_13TeVUp')
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
            dytes10down.Add(dyfakes, -1)
            dytes10down = positivize(dytes10down)
            dytes10down.SetName(b[i]+'_CMS_scale_t_3prong_13TeVDown')
            
            #Electron Energy Scale
            dyeescup = DY.Get('TightOS'+di+'/eescUp/bdtDiscriminator')
            dyeescup.Add(dyfakes, -1)
            dyeescup = positivize(dyeescup)
            dyeescup.SetName(b[i]+'_CMS_EEScale_13TeVUp')
            dyeescdown = DY.Get('TightOS'+di+'/eescDown/bdtDiscriminator')
            dyeescdown.Add(dyfakes, -1)
            dyeescdown = positivize(dyeescdown)
            dyeescdown.SetName(b[i]+'_CMS_EEScale_13TeVDown')

            #Electron Energy Sigma
            dyeesiup = DY.Get('TightOS'+di+'/eesiUp/bdtDiscriminator')
            dyeesiup.Add(dyfakes, -1)
            dyeesiup = positivize(dyeesiup)
            dyeesiup.SetName(b[i]+'_CMS_EESigma_13TeVUp')
            dyeesidown = DY.Get('TightOS'+di+'/eesiDown/bdtDiscriminator')
            dyeesidown.Add(dyfakes, -1)
            dyeesidown = positivize(dyeesidown)
            dyeesidown.SetName(b[i]+'_CMS_EESigma_13TeVDown')

            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup = DY.Get('TightOS'+di+'/UnclusteredEnUp/bdtDiscriminator')
                dyuesup.Add(dyfakes, -1)
                dyuesup = positivize(dyuesup)
                dyuesup.SetName(b[i]+'_CMS_MET_Ues_13TeVUp')
                dyuesdown = DY.Get('TightOS'+di+'/UnclusteredEnDown/bdtDiscriminator')
                dyuesdown.Add(dyfakes, -1)
                dyuesdown = positivize(dyuesdown)
                dyuesdown.SetName(b[i]+'_CMS_MET_Ues_13TeVDown')
        
                dyjetAFMup = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapUp/bdtDiscriminator')
                dyjetAFMup.Add(dyfakes, -1)
                dyjetAFMup = positivize(dyjetAFMup)
                dyjetAFMup.SetName(b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVUp')
                dyjetAFMdown = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapDown/bdtDiscriminator')
                dyjetAFMdown.Add(dyfakes, -1)
                dyjetAFMdown = positivize(dyjetAFMdown)
                dyjetAFMdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVDown')
        
                dyjetAMPFBup = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasUp/bdtDiscriminator')
                dyjetAMPFBup.Add(dyfakes, -1)
                dyjetAMPFBup = positivize(dyjetAMPFBup)
                dyjetAMPFBup.SetName(b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVUp')
                dyjetAMPFBdown = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasDown/bdtDiscriminator')
                dyjetAMPFBdown.Add(dyfakes, -1)
                dyjetAMPFBdown = positivize(dyjetAMPFBdown)
                dyjetAMPFBdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVDown')
        
                dyjetASup = DY.Get('TightOS'+di+'/JetAbsoluteScaleUp/bdtDiscriminator')
                dyjetASup.Add(dyfakes, -1)
                dyjetASup = positivize(dyjetASup)
                dyjetASup.SetName(b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVUp')
                dyjetASdown = DY.Get('TightOS'+di+'/JetAbsoluteScaleDown/bdtDiscriminator')
                dyjetASdown.Add(dyfakes, -1)
                dyjetASdown = positivize(dyjetASdown)
                dyjetASdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVDown')

                dyjetAStup = DY.Get('TightOS'+di+'/JetAbsoluteStatUp/bdtDiscriminator')
                dyjetAStup.Add(dyfakes, -1)
                dyjetAStup = positivize(dyjetAStup)
                dyjetAStup.SetName(b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVUp')
                dyjetAStdown = DY.Get('TightOS'+di+'/JetAbsoluteStatDown/bdtDiscriminator')
                dyjetAStdown.Add(dyfakes, -1)
                dyjetAStdown = positivize(dyjetAStdown)
                dyjetAStdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVDown')
            
                dyjetFQCDup = DY.Get('TightOS'+di+'/JetFlavorQCDUp/bdtDiscriminator')
                dyjetFQCDup.Add(dyfakes, -1)
                dyjetFQCDup = positivize(dyjetFQCDup)
                dyjetFQCDup.SetName(b[i]+'_CMS_Jes_JetFlavorQCD_13TeVUp')
                dyjetFQCDdown = DY.Get('TightOS'+di+'/JetFlavorQCDDown/bdtDiscriminator')
                dyjetFQCDdown.Add(dyfakes, -1)
                dyjetFQCDdown = positivize(dyjetFQCDdown)
                dyjetFQCDdown.SetName(b[i]+'_CMS_Jes_JetFlavorQCD_13TeVDown')

                dyjetFup = DY.Get('TightOS'+di+'/JetFragmentationUp/bdtDiscriminator')
                dyjetFup.Add(dyfakes, -1)
                dyjetFup = positivize(dyjetFup)
                dyjetFup.SetName(b[i]+'_CMS_Jes_JetFragmentation_13TeVUp')
                dyjetFdown = DY.Get('TightOS'+di+'/JetFragmentationDown/bdtDiscriminator')
                dyjetFdown.Add(dyfakes, -1)
                dyjetFdown = positivize(dyjetFdown)
                dyjetFdown.SetName(b[i]+'_CMS_Jes_JetFragmentation_13TeVDown')

                dyjetPUDMCup = DY.Get('TightOS'+di+'/JetPileUpDataMCUp/bdtDiscriminator')
                dyjetPUDMCup.Add(dyfakes, -1)
                dyjetPUDMCup = positivize(dyjetPUDMCup)
                dyjetPUDMCup.SetName(b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVUp')
                dyjetPUDMCdown = DY.Get('TightOS'+di+'/JetPileUpDataMCDown/bdtDiscriminator')
                dyjetPUDMCdown.Add(dyfakes, -1)
                dyjetPUDMCdown = positivize(dyjetPUDMCdown)
                dyjetPUDMCdown.SetName(b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVDown')

                dyjetPUPBBup = DY.Get('TightOS'+di+'/JetPileUpPtBBUp/bdtDiscriminator')
                dyjetPUPBBup.Add(dyfakes, -1)
                dyjetPUPBBup = positivize(dyjetPUPBBup)
                dyjetPUPBBup.SetName(b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVUp')
                dyjetPUPBBdown = DY.Get('TightOS'+di+'/JetPileUpPtBBDown/bdtDiscriminator')
                dyjetPUPBBdown.Add(dyfakes, -1)
                dyjetPUPBBdown = positivize(dyjetPUPBBdown)
                dyjetPUPBBdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVDown')
                
                dyjetPUPEC1up = DY.Get('TightOS'+di+'/JetPileUpPtEC1Up/bdtDiscriminator')
                dyjetPUPEC1up.Add(dyfakes, -1)
                dyjetPUPEC1up = positivize(dyjetPUPEC1up)
                dyjetPUPEC1up.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVUp')
                dyjetPUPEC1down = DY.Get('TightOS'+di+'/JetPileUpPtEC1Down/bdtDiscriminator')
                dyjetPUPEC1down.Add(dyfakes, -1)
                dyjetPUPEC1down = positivize(dyjetPUPEC1down)
                dyjetPUPEC1down.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVDown')

                dyjetPUPEC2up = DY.Get('TightOS'+di+'/JetPileUpPtEC2Up/bdtDiscriminator')
                dyjetPUPEC2up.Add(dyfakes, -1)
                dyjetPUPEC2up = positivize(dyjetPUPEC2up)
                dyjetPUPEC2up.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVUp')
                dyjetPUPEC2down = DY.Get('TightOS'+di+'/JetPileUpPtEC2Down/bdtDiscriminator')
                dyjetPUPEC2down.Add(dyfakes, -1)
                dyjetPUPEC2down = positivize(dyjetPUPEC2down)
                dyjetPUPEC2down.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVDown')

                dyjetPUPHFup = DY.Get('TightOS'+di+'/JetPileUpPtHFUp/bdtDiscriminator')
                dyjetPUPHFup.Add(dyfakes, -1)
                dyjetPUPHFup = positivize(dyjetPUPHFup)
                dyjetPUPHFup.SetName(b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVUp')
                dyjetPUPHFdown = DY.Get('TightOS'+di+'/JetPileUpPtHFDown/bdtDiscriminator')
                dyjetPUPHFdown.Add(dyfakes, -1)
                dyjetPUPHFdown = positivize(dyjetPUPHFdown)
                dyjetPUPHFdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVDown')
        
                dyjetPUPRup = DY.Get('TightOS'+di+'/JetPileUpPtRefUp/bdtDiscriminator')
                dyjetPUPRup.Add(dyfakes, -1)
                dyjetPUPRup = positivize(dyjetPUPRup)
                dyjetPUPRup.SetName(b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVUp')
                dyjetPUPRdown = DY.Get('TightOS'+di+'/JetPileUpPtRefDown/bdtDiscriminator')
                dyjetPUPRdown.Add(dyfakes, -1)
                dyjetPUPRdown = positivize(dyjetPUPRdown)
                dyjetPUPRdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVDown')
        
                dyjetRFSRup = DY.Get('TightOS'+di+'/JetRelativeFSRUp/bdtDiscriminator')
                dyjetRFSRup.Add(dyfakes, -1)
                dyjetRFSRup = positivize(dyjetRFSRup)
                dyjetRFSRup.SetName(b[i]+'_CMS_Jes_JetRelativeFSR_13TeVUp')
                dyjetRFSRdown = DY.Get('TightOS'+di+'/JetRelativeFSRDown/bdtDiscriminator')
                dyjetRFSRdown.Add(dyfakes, -1)
                dyjetRFSRdown = positivize(dyjetRFSRdown)
                dyjetRFSRdown.SetName(b[i]+'_CMS_Jes_JetRelativeFSR_13TeVDown')
        
                dyjetRJEREC1up = DY.Get('TightOS'+di+'/JetRelativeJEREC1Up/bdtDiscriminator')
                dyjetRJEREC1up.Add(dyfakes, -1)
                dyjetRJEREC1up = positivize(dyjetRJEREC1up)
                dyjetRJEREC1up.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVUp')
                dyjetRJEREC1down = DY.Get('TightOS'+di+'/JetRelativeJEREC1Down/bdtDiscriminator')
                dyjetRJEREC1down.Add(dyfakes, -1)
                dyjetRJEREC1down = positivize(dyjetRJEREC1down)
                dyjetRJEREC1down.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVDown')
        
                dyjetRJEREC2up = DY.Get('TightOS'+di+'/JetRelativeJEREC2Up/bdtDiscriminator')
                dyjetRJEREC2up.Add(dyfakes, -1)
                dyjetRJEREC2up = positivize(dyjetRJEREC2up)
                dyjetRJEREC2up.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVUp')
                dyjetRJEREC2down = DY.Get('TightOS'+di+'/JetRelativeJEREC2Down/bdtDiscriminator')
                dyjetRJEREC2down.Add(dyfakes, -1)
                dyjetRJEREC2down = positivize(dyjetRJEREC2down)
                dyjetRJEREC2down.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVDown')

                dyjetRJERHFup = DY.Get('TightOS'+di+'/JetRelativeJERHFUp/bdtDiscriminator')
                dyjetRJERHFup.Add(dyfakes, -1)
                dyjetRJERHFup = positivize(dyjetRJERHFup)
                dyjetRJERHFup.SetName(b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVUp')
                dyjetRJERHFdown = DY.Get('TightOS'+di+'/JetRelativeJERHFDown/bdtDiscriminator')
                dyjetRJERHFdown.Add(dyfakes, -1)
                dyjetRJERHFdown = positivize(dyjetRJERHFdown)
                dyjetRJERHFdown.SetName(b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVDown')
        
                dyjetRPBBup = DY.Get('TightOS'+di+'/JetRelativePtBBUp/bdtDiscriminator')
                dyjetRPBBup.Add(dyfakes, -1)
                dyjetRPBBup = positivize(dyjetRPBBup)
                dyjetRPBBup.SetName(b[i]+'_CMS_Jes_JetRelativePtBB_13TeVUp')
                dyjetRPBBdown = DY.Get('TightOS'+di+'/JetRelativePtBBDown/bdtDiscriminator')
                dyjetRPBBdown.Add(dyfakes, -1)
                dyjetRPBBdown = positivize(dyjetRPBBdown)
                dyjetRPBBdown.SetName(b[i]+'_CMS_Jes_JetRelativePtBB_13TeVDown')

                dyjetRPEC1up = DY.Get('TightOS'+di+'/JetRelativePtEC1Up/bdtDiscriminator')
                dyjetRPEC1up.Add(dyfakes, -1)
                dyjetRPEC1up = positivize(dyjetRPEC1up)
                dyjetRPEC1up.SetName(b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVUp')
                dyjetRPEC1down = DY.Get('TightOS'+di+'/JetRelativePtEC1Down/bdtDiscriminator')
                dyjetRPEC1down.Add(dyfakes, -1)
                dyjetRPEC1down = positivize(dyjetRPEC1down)
                dyjetRPEC1down.SetName(b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVDown')
                
                dyjetRPEC2up = DY.Get('TightOS'+di+'/JetRelativePtEC2Up/bdtDiscriminator')
                dyjetRPEC2up.Add(dyfakes, -1)
                dyjetRPEC2up = positivize(dyjetRPEC2up)
                dyjetRPEC2up.SetName(b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVUp')
                dyjetRPEC2down = DY.Get('TightOS'+di+'/JetRelativePtEC2Down/bdtDiscriminator')
                dyjetRPEC2down.Add(dyfakes, -1)
                dyjetRPEC2down = positivize(dyjetRPEC2down)
                dyjetRPEC2down.SetName(b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVDown')

                dyjetRPHFup = DY.Get('TightOS'+di+'/JetRelativePtHFUp/bdtDiscriminator')
                dyjetRPHFup.Add(dyfakes, -1)
                dyjetRPHFup = positivize(dyjetRPHFup)
                dyjetRPHFup.SetName(b[i]+'_CMS_Jes_JetRelativePtHF_13TeVUp')
                dyjetRPHFdown = DY.Get('TightOS'+di+'/JetRelativePtHFDown/bdtDiscriminator')
                dyjetRPHFdown.Add(dyfakes, -1)
                dyjetRPHFdown = positivize(dyjetRPHFdown)
                dyjetRPHFdown.SetName(b[i]+'_CMS_Jes_JetRelativePtHF_13TeVDown')
        
                dyjetRSECup = DY.Get('TightOS'+di+'/JetRelativeStatECUp/bdtDiscriminator')
                dyjetRSECup.Add(dyfakes, -1)
                dyjetRSECup = positivize(dyjetRSECup)
                dyjetRSECup.SetName(b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVUp')
                dyjetRSECdown = DY.Get('TightOS'+di+'/JetRelativeStatECDown/bdtDiscriminator')
                dyjetRSECdown.Add(dyfakes, -1)
                dyjetRSECdown = positivize(dyjetRSECdown)
                dyjetRSECdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVDown')
        
                dyjetRSFSRup = DY.Get('TightOS'+di+'/JetRelativeStatFSRUp/bdtDiscriminator')
                dyjetRSFSRup.Add(dyfakes, -1)
                dyjetRSFSRup = positivize(dyjetRSFSRup)
                dyjetRSFSRup.SetName(b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVUp')
                dyjetRSFSRdown = DY.Get('TightOS'+di+'/JetRelativeStatFSRDown/bdtDiscriminator')
                dyjetRSFSRdown.Add(dyfakes, -1)
                dyjetRSFSRdown = positivize(dyjetRSFSRdown)
                dyjetRSFSRdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVDown')
        
                dyjetRSHFup = DY.Get('TightOS'+di+'/JetRelativeStatHFUp/bdtDiscriminator')
                dyjetRSHFup.Add(dyfakes, -1)
                dyjetRSHFup = positivize(dyjetRSHFup)
                dyjetRSHFup.SetName(b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVUp')
                dyjetRSHFdown = DY.Get('TightOS'+di+'/JetRelativeStatHFDown/bdtDiscriminator')
                dyjetRSHFdown.Add(dyfakes, -1)
                dyjetRSHFdown = positivize(dyjetRSHFdown)
                dyjetRSHFdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVDown')

                dyjetSPEup = DY.Get('TightOS'+di+'/JetSinglePionECALUp/bdtDiscriminator')
                dyjetSPEup.Add(dyfakes, -1)
                dyjetSPEup = positivize(dyjetSPEup)
                dyjetSPEup.SetName(b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVUp')
                dyjetSPEdown = DY.Get('TightOS'+di+'/JetSinglePionECALDown/bdtDiscriminator')
                dyjetSPEdown.Add(dyfakes, -1)
                dyjetSPEdown = positivize(dyjetSPEdown)
                dyjetSPEdown.SetName(b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVDown')
                
                dyjetSPHup = DY.Get('TightOS'+di+'/JetSinglePionHCALUp/bdtDiscriminator')
                dyjetSPHup.Add(dyfakes, -1)
                dyjetSPHup = positivize(dyjetSPHup)
                dyjetSPHup.SetName(b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVUp')
                dyjetSPHdown = DY.Get('TightOS'+di+'/JetSinglePionHCALDown/bdtDiscriminator')
                dyjetSPHdown.Add(dyfakes, -1)
                dyjetSPHdown = positivize(dyjetSPHdown)
                dyjetSPHdown.SetName(b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVDown')
        
                dyjetTPEup = DY.Get('TightOS'+di+'/JetTimePtEtaUp/bdtDiscriminator')
                dyjetTPEup.Add(dyfakes, -1)
                dyjetTPEup = positivize(dyjetTPEup)
                dyjetTPEup.SetName(b[i]+'_CMS_Jes_JetTimePtEta_13TeVUp')
                dyjetTPEdown = DY.Get('TightOS'+di+'/JetTimePtEtaDown/bdtDiscriminator')
                dyjetTPEdown.Add(dyfakes, -1)
                dyjetTPEdown = positivize(dyjetTPEdown)
                dyjetTPEdown.SetName(b[i]+'_CMS_Jes_JetTimePtEta_13TeVDown')
                
                dyjetRBup = DY.Get('TightOS'+di+'/JetRelativeBalUp/bdtDiscriminator')
                dyjetRBup.Add(dyfakes, -1)
                dyjetRBup = positivize(dyjetRBup)
                dyjetRBup.SetName(b[i]+'_CMS_Jes_JetRelativeBal_13TeVUp')
                dyjetRBdown = DY.Get('TightOS'+di+'/JetRelativeBalDown/bdtDiscriminator')
                dyjetRBdown.Add(dyfakes, -1)
                dyjetRBdown = positivize(dyjetRBdown)
                dyjetRBdown.SetName(b[i]+'_CMS_Jes_JetRelativeBal_13TeVDown')
        
                dyjetRSup = DY.Get('TightOS'+di+'/JetRelativeSampleUp/bdtDiscriminator')
                dyjetRSup.Add(dyfakes, -1)
                dyjetRSup = positivize(dyjetRSup)
                dyjetRSup.SetName(b[i]+'_CMS_Jes_JetRelativeSample_13TeVUp')
                dyjetRSdown = DY.Get('TightOS'+di+'/JetRelativeSampleDown/bdtDiscriminator')
                dyjetRSdown.Add(dyfakes, -1)
                dyjetRSdown = positivize(dyjetRSdown)
                dyjetRSdown.SetName(b[i]+'_CMS_Jes_JetRelativeSample_13TeVDown')

            dyall = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dyte0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator') 
            dyte0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
            dyte1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator') 
            dyte1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
            dyte10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator') 
            dyte10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
            dytb0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator') 
            dytb0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
            dytb1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator') 
            dytb1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
            dytb10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator') 
            dytb10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
            dyefakesup = DY.Get('EleLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
            dyefakesdown = DY.Get('EleLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
            dyette0fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
            dyette0fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
            dyette1fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
            dyette1fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
            dyette10fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
            dyette10fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
            dyettb0fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
            dyettb0fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
            dyettb1fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
            dyettb1fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
            dyettb10fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
            dyettb10fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
            dyetefakesup = DY.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/bdtDiscriminator')
            dyetefakesdown = DY.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/bdtDiscriminator')
            dy1e0 = dyall.Clone()
            dy1te0 = dyte0fakesup.Clone()
            dy1te0.add(dyefakes)
            dy1te0.add(dyette0fakesup, -1)
            dy1te0 = positivize(dy1te0)
            dy1e0.add(dy1te0, -1)
            dy1e0 = positivize(dy1e0)
            dy1e0.SetName(b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVUp')
            dy2e0 = dyall.Clone()
            dy2te0 = dyte0fakesdown.Clone()
            dy2te0.add(dyefakes)
            dy2te0.add(dyette0fakesdown, -1)
            dy2te0 = positivize(dy2te0)
            dy2e0.add(dy2te0, -1)
            dy2e0 = positivize(dy2e0)
            dy2e0.SetName(b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVDown')
            dy1e1 = dyall.Clone()
            dy1te1 = dyte1fakesup.Clone()
            dy1te1.add(dyefakes)
            dy1te1.add(dyette1fakesup, -1)
            dy1te1 = positivize(dy1te1)
            dy1e1.add(dy1te1, -1)
            dy1e1 = positivize(dy1e1)
            dy1e1.SetName(b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVUp')
            dy2e1 = dyall.Clone()
            dy2te1 = dyte1fakesdown.Clone()
            dy2te1.add(dyefakes)
            dy2te1.add(dyette1fakesdown, -1)
            dy2te1 = positivize(dy2te1)
            dy2e1.add(dy2te1, -1)
            dy2e1 = positivize(dy2e1)
            dy2e1.SetName(b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVDown')
            dy1e10 = dyall.Clone()
            dy1te10 = dyte10fakesup.Clone()
            dy1te10.add(dyefakes)
            dy1te10.add(dyette10fakesup, -1)
            dy1te10 = positivize(dy1te10)
            dy1e10.add(dy1te10, -1)
            dy1e10 = positivize(dy1e10)
            dy1e10.SetName(b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVUp')
            dy2e10 = dyall.Clone()
            dy2te10 = dyte10fakesdown.Clone()
            dy2te10.add(dyefakes)
            dy2te10.add(dyette10fakesdown, -1)
            dy2te10 = positivize(dy2te10)
            dy2e10.add(dy2te10, -1)
            dy2e10 = positivize(dy2e10)
            dy2e10.SetName(b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVDown')
            dy1b0 = dyall.Clone()
            dy1tb0 = dytb0fakesup.Clone()
            dy1tb0.add(dyefakes)
            dy1tb0.add(dyettb0fakesup, -1)
            dy1tb0 = positivize(dy1tb0)
            dy1b0.add(dy1tb0, -1)
            dy1b0 = positivize(dy1b0)
            dy1b0.SetName(b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVUp')
            dy2b0 = dyall.Clone()
            dy2tb0 = dytb0fakesdown.Clone()
            dy2tb0.add(dyefakes)
            dy2tb0.add(dyettb0fakesdown, -1)
            dy2tb0 = positivize(dy2tb0)
            dy2b0.add(dy2tb0, -1)
            dy2b0 = positivize(dy2b0)
            dy2b0.SetName(b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVDown')
            dy1b1 = dyall.Clone()
            dy1tb1 = dytb1fakesup.Clone()
            dy1tb1.add(dyefakes)
            dy1tb1.add(dyettb1fakesup, -1)
            dy1tb1 = positivize(dy1tb1)
            dy1b1.add(dy1tb1, -1)
            dy1b1 = positivize(dy1b1)
            dy1b1.SetName(b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVUp')
            dy2b1 = dyall.Clone()
            dy2tb1 = dytb1fakesdown.Clone()
            dy2tb1.add(dyefakes)
            dy2tb1.add(dyettb1fakesdown, -1)
            dy2tb1 = positivize(dy2tb1)
            dy2b1.add(dy2tb1, -1)
            dy2b1 = positivize(dy2b1)
            dy2b1.SetName(b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVDown')
            dy1b10 = dyall.Clone()
            dy1tb10 = dytb10fakesup.Clone()
            dy1tb10.add(dyefakes)
            dy1tb10.add(dyettb10fakesup, -1)
            dy1tb10 = positivize(dy1tb10)
            dy1b10.add(dy1tb10, -1)
            dy1b10 = positivize(dy1b10)
            dy1b10.SetName(b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVUp')
            dy2b10 = dyall.Clone()
            dy2tb10 = dytb10fakesdown.Clone()
            dy2tb10.add(dyefakes)
            dy2tb10.add(dyettb10fakesdown, -1)
            dy2tb10 = positivize(dy2tb10)
            dy2b10.add(dy2tb10, -1)
            dy2b10 = positivize(dy2b10)
            dy2b10.SetName(b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVDown')
            dy3 = dyall.Clone()
            dy3t = dytfakes.Clone()
            dy3t.add(dyefakesup)
            dy3t.add(dyetefakesup, -1)
            dy3t = positivize(dy3t)
            dy3.add(dy3t, -1)
            dy3 = positivize(dy3)
            dy3.SetName(b[i]+'_CMS_EleFakeRate_13TeVUp')
            dy4 = dyall.Clone()
            dy4t = dytfakes.Clone()
            dy4t.add(dyefakesdown)
            dy4t.add(dyetefakesdown, -1)
            dy4t = positivize(dy4t)
            dy4.add(dy4t, -1)
            dy4 = positivize(dy4)
            dy4.SetName(b[i]+'_CMS_EleFakeRate_13TeVDown')
            dyall.Delete()
            dy1te0.Delete()
            dy2te0.Delete()
            dy1te1.Delete()
            dy2te1.Delete()
            dy1te10.Delete()
            dy2te10.Delete()
            dy1tb0.Delete()
            dy2tb0.Delete()
            dy1tb1.Delete()
            dy2tb1.Delete()
            dy1tb10.Delete()
            dy2tb10.Delete()
            dy3t.Delete()
            dy4t.Delete()
            dyfakes.Delete()
            dytfakes.Delete()
            dyefakes.Delete()
            dyetfakes.Delete()
            dyte0fakesup.Delete()
            dyte0fakesdown.Delete()
            dyte1fakesup.Delete()
            dyte1fakesdown.Delete()
            dyte10fakesup.Delete()
            dyte10fakesdown.Delete()
            dytb0fakesup.Delete()
            dytb0fakesdown.Delete()
            dytb1fakesup.Delete()
            dytb1fakesdown.Delete()
            dytb10fakesup.Delete()
            dytb10fakesdown.Delete()
            dyefakesup.Delete()
            dyefakesdown.Delete()
            dyette0fakesup.Delete()
            dyette0fakesdown.Delete()
            dyette1fakesup.Delete()
            dyette1fakesdown.Delete()
            dyette10fakesup.Delete()
            dyette10fakesdown.Delete()
            dyettb0fakesup.Delete()
            dyettb0fakesdown.Delete()
            dyettb1fakesup.Delete()
            dyettb1fakesdown.Delete()
            dyettb10fakesup.Delete()
            dyettb10fakesdown.Delete()
            dyetefakesup.Delete()
            dyetefakesdown.Delete()

        f.Write()
        if i==0:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1e0.Delete()
            f2e0.Delete()
            f1e1.Delete()
            f2e1.Delete()
            f1e10.Delete()
            f2e10.Delete()
            f1b0.Delete()
            f2b0.Delete()
            f1b1.Delete()
            f2b1.Delete()
            f1b10.Delete()
            f2b10.Delete()
            f3.Delete()
            f4.Delete()
            emb1e0.Delete()
            emb2e0.Delete()
            emb1e1.Delete()
            emb2e1.Delete()
            emb1e10.Delete()
            emb2e10.Delete()
            emb1b0.Delete()
            emb2b0.Delete()
            emb1b1.Delete()
            emb2b1.Delete()
            emb1b10.Delete()
            emb2b10.Delete()
            emb3.Delete()
            emb4.Delete()
            embtrkup.Delete()
            embtrkdown.Delete()
            embtes0up.Delete()
            embtes0down.Delete()
            embtes1up.Delete()
            embtes1down.Delete()
            embtes10up.Delete()
            embtes10down.Delete()
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            dyrecrespup.Delete()
            dyrecrespdown.Delete()
            dyrecresoup.Delete()
            dyrecresodown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dyeescup.Delete()
            dyeescdown.Delete()
            dyeesiup.Delete()
            dyeesidown.Delete()
        else:
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup.Delete()
                dyrecrespdown.Delete()
                dyrecresoup.Delete()
                dyrecresodown.Delete()
            if b[i]=='Zll':
                dyptup.Delete()
                dyptdown.Delete()
            if b[i]=='TT' or b[i]=='ST':
                dybtagup.Delete()
                dybtagdown.Delete()
            if b[i]=='TT':
                dytptup.Delete()
                dytptdown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dyeescup.Delete()
            dyeescdown.Delete()
            dyeesiup.Delete()
            dyeesidown.Delete()
            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup.Delete()
                dyuesdown.Delete()
                dyjetAFMup.Delete()
                dyjetAFMdown.Delete()
                dyjetAMPFBup.Delete()
                dyjetAMPFBdown.Delete()
                dyjetASup.Delete()
                dyjetASdown.Delete()
                dyjetAStup.Delete()
                dyjetAStdown.Delete()
                dyjetFQCDup.Delete()
                dyjetFQCDdown.Delete()
                dyjetFup.Delete()
                dyjetFdown.Delete()
                dyjetPUDMCup.Delete()
                dyjetPUDMCdown.Delete()
                dyjetPUPBBup.Delete()
                dyjetPUPBBdown.Delete()
                dyjetPUPEC1up.Delete()
                dyjetPUPEC1down.Delete()
                dyjetPUPEC2up.Delete()
                dyjetPUPEC2down.Delete()
                dyjetPUPHFup.Delete()
                dyjetPUPHFdown.Delete()
                dyjetPUPRup.Delete()
                dyjetPUPRdown.Delete()
                dyjetRFSRup.Delete()
                dyjetRFSRdown.Delete()
                dyjetRJEREC1up.Delete()
                dyjetRJEREC1down.Delete()
                dyjetRJEREC2up.Delete()
                dyjetRJEREC2down.Delete()
                dyjetRJERHFup.Delete()
                dyjetRJERHFdown.Delete()
                dyjetRPBBup.Delete()
                dyjetRPBBdown.Delete()
                dyjetRPEC1up.Delete()
                dyjetRPEC1down.Delete()
                dyjetRPEC2up.Delete()
                dyjetRPEC2down.Delete()
                dyjetRPHFup.Delete()
                dyjetRPHFdown.Delete()
                dyjetRSECup.Delete()
                dyjetRSECdown.Delete()
                dyjetRSFSRup.Delete()
                dyjetRSFSRdown.Delete()
                dyjetRSHFup.Delete()
                dyjetRSHFdown.Delete()
                dyjetSPEup.Delete()
                dyjetSPEdown.Delete()
                dyjetSPHup.Delete()
                dyjetSPHdown.Delete()
                dyjetTPEup.Delete()
                dyjetTPEdown.Delete()
                dyjetRBup.Delete()
                dyjetRBdown.Delete()
                dyjetRSup.Delete()
                dyjetRSdown.Delete()
            dy1e0.Delete()
            dy2e0.Delete()
            dy1e1.Delete()
            dy2e1.Delete()
            dy1e10.Delete()
            dy2e10.Delete()
            dy1b0.Delete()
            dy2b0.Delete()
            dy1b1.Delete()
            dy2b1.Delete()
            dy1b10.Delete()
            dy2b10.Delete()
            dy3.Delete()
            dy4.Delete()
