import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'mt'
period = '13TeV'
sqrts = 13

def positivize(histogram):
    output = histogram.Clone()
    for i in range(output.GetSize()):
        if output.GetArray()[i] < 0:
            output.AddAt(0, i)
    return output

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'GluGluHToWW*', 'VBFHToWW*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('../results/%s/AnalyzeMuTauSys/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('../inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = '../plots/%s/AnalyzeMuTauSys/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'shapes/shapesMT.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') or x.startswith('DYJetsToLL_M-10to50'), mc_samples )]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('EWK') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGluHToTauTau') or x.startswith('GluGluHToWW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBFHToTauTau') or x.startswith('VBFHToWW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('WminusHToTauTau') or x.startswith('WplusHToTauTau') or x.startswith('ZHToTauTau') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGlu_LFV') , mc_samples)]), 
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBF_LFV') , mc_samples)])
]

b = ['Zll', 'EWK', 'GluGluH', 'VBFH', 'VH', 'TT', 'ST', 'EWKDiboson', 'GluGlu125', 'VBF125']

for di in dirs:

    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    data = DataTotal.Get('TightOS'+di+'/m_t_CollinearMass')
    data.SetName('data_obs')
    
    embed = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    emball = embed.Get('TightOS'+di+'/m_t_CollinearMass')
    embtfakes = embed.Get('TauLooseOS'+di+'/m_t_CollinearMass')
    embmfakes = embed.Get('MuonLooseOS'+di+'/m_t_CollinearMass')
    embmtfakes = embed.Get('MuonLooseTauLooseOS'+di+'/m_t_CollinearMass')
    embfakes = embtfakes.Clone()
    embfakes.Add(embmfakes)
    embfakes.Add(embmtfakes, -1)
    embfakes = positivize(embfakes)
    emb = emball.Clone()
    emb.Add(embfakes, -1)
    emb = positivize(emb)
    emb.SetName('embed')

    embtrkup = embed.Get('TightOS'+di+'/embtrkUp/m_t_CollinearMass')
    embtrkup.Add(embfakes, -1)
    embtrkup = positivize(embtrkup)
    embtrkup.SetName('embed_CMS_tracking_tauUp')
    embtrkdown = embed.Get('TightOS'+di+'/embtrkDown/m_t_CollinearMass')
    embtrkdown.Add(embfakes, -1)
    embtrkdown = positivize(embtrkdown)
    embtrkdown.SetName('embed_CMS_tracking_tauDown')

    embtes0up = embed.Get('TightOS'+di+'/scaletDM0Up/m_t_CollinearMass')
    embtes0up.Add(embfakes, -1)
    embtes0up = positivize(embtes0up)
    embtes0up.SetName('embed_CMS_scale_t_1prong_13TeVUp')
    embtes0down = embed.Get('TightOS'+di+'/scaletDM0Down/m_t_CollinearMass')
    embtes0down.Add(embfakes, -1)
    embtes0down = positivize(embtes0down)
    embtes0down.SetName('embed_CMS_scale_t_1prong_13TeVDown')

    embtes1up = embed.Get('TightOS'+di+'/scaletDM1Up/m_t_CollinearMass')
    embtes1up.Add(embfakes, -1)
    embtes1up = positivize(embtes1up)
    embtes1up.SetName('embed_CMS_scale_t_1prong1pizero_13TeVUp')
    embtes1down = embed.Get('TightOS'+di+'/scaletDM1Down/m_t_CollinearMass')
    embtes1down.Add(embfakes, -1)
    embtes1down = positivize(embtes1down)
    embtes1down.SetName('embed_CMS_scale_t_1prong1pizero_13TeVDown')

    embtes10up = embed.Get('TightOS'+di+'/scaletDM10Up/m_t_CollinearMass')
    embtes10up.Add(embfakes, -1)
    embtes10up = positivize(embtes10up)
    embtes10up.SetName('embed_CMS_scale_t_3prong_13TeVUp')
    embtes10down = embed.Get('TightOS'+di+'/scaletDM10Down/m_t_CollinearMass')
    embtes10down.Add(embfakes, -1)
    embtes10down = positivize(embtes10down)
    embtes10down.SetName('embed_CMS_scale_t_3prong_13TeVDown')

    embtfakesup = embed.Get('TauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass')
    embtfakesdown = embed.Get('TauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
    embmfakesup = embed.Get('MuonLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
    embmfakesdown = embed.Get('MuonLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
    embmttfakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass')
    embmttfakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
    embmtmfakesup = embed.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
    embmtmfakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
    emb1 = emball.Clone()
    emb1t = embtfakesup.Clone()
    emb1t.add(embmfakes)
    emb1t.add(embmttfakesup, -1)
    emb1t = positivize(emb1t)
    emb1.add(emb1t, -1)
    emb1 = positivize(emb1)
    emb1.SetName('embed_CMS_TauFakeRate_13TeVUp')
    emb2 = emball.Clone()
    emb2t = embtfakesdown.Clone()
    emb2t.add(embmfakes)
    emb2t.add(embmttfakesdown, -1)
    emb2t = positivize(emb2t)
    emb2.add(emb2t, -1)
    emb2 = positivize(emb2)
    emb2.SetName('embed_CMS_TauFakeRate_13TeVDown')
    emb3 = emball.Clone()
    emb3t = embtfakes.Clone()
    emb3t.add(embmfakesup)
    emb3t.add(embmtmfakesup, -1)
    emb3t = positivize(emb3t)
    emb3.add(emb3t, -1)
    emb3 = positivize(emb3)
    emb3.SetName('embed_CMS_MuonFakeRate_13TeVUp')
    emb4 = emball.Clone()
    emb4t = embtfakes.Clone()
    emb4t.add(embmfakesdown)
    emb4t.add(embmtmfakesdown, -1)
    emb4t = positivize(emb4t)
    emb4.add(emb4t, -1)
    emb4 = positivize(emb4)
    emb4.SetName('embed_CMS_MuonFakeRate_13TeVDown')
    emball.Delete()
    emb1t.Delete()
    emb2t.Delete()
    emb3t.Delete()
    emb4t.Delete()
    embfakes.Delete()
    embtfakes.Delete()
    embmfakes.Delete()
    embmtfakes.Delete()
    embtfakesup.Delete()
    embtfakesdown.Delete()
    embmfakesup.Delete()
    embmfakesdown.Delete()
    embmttfakesup.Delete()
    embmttfakesdown.Delete()
    embmtmfakesup.Delete()
    embmtmfakesdown.Delete()
    
    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    tfakes = QCD.Get('TauLooseOS'+di+'/m_t_CollinearMass')
    mfakes = QCD.Get('MuonLooseOS'+di+'/m_t_CollinearMass')
    mtfakes = QCD.Get('MuonLooseTauLooseOS'+di+'/m_t_CollinearMass')
    qcd = tfakes.Clone()
    qcd.Add(mfakes)
    qcd.Add(mtfakes, -1)
    qcd = positivize(qcd)
    qcd.SetName('Fakes')
    tfakesup = QCD.Get('TauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass')
    tfakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
    mfakesup = QCD.Get('MuonLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
    mfakesdown = QCD.Get('MuonLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
    mttfakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass')
    mttfakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
    mtmfakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
    mtmfakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
    f1 = tfakesup.Clone()
    f1.add(mfakes)
    f1.add(mttfakesup, -1)
    f1 = positivize(f1)
    f1.SetName('Fakes_CMS_TauFakeRate_13TeVUp')
    f2 = tfakesdown.Clone()
    f2.add(mfakes)
    f2.add(mttfakesdown, -1)
    f2 = positivize(f2)
    f2.SetName('Fakes_CMS_TauFakeRate_13TeVDown')
    f3 = tfakes.Clone()
    f3.add(mfakesup)
    f3.add(mtmfakesup, -1)
    f3 = positivize(f3)
    f3.SetName('Fakes_CMS_MuonFakeRate_13TeVUp')
    f4 = tfakes.Clone()
    f4.add(mfakesdown)
    f4.add(mtmfakesdown, -1)
    f4 = positivize(f4)
    f4.SetName('Fakes_CMS_MuonFakeRate_13TeVDown')
    tfakes.Delete()
    mfakes.Delete()
    mtfakes.Delete()
    tfakesup.Delete()
    tfakesdown.Delete()
    mfakesup.Delete()
    mfakesdown.Delete()
    mttfakesup.Delete()
    mttfakesdown.Delete()
    mtmfakesup.Delete()
    mtmfakesdown.Delete()

    for i in range(10):
        DY = v[i]
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy = DY.Get('TightOS'+di+'/m_t_CollinearMass')
            dy.SetName(b[i])

            dypuup = DY.Get('TightOS'+di+'/puUp/m_t_CollinearMass')
            dypuup.SetName(b[i]+'_CMS_Pileup_13TeVUp')
            dypudown = DY.Get('TightOS'+di+'/puDown/m_t_CollinearMass')
            dypudown.SetName(b[i]+'_CMS_Pileup_13TeVDown')

            dytidup = DY.Get('TightOS'+di+'/tidUp/m_t_CollinearMass')
            dytidup.SetName(b[i]+'_CMS_eff_tauUp')
            dytiddown = DY.Get('TightOS'+di+'/tidDown/m_t_CollinearMass')
            dytiddown.SetName(b[i]+'_CMS_eff_tauDown')
        
            dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/m_t_CollinearMass')
            dyrecrespup.SetName(b[i]+'_CMS_RecoilResponse_13TeVUp')
            dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/m_t_CollinearMass')
            dyrecrespdown.SetName(b[i]+'_CMS_RecoilResponse_13TeVDown')

            dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/m_t_CollinearMass')
            dyrecresoup.SetName(b[i]+'_CMS_RecoilResolution_13TeVUp')
            dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/m_t_CollinearMass')
            dyrecresodown.SetName(b[i]+'_CMS_RecoilResolution_13TeVDown')

            dymtfakeup = DY.Get('TightOS'+di+'/mtfakeUp/m_t_CollinearMass')
            dymtfakeup.SetName(b[i]+'_CMS_scale_mfaketau_13TeVUp')
            dymtfakedown = DY.Get('TightOS'+di+'/mtfakeDown/m_t_CollinearMass')
            dymtfakedown.SetName(b[i]+'_CMS_scale_mfaketau_13TeVDown')

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/m_t_CollinearMass')
            dyetfakeup.SetName(b[i]+'_CMS_scale_efaketau_13TeVUp')
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/m_t_CollinearMass')
            dyetfakedown.SetName(b[i]+'_CMS_scale_efaketau_13TeVDown')

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/m_t_CollinearMass')
            dyetefakeup.SetName(b[i]+'_CMS_scale_efaketaues_13TeVUp')
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/m_t_CollinearMass')
            dyetefakedown.SetName(b[i]+'_CMS_scale_efaketaues_13TeVDown')

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/m_t_CollinearMass')
            dytes0up.SetName(b[i]+'_CMS_scale_t_1prong_13TeVUp')
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/m_t_CollinearMass')
            dytes0down.SetName(b[i]+'_CMS_scale_t_1prong_13TeVDown')

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/m_t_CollinearMass')
            dytes1up.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp')
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/m_t_CollinearMass')
            dytes1down.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown')

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/m_t_CollinearMass')
            dytes10up.SetName(b[i]+'_CMS_scale_t_3prong_13TeVUp')
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/m_t_CollinearMass')
            dytes10down.SetName(b[i]+'_CMS_scale_t_3prong_13TeVDown')

            dymesup = DY.Get('TightOS'+di+'/mesUp/m_t_CollinearMass')
            dymesup.SetName(b[i]+'_CMS_MES_13TeVUp')
            dymesdown = DY.Get('TightOS'+di+'/mesDown/m_t_CollinearMass')
            dymesdown.SetName(b[i]+'_CMS_MES_13TeVDown')

        else:
            dyall = DY.Get('TightOS'+di+'/m_t_CollinearMass')
            dytfakes = DY.Get('TauLooseOS'+di+'/m_t_CollinearMass')
            dymfakes = DY.Get('MuonLooseOS'+di+'/m_t_CollinearMass')
            dymtfakes = DY.Get('MuonLooseTauLooseOS'+di+'/m_t_CollinearMass')
            dyfakes = dytfakes.Clone()
            dyfakes.Add(dymfakes)
            dyfakes.Add(dymtfakes, -1)
            dyfakes = positivize(dyfakes)
            dyall.Add(dyfakes, -1)
            dy = positivize(dyall)
            dy.SetName(b[i])

            dypuup = DY.Get('TightOS'+di+'/puUp/m_t_CollinearMass')
            dypuup.Add(dyfakes, -1)
            dypuup = positivize(dypuup)
            dypuup.SetName(b[i]+'_CMS_Pileup_13TeVUp')
            dypudown = DY.Get('TightOS'+di+'/puDown/m_t_CollinearMass')
            dypudown.Add(dyfakes, -1)
            dypudown = positivize(dypudown)
            dypudown.SetName(b[i]+'_CMS_Pileup_13TeVDown')

            dytidup = DY.Get('TightOS'+di+'/tidUp/m_t_CollinearMass')
            dytidup.Add(dyfakes, -1)
            dytidup = positivize(dytidup)
            dytidup.SetName(b[i]+'_CMS_eff_tauUp')
            dytiddown = DY.Get('TightOS'+di+'/tidDown/m_t_CollinearMass')
            dytiddown.Add(dyfakes, -1)
            dytiddown = positivize(dytiddown)
            dytiddown.SetName(b[i]+'_CMS_eff_tauDown')
        
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH':
                dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/m_t_CollinearMass')
                dyrecrespup.Add(dyfakes, -1)
                dyrecrespup = positivize(dyrecrespup)
                dyrecrespup.SetName(b[i]+'_CMS_RecoilResponse_13TeVUp')
                dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/m_t_CollinearMass')
                dyrecrespdown.Add(dyfakes, -1)
                dyrecrespdown = positivize(dyrecrespdown)
                dyrecrespdown.SetName(b[i]+'_CMS_RecoilResponse_13TeVDown')

                dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/m_t_CollinearMass')
                dyrecresoup.Add(dyfakes, -1)
                dyrecresoup = positivize(dyrecresoup)
                dyrecresoup.SetName(b[i]+'_CMS_RecoilResolution_13TeVUp')
                dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/m_t_CollinearMass')
                dyrecresodown.Add(dyfakes, -1)
                dyrecresodown = positivize(dyrecresodown)
                dyrecresodown.SetName(b[i]+'_CMS_RecoilResolution_13TeVDown')

            if b[i]=='Zll':
                dyptup = DY.Get('TightOS'+di+'/DYptreweightUp/m_t_CollinearMass')
                dyptup.Add(dyfakes, -1)
                dyptup = positivize(dyptup)
                dyptup.SetName(b[i]+'_CMS_DYpTreweight_13TeVUp')
                dyptdown = DY.Get('TightOS'+di+'/DYptreweightDown/m_t_CollinearMass')
                dyptdown.Add(dyfakes, -1)
                dyptdown = positivize(dyptdown)
                dyptdown.SetName(b[i]+'_CMS_DYpTreweight_13TeVDown')

            if b[i]=='TT' or b[i]=='ST':
                dybtagup = DY.Get('TightOS'+di+'/bTagUp/m_t_CollinearMass')
                dybtagup.Add(dyfakes, -1)
                dybtagup = positivize(dybtagup)
                dybtagup.SetName(b[i]+'_CMS_eff_btag_13TeVUp')
                dybtagdown = DY.Get('TightOS'+di+'/bTagDown/m_t_CollinearMass')
                dybtagdown.Add(dyfakes, -1)
                dybtagdown = positivize(dybtagdown)
                dybtagdown.SetName(b[i]+'_CMS_eff_btag_13TeVDown')

            if b[i]=='TT':
                dytptup = DY.Get('TightOS'+di+'/TopptreweightUp/m_t_CollinearMass')
                dytptup.Add(dyfakes, -1)
                dytptup = positivize(dytptup)
                dytptup.SetName(b[i]+'_CMS_ToppTreweight_13TeVUp')
                dytptdown = DY.Get('TightOS'+di+'/TopptreweightDown/m_t_CollinearMass')
                dytptdown.Add(dyfakes, -1)
                dytptdown = positivize(dytptdown)
                dytptdown.SetName(b[i]+'_CMS_ToppTreweight_13TeVDown')

            dymtfakeup = DY.Get('TightOS'+di+'/mtfakeUp/m_t_CollinearMass')
            dymtfakeup.Add(dyfakes, -1)
            dymtfakeup = positivize(dymtfakeup)
            dymtfakeup.SetName(b[i]+'_CMS_scale_mfaketau_13TeVUp')
            dymtfakedown = DY.Get('TightOS'+di+'/mtfakeDown/m_t_CollinearMass')
            dymtfakedown.Add(dyfakes, -1)
            dymtfakedown = positivize(dymtfakedown)
            dymtfakedown.SetName(b[i]+'_CMS_scale_mfaketau_13TeVDown')
            
            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/m_t_CollinearMass')
            dyetfakeup.Add(dyfakes, -1)
            dyetfakeup = positivize(dyetfakeup)
            dyetfakeup.SetName(b[i]+'_CMS_scale_efaketau_13TeVUp')
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/m_t_CollinearMass')
            dyetfakedown.Add(dyfakes, -1)
            dyetfakedown = positivize(dyetfakedown)
            dyetfakedown.SetName(b[i]+'_CMS_scale_efaketau_13TeVDown')
            
            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/m_t_CollinearMass')
            dyetefakeup.Add(dyfakes, -1)
            dyetefakeup = positivize(dyetefakeup)
            dyetefakeup.SetName(b[i]+'_CMS_scale_efaketaues_13TeVUp')
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/m_t_CollinearMass')
            dyetefakedown.Add(dyfakes, -1)
            dyetefakedown = positivize(dyetefakedown)
            dyetefakedown.SetName(b[i]+'_CMS_scale_efaketaues_13TeVDown')

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/m_t_CollinearMass')
            dytes0up.Add(dyfakes, -1)
            dytes0up = positivize(dytes0up)
            dytes0up.SetName(b[i]+'_CMS_scale_t_1prong_13TeVUp')
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/m_t_CollinearMass')
            dytes0down.Add(dyfakes, -1)
            dytes0down = positivize(dytes0down)
            dytes0down.SetName(b[i]+'_CMS_scale_t_1prong_13TeVDown')

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/m_t_CollinearMass')
            dytes1up.Add(dyfakes, -1)
            dytes1up = positivize(dytes1up)
            dytes1up.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp')
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/m_t_CollinearMass')
            dytes1down.Add(dyfakes, -1)
            dytes1down = positivize(dytes1down)
            dytes1down.SetName(b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown')
            
            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/m_t_CollinearMass')
            dytes10up.Add(dyfakes, -1)
            dytes10up = positivize(dytes10up)
            dytes10up.SetName(b[i]+'_CMS_scale_t_3prong_13TeVUp')
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/m_t_CollinearMass')
            dytes10down.Add(dyfakes, -1)
            dytes10down = positivize(dytes10down)
            dytes10down.SetName(b[i]+'_CMS_scale_t_3prong_13TeVDown')
            
            dymesup = DY.Get('TightOS'+di+'/mesUp/m_t_CollinearMass')
            dymesup.Add(dyfakes, -1)
            dymesup = positivize(dymesup)
            dymesup.SetName(b[i]+'_CMS_MES_13TeVUp')
            dymesdown = DY.Get('TightOS'+di+'/mesDown/m_t_CollinearMass')
            dymesdown.Add(dyfakes, -1)
            dymesdown = positivize(dymesdown)
            dymesdown.SetName(b[i]+'_CMS_MES_13TeVDown')

            if b[i]=='EWK' or b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup = DY.Get('TightOS'+di+'/UnclusteredEnUp/m_t_CollinearMass')
                dyuesup.Add(dyfakes, -1)
                dyuesup = positivize(dyuesup)
                dyuesup.SetName(b[i]+'_CMS_MET_Ues_13TeVUp')
                dyuesdown = DY.Get('TightOS'+di+'/UnclusteredEnDown/m_t_CollinearMass')
                dyuesdown.Add(dyfakes, -1)
                dyuesdown = positivize(dyuesdown)
                dyuesdown.SetName(b[i]+'_CMS_MET_Ues_13TeVDown')
        
                dyjetAFMup = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapUp/m_t_CollinearMass')
                dyjetAFMup.Add(dyfakes, -1)
                dyjetAFMup = positivize(dyjetAFMup)
                dyjetAFMup.SetName(b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVUp')
                dyjetAFMdown = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapDown/m_t_CollinearMass')
                dyjetAFMdown.Add(dyfakes, -1)
                dyjetAFMdown = positivize(dyjetAFMdown)
                dyjetAFMdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVDown')
        
                dyjetAMPFBup = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasUp/m_t_CollinearMass')
                dyjetAMPFBup.Add(dyfakes, -1)
                dyjetAMPFBup = positivize(dyjetAMPFBup)
                dyjetAMPFBup.SetName(b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVUp')
                dyjetAMPFBdown = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasDown/m_t_CollinearMass')
                dyjetAMPFBdown.Add(dyfakes, -1)
                dyjetAMPFBdown = positivize(dyjetAMPFBdown)
                dyjetAMPFBdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVDown')
        
                dyjetASup = DY.Get('TightOS'+di+'/JetAbsoluteScaleUp/m_t_CollinearMass')
                dyjetASup.Add(dyfakes, -1)
                dyjetASup = positivize(dyjetASup)
                dyjetASup.SetName(b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVUp')
                dyjetASdown = DY.Get('TightOS'+di+'/JetAbsoluteScaleDown/m_t_CollinearMass')
                dyjetASdown.Add(dyfakes, -1)
                dyjetASdown = positivize(dyjetASdown)
                dyjetASdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVDown')

                dyjetAStup = DY.Get('TightOS'+di+'/JetAbsoluteStatUp/m_t_CollinearMass')
                dyjetAStup.Add(dyfakes, -1)
                dyjetAStup = positivize(dyjetAStup)
                dyjetAStup.SetName(b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVUp')
                dyjetAStdown = DY.Get('TightOS'+di+'/JetAbsoluteStatDown/m_t_CollinearMass')
                dyjetAStdown.Add(dyfakes, -1)
                dyjetAStdown = positivize(dyjetAStdown)
                dyjetAStdown.SetName(b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVDown')
            
                dyjetFQCDup = DY.Get('TightOS'+di+'/JetFlavorQCDUp/m_t_CollinearMass')
                dyjetFQCDup.Add(dyfakes, -1)
                dyjetFQCDup = positivize(dyjetFQCDup)
                dyjetFQCDup.SetName(b[i]+'_CMS_Jes_JetFlavorQCD_13TeVUp')
                dyjetFQCDdown = DY.Get('TightOS'+di+'/JetFlavorQCDDown/m_t_CollinearMass')
                dyjetFQCDdown.Add(dyfakes, -1)
                dyjetFQCDdown = positivize(dyjetFQCDdown)
                dyjetFQCDdown.SetName(b[i]+'_CMS_Jes_JetFlavorQCD_13TeVDown')

                dyjetFup = DY.Get('TightOS'+di+'/JetFragmentationUp/m_t_CollinearMass')
                dyjetFup.Add(dyfakes, -1)
                dyjetFup = positivize(dyjetFup)
                dyjetFup.SetName(b[i]+'_CMS_Jes_JetFragmentation_13TeVUp')
                dyjetFdown = DY.Get('TightOS'+di+'/JetFragmentationDown/m_t_CollinearMass')
                dyjetFdown.Add(dyfakes, -1)
                dyjetFdown = positivize(dyjetFdown)
                dyjetFdown.SetName(b[i]+'_CMS_Jes_JetFragmentation_13TeVDown')

                dyjetPUDMCup = DY.Get('TightOS'+di+'/JetPileUpDataMCUp/m_t_CollinearMass')
                dyjetPUDMCup.Add(dyfakes, -1)
                dyjetPUDMCup = positivize(dyjetPUDMCup)
                dyjetPUDMCup.SetName(b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVUp')
                dyjetPUDMCdown = DY.Get('TightOS'+di+'/JetPileUpDataMCDown/m_t_CollinearMass')
                dyjetPUDMCdown.Add(dyfakes, -1)
                dyjetPUDMCdown = positivize(dyjetPUDMCdown)
                dyjetPUDMCdown.SetName(b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVDown')

                dyjetPUPBBup = DY.Get('TightOS'+di+'/JetPileUpPtBBUp/m_t_CollinearMass')
                dyjetPUPBBup.Add(dyfakes, -1)
                dyjetPUPBBup = positivize(dyjetPUPBBup)
                dyjetPUPBBup.SetName(b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVUp')
                dyjetPUPBBdown = DY.Get('TightOS'+di+'/JetPileUpPtBBDown/m_t_CollinearMass')
                dyjetPUPBBdown.Add(dyfakes, -1)
                dyjetPUPBBdown = positivize(dyjetPUPBBdown)
                dyjetPUPBBdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVDown')
                
                dyjetPUPEC1up = DY.Get('TightOS'+di+'/JetPileUpPtEC1Up/m_t_CollinearMass')
                dyjetPUPEC1up.Add(dyfakes, -1)
                dyjetPUPEC1up = positivize(dyjetPUPEC1up)
                dyjetPUPEC1up.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVUp')
                dyjetPUPEC1down = DY.Get('TightOS'+di+'/JetPileUpPtEC1Down/m_t_CollinearMass')
                dyjetPUPEC1down.Add(dyfakes, -1)
                dyjetPUPEC1down = positivize(dyjetPUPEC1down)
                dyjetPUPEC1down.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVDown')

                dyjetPUPEC2up = DY.Get('TightOS'+di+'/JetPileUpPtEC2Up/m_t_CollinearMass')
                dyjetPUPEC2up.Add(dyfakes, -1)
                dyjetPUPEC2up = positivize(dyjetPUPEC2up)
                dyjetPUPEC2up.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVUp')
                dyjetPUPEC2down = DY.Get('TightOS'+di+'/JetPileUpPtEC2Down/m_t_CollinearMass')
                dyjetPUPEC2down.Add(dyfakes, -1)
                dyjetPUPEC2down = positivize(dyjetPUPEC2down)
                dyjetPUPEC2down.SetName(b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVDown')

                dyjetPUPHFup = DY.Get('TightOS'+di+'/JetPileUpPtHFUp/m_t_CollinearMass')
                dyjetPUPHFup.Add(dyfakes, -1)
                dyjetPUPHFup = positivize(dyjetPUPHFup)
                dyjetPUPHFup.SetName(b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVUp')
                dyjetPUPHFdown = DY.Get('TightOS'+di+'/JetPileUpPtHFDown/m_t_CollinearMass')
                dyjetPUPHFdown.Add(dyfakes, -1)
                dyjetPUPHFdown = positivize(dyjetPUPHFdown)
                dyjetPUPHFdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVDown')
        
                dyjetPUPRup = DY.Get('TightOS'+di+'/JetPileUpPtRefUp/m_t_CollinearMass')
                dyjetPUPRup.Add(dyfakes, -1)
                dyjetPUPRup = positivize(dyjetPUPRup)
                dyjetPUPRup.SetName(b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVUp')
                dyjetPUPRdown = DY.Get('TightOS'+di+'/JetPileUpPtRefDown/m_t_CollinearMass')
                dyjetPUPRdown.Add(dyfakes, -1)
                dyjetPUPRdown = positivize(dyjetPUPRdown)
                dyjetPUPRdown.SetName(b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVDown')
        
                dyjetRFSRup = DY.Get('TightOS'+di+'/JetRelativeFSRUp/m_t_CollinearMass')
                dyjetRFSRup.Add(dyfakes, -1)
                dyjetRFSRup = positivize(dyjetRFSRup)
                dyjetRFSRup.SetName(b[i]+'_CMS_Jes_JetRelativeFSR_13TeVUp')
                dyjetRFSRdown = DY.Get('TightOS'+di+'/JetRelativeFSRDown/m_t_CollinearMass')
                dyjetRFSRdown.Add(dyfakes, -1)
                dyjetRFSRdown = positivize(dyjetRFSRdown)
                dyjetRFSRdown.SetName(b[i]+'_CMS_Jes_JetRelativeFSR_13TeVDown')
        
                dyjetRJEREC1up = DY.Get('TightOS'+di+'/JetRelativeJEREC1Up/m_t_CollinearMass')
                dyjetRJEREC1up.Add(dyfakes, -1)
                dyjetRJEREC1up = positivize(dyjetRJEREC1up)
                dyjetRJEREC1up.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVUp')
                dyjetRJEREC1down = DY.Get('TightOS'+di+'/JetRelativeJEREC1Down/m_t_CollinearMass')
                dyjetRJEREC1down.Add(dyfakes, -1)
                dyjetRJEREC1down = positivize(dyjetRJEREC1down)
                dyjetRJEREC1down.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVDown')
        
                dyjetRJEREC2up = DY.Get('TightOS'+di+'/JetRelativeJEREC2Up/m_t_CollinearMass')
                dyjetRJEREC2up.Add(dyfakes, -1)
                dyjetRJEREC2up = positivize(dyjetRJEREC2up)
                dyjetRJEREC2up.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVUp')
                dyjetRJEREC2down = DY.Get('TightOS'+di+'/JetRelativeJEREC2Down/m_t_CollinearMass')
                dyjetRJEREC2down.Add(dyfakes, -1)
                dyjetRJEREC2down = positivize(dyjetRJEREC2down)
                dyjetRJEREC2down.SetName(b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVDown')

                dyjetRJERHFup = DY.Get('TightOS'+di+'/JetRelativeJERHFUp/m_t_CollinearMass')
                dyjetRJERHFup.Add(dyfakes, -1)
                dyjetRJERHFup = positivize(dyjetRJERHFup)
                dyjetRJERHFup.SetName(b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVUp')
                dyjetRJERHFdown = DY.Get('TightOS'+di+'/JetRelativeJERHFDown/m_t_CollinearMass')
                dyjetRJERHFdown.Add(dyfakes, -1)
                dyjetRJERHFdown = positivize(dyjetRJERHFdown)
                dyjetRJERHFdown.SetName(b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVDown')
        
                dyjetRPBBup = DY.Get('TightOS'+di+'/JetRelativePtBBUp/m_t_CollinearMass')
                dyjetRPBBup.Add(dyfakes, -1)
                dyjetRPBBup = positivize(dyjetRPBBup)
                dyjetRPBBup.SetName(b[i]+'_CMS_Jes_JetRelativePtBB_13TeVUp')
                dyjetRPBBdown = DY.Get('TightOS'+di+'/JetRelativePtBBDown/m_t_CollinearMass')
                dyjetRPBBdown.Add(dyfakes, -1)
                dyjetRPBBdown = positivize(dyjetRPBBdown)
                dyjetRPBBdown.SetName(b[i]+'_CMS_Jes_JetRelativePtBB_13TeVDown')

                dyjetRPEC1up = DY.Get('TightOS'+di+'/JetRelativePtEC1Up/m_t_CollinearMass')
                dyjetRPEC1up.Add(dyfakes, -1)
                dyjetRPEC1up = positivize(dyjetRPEC1up)
                dyjetRPEC1up.SetName(b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVUp')
                dyjetRPEC1down = DY.Get('TightOS'+di+'/JetRelativePtEC1Down/m_t_CollinearMass')
                dyjetRPEC1down.Add(dyfakes, -1)
                dyjetRPEC1down = positivize(dyjetRPEC1down)
                dyjetRPEC1down.SetName(b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVDown')
                
                dyjetRPEC2up = DY.Get('TightOS'+di+'/JetRelativePtEC2Up/m_t_CollinearMass')
                dyjetRPEC2up.Add(dyfakes, -1)
                dyjetRPEC2up = positivize(dyjetRPEC2up)
                dyjetRPEC2up.SetName(b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVUp')
                dyjetRPEC2down = DY.Get('TightOS'+di+'/JetRelativePtEC2Down/m_t_CollinearMass')
                dyjetRPEC2down.Add(dyfakes, -1)
                dyjetRPEC2down = positivize(dyjetRPEC2down)
                dyjetRPEC2down.SetName(b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVDown')

                dyjetRPHFup = DY.Get('TightOS'+di+'/JetRelativePtHFUp/m_t_CollinearMass')
                dyjetRPHFup.Add(dyfakes, -1)
                dyjetRPHFup = positivize(dyjetRPHFup)
                dyjetRPHFup.SetName(b[i]+'_CMS_Jes_JetRelativePtHF_13TeVUp')
                dyjetRPHFdown = DY.Get('TightOS'+di+'/JetRelativePtHFDown/m_t_CollinearMass')
                dyjetRPHFdown.Add(dyfakes, -1)
                dyjetRPHFdown = positivize(dyjetRPHFdown)
                dyjetRPHFdown.SetName(b[i]+'_CMS_Jes_JetRelativePtHF_13TeVDown')
        
                dyjetRSECup = DY.Get('TightOS'+di+'/JetRelativeStatECUp/m_t_CollinearMass')
                dyjetRSECup.Add(dyfakes, -1)
                dyjetRSECup = positivize(dyjetRSECup)
                dyjetRSECup.SetName(b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVUp')
                dyjetRSECdown = DY.Get('TightOS'+di+'/JetRelativeStatECDown/m_t_CollinearMass')
                dyjetRSECdown.Add(dyfakes, -1)
                dyjetRSECdown = positivize(dyjetRSECdown)
                dyjetRSECdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVDown')
        
                dyjetRSFSRup = DY.Get('TightOS'+di+'/JetRelativeStatFSRUp/m_t_CollinearMass')
                dyjetRSFSRup.Add(dyfakes, -1)
                dyjetRSFSRup = positivize(dyjetRSFSRup)
                dyjetRSFSRup.SetName(b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVUp')
                dyjetRSFSRdown = DY.Get('TightOS'+di+'/JetRelativeStatFSRDown/m_t_CollinearMass')
                dyjetRSFSRdown.Add(dyfakes, -1)
                dyjetRSFSRdown = positivize(dyjetRSFSRdown)
                dyjetRSFSRdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVDown')
        
                dyjetRSHFup = DY.Get('TightOS'+di+'/JetRelativeStatHFUp/m_t_CollinearMass')
                dyjetRSHFup.Add(dyfakes, -1)
                dyjetRSHFup = positivize(dyjetRSHFup)
                dyjetRSHFup.SetName(b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVUp')
                dyjetRSHFdown = DY.Get('TightOS'+di+'/JetRelativeStatHFDown/m_t_CollinearMass')
                dyjetRSHFdown.Add(dyfakes, -1)
                dyjetRSHFdown = positivize(dyjetRSHFdown)
                dyjetRSHFdown.SetName(b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVDown')

                dyjetSPEup = DY.Get('TightOS'+di+'/JetSinglePionECALUp/m_t_CollinearMass')
                dyjetSPEup.Add(dyfakes, -1)
                dyjetSPEup = positivize(dyjetSPEup)
                dyjetSPEup.SetName(b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVUp')
                dyjetSPEdown = DY.Get('TightOS'+di+'/JetSinglePionECALDown/m_t_CollinearMass')
                dyjetSPEdown.Add(dyfakes, -1)
                dyjetSPEdown = positivize(dyjetSPEdown)
                dyjetSPEdown.SetName(b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVDown')
                
                dyjetSPHup = DY.Get('TightOS'+di+'/JetSinglePionHCALUp/m_t_CollinearMass')
                dyjetSPHup.Add(dyfakes, -1)
                dyjetSPHup = positivize(dyjetSPHup)
                dyjetSPHup.SetName(b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVUp')
                dyjetSPHdown = DY.Get('TightOS'+di+'/JetSinglePionHCALDown/m_t_CollinearMass')
                dyjetSPHdown.Add(dyfakes, -1)
                dyjetSPHdown = positivize(dyjetSPHdown)
                dyjetSPHdown.SetName(b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVDown')
        
                dyjetTPEup = DY.Get('TightOS'+di+'/JetTimePtEtaUp/m_t_CollinearMass')
                dyjetTPEup.Add(dyfakes, -1)
                dyjetTPEup = positivize(dyjetTPEup)
                dyjetTPEup.SetName(b[i]+'_CMS_Jes_JetTimePtEta_13TeVUp')
                dyjetTPEdown = DY.Get('TightOS'+di+'/JetTimePtEtaDown/m_t_CollinearMass')
                dyjetTPEdown.Add(dyfakes, -1)
                dyjetTPEdown = positivize(dyjetTPEdown)
                dyjetTPEdown.SetName(b[i]+'_CMS_Jes_JetTimePtEta_13TeVDown')
                
                dyjetRBup = DY.Get('TightOS'+di+'/JetRelativeBalUp/m_t_CollinearMass')
                dyjetRBup.Add(dyfakes, -1)
                dyjetRBup = positivize(dyjetRBup)
                dyjetRBup.SetName(b[i]+'_CMS_Jes_JetRelativeBal_13TeVUp')
                dyjetRBdown = DY.Get('TightOS'+di+'/JetRelativeBalDown/m_t_CollinearMass')
                dyjetRBdown.Add(dyfakes, -1)
                dyjetRBdown = positivize(dyjetRBdown)
                dyjetRBdown.SetName(b[i]+'_CMS_Jes_JetRelativeBal_13TeVDown')
        
                dyjetRSup = DY.Get('TightOS'+di+'/JetRelativeSampleUp/m_t_CollinearMass')
                dyjetRSup.Add(dyfakes, -1)
                dyjetRSup = positivize(dyjetRSup)
                dyjetRSup.SetName(b[i]+'_CMS_Jes_JetRelativeSample_13TeVUp')
                dyjetRSdown = DY.Get('TightOS'+di+'/JetRelativeSampleDown/m_t_CollinearMass')
                dyjetRSdown.Add(dyfakes, -1)
                dyjetRSdown = positivize(dyjetRSdown)
                dyjetRSdown.SetName(b[i]+'_CMS_Jes_JetRelativeSample_13TeVDown')

            dyall = DY.Get('TightOS'+di+'/m_t_CollinearMass')
            dytfakesup = DY.Get('TauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass') 
            dytfakesdown = DY.Get('TauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
            dymfakesup = DY.Get('MuonLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
            dymfakesdown = DY.Get('MuonLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
            dymttfakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeUp/m_t_CollinearMass')
            dymttfakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeDown/m_t_CollinearMass')
            dymtmfakesup = DY.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/m_t_CollinearMass')
            dymtmfakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/m_t_CollinearMass')
            dy1 = dyall.Clone()
            dy1t = dytfakesup.Clone()
            dy1t.add(dymfakes)
            dy1t.add(dymttfakesup, -1)
            dy1t = positivize(dy1t)
            dy1.add(dy1t, -1)
            dy1 = positivize(dy1)
            dy1.SetName(b[i]+'_CMS_TauFakeRate_13TeVUp')
            dy2 = dyall.Clone()
            dy2t = dytfakesdown.Clone()
            dy2t.add(dymfakes)
            dy2t.add(dymttfakesdown, -1)
            dy2t = positivize(dy2t)
            dy2.add(dy2t, -1)
            dy2 = positivize(dy2)
            dy2.SetName(b[i]+'_CMS_TauFakeRate_13TeVDown')
            dy3 = dyall.Clone()
            dy3t = dytfakes.Clone()
            dy3t.add(dymfakesup)
            dy3t.add(dymtmfakesup, -1)
            dy3t = positivize(dy3t)
            dy3.add(dy3t, -1)
            dy3 = positivize(dy3)
            dy3.SetName(b[i]+'_CMS_MuonFakeRate_13TeVUp')
            dy4 = dyall.Clone()
            dy4t = dytfakes.Clone()
            dy4t.add(dymfakesdown)
            dy4t.add(dymtmfakesdown, -1)
            dy4t = positivize(dy4t)
            dy4.add(dy4t, -1)
            dy4 = positivize(dy4)
            dy4.SetName(b[i]+'_CMS_MuonFakeRate_13TeVDown')
            dyall.Delete()
            dy1t.Delete()
            dy2t.Delete()
            dy3t.Delete()
            dy4t.Delete()
            dyfakes.Delete()
            dytfakes.Delete()
            dymfakes.Delete()
            dymtfakes.Delete()
            dytfakesup.Delete()
            dytfakesdown.Delete()
            dymfakesup.Delete()
            dymfakesdown.Delete()
            dymttfakesup.Delete()
            dymttfakesdown.Delete()
            dymtmfakesup.Delete()
            dymtmfakesdown.Delete()

        f.Write()
        if i==0:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1.Delete()
            f2.Delete()
            f3.Delete()
            f4.Delete()
            emb1.Delete()
            emb2.Delete()
            emb3.Delete()
            emb4.Delete()
            embtrkup.Delete()
            embtrkdown.Delete()
            embtes0up.Delete()
            embtes0down.Delete()
            embtes1up.Delete()
            embtes1down.Delete()
            embtes10up.Delete()
            embtes10down.Delete()
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            dyrecrespup.Delete()                                                                                                                                                                                                                                               
            dyrecrespdown.Delete()                                                                                                                                                                                                                                             
            dyrecresoup.Delete()                                                                                                                                                                                                                                               
            dyrecresodown.Delete()                                                                                                                                                                                                                                             
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dymesup.Delete()
            dymesdown.Delete()
        else:
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH':
                dyrecrespup.Delete()
                dyrecrespdown.Delete()
                dyrecresoup.Delete()
                dyrecresodown.Delete()
            if b[i]=='Zll':
                dyptup.Delete()
                dyptdown.Delete()
            if b[i]=='TT' or b[i]=='ST':
                dybtagup.Delete()
                dybtagdown.Delete()
            if b[i]=='TT':
                dytptup.Delete()
                dytptdown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dymesup.Delete()
            dymesdown.Delete()
            if b[i]=='EWK' or b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup.Delete()
                dyuesdown.Delete()
                dyjetAFMup.Delete()
                dyjetAFMdown.Delete()
                dyjetAMPFBup.Delete()
                dyjetAMPFBdown.Delete()
                dyjetASup.Delete()
                dyjetASdown.Delete()
                dyjetAStup.Delete()
                dyjetAStdown.Delete()
                dyjetFQCDup.Delete()
                dyjetFQCDdown.Delete()
                dyjetFup.Delete()
                dyjetFdown.Delete()
                dyjetPUDMCup.Delete()
                dyjetPUDMCdown.Delete()
                dyjetPUPBBup.Delete()
                dyjetPUPBBdown.Delete()
                dyjetPUPEC1up.Delete()
                dyjetPUPEC1down.Delete()
                dyjetPUPEC2up.Delete()
                dyjetPUPEC2down.Delete()
                dyjetPUPHFup.Delete()
                dyjetPUPHFdown.Delete()
                dyjetPUPRup.Delete()
                dyjetPUPRdown.Delete()
                dyjetRFSRup.Delete()
                dyjetRFSRdown.Delete()
                dyjetRJEREC1up.Delete()
                dyjetRJEREC1down.Delete()
                dyjetRJEREC2up.Delete()
                dyjetRJEREC2down.Delete()
                dyjetRJERHFup.Delete()
                dyjetRJERHFdown.Delete()
                dyjetRPBBup.Delete()
                dyjetRPBBdown.Delete()
                dyjetRPEC1up.Delete()
                dyjetRPEC1down.Delete()
                dyjetRPEC2up.Delete()
                dyjetRPEC2down.Delete()
                dyjetRPHFup.Delete()
                dyjetRPHFdown.Delete()
                dyjetRSECup.Delete()
                dyjetRSECdown.Delete()
                dyjetRSFSRup.Delete()
                dyjetRSFSRdown.Delete()
                dyjetRSHFup.Delete()
                dyjetRSHFdown.Delete()
                dyjetSPEup.Delete()
                dyjetSPEdown.Delete()
                dyjetSPHup.Delete()
                dyjetSPHdown.Delete()
                dyjetTPEup.Delete()
                dyjetTPEdown.Delete()
                dyjetRBup.Delete()
                dyjetRBdown.Delete()
                dyjetRSup.Delete()
                dyjetRSdown.Delete()
            dy1.Delete()
            dy2.Delete()
            dy3.Delete()
            dy4.Delete()
