import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'mt'
period = '13TeV'
sqrts = 13

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('results/%s/AnalyzeMuTauSys/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = 'plots/%s/AnalyzeMuTauSys/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'shapes.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') , mc_samples )]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x :  x.startswith('DYJetsToLL_M-10to50') , mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x :  x.startswith('EWK') , mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : 'HToTauTau' in x , mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]), views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : 'VBF_LFV_HToMuTau' or 'GluGlu_LFV_HToMuTau' in x , mc_samples)])]

b = ['Zll', 'ZllLowMass', 'EWK', 'SMH', 'TT', 'ST', 'EWKDiboson', 'LFV125']

for di in dirs:
    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    DataAll = views.SubdirectoryView(DataTotal, 'TightOS'+di)
    data = DataAll.Get("m_t_CollinearMass")
    data.SetName('data_obs')
    embedtotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    embedall = views.SubdirectoryView(embedtotal, 'TightOS'+di)
    embedtfakes = views.SubdirectoryView(embedtotal, 'TauLooseOS'+di)
    embedmfakes = views.SubdirectoryView(embedtotal, 'MuonLooseOS'+di)
    embedmtfakes = views.SubdirectoryView(embedtotal, 'MuonLooseTauLooseOS'+di)
    embedmt = views.SumView(embedtfakes, embedmfakes)
    embedfakes = SubtractionView(embedmt, embedmtfakes, restrict_positive=True)
    embed = SubtractionView(embedall, embedfakes, restrict_positive=True)
    emb = embed.Get("m_t_CollinearMass")
    emb.SetName('embed')
    embmfakes = embedmfakes.Get("m_t_CollinearMass")
    embtfakes = embedtfakes.Get("m_t_CollinearMass")
    embmtfakes = embedmtfakes.Get("m_t_CollinearMass")
    embtfakesup = embedtfakes.Get("TauFakeUp/m_t_CollinearMass")
    embtfakesdown = embedtfakes.Get("TauFakeDown/m_t_CollinearMass")
    embmfakesup = embedmfakes.Get("MuonFakeUp/m_t_CollinearMass")
    embmfakesdown = embedmfakes.Get("MuonFakeDown/m_t_CollinearMass")
    embmttfakesup = embedmtfakes.Get("TauFakeUp/m_t_CollinearMass")
    embmttfakesdown = embedmtfakes.Get("TauFakeDown/m_t_CollinearMass")
    embmtmfakesup = embedmtfakes.Get("MuonFakeUp/m_t_CollinearMass")
    embmtmfakesdown = embedmtfakes.Get("MuonFakeDown/m_t_CollinearMass")
    emball = embedall.Get("m_t_CollinearMass")
    e1 = emball.Clone()
    e1.add(embtfakesup, -1)
    e1.add(embmfakes, -1)
    e1.add(embmttfakesup)
    e1.SetName("embed_TauFakesUp")
    e2 = emball.Clone()
    e2.add(embtfakesdown, -1)
    e2.add(embmfakes, -1)
    e2.add(embmttfakesdown)
    e2.SetName("embed_TauFakesDown")
    e3 = emball.Clone()
    e3.add(embtfakes, -1)
    e3.add(embmfakesup, -1)
    e3.add(embmtmfakesup)
    e3.SetName("embed_MuonFakesUp")
    e4 = emball.Clone()
    e4.add(embtfakes, -1)
    e4.add(embmfakesdown, -1)
    e4.add(embmtmfakesdown)
    e4.SetName("embed_MuonFakesDown")
    emball.Delete()
    embtfakes.Delete()
    embmfakes.Delete()
    embmtfakes.Delete()
    embtfakesup.Delete()
    embtfakesdown.Delete()
    embmfakesup.Delete()
    embmfakesdown.Delete()
    embmttfakesup.Delete()
    embmttfakesdown.Delete()
    embmtmfakesup.Delete()
    embmtmfakesdown.Delete()
    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    fakesTau = views.SubdirectoryView(QCD, 'TauLooseOS'+di)
    fakesMuon = views.SubdirectoryView(QCD, 'MuonLooseOS'+di)
    fakesTauMuon = views.SubdirectoryView(QCD, 'MuonLooseTauLooseOS'+di)
    fakesMT = views.SumView(fakesTau, fakesMuon)
    QCD = SubtractionView(fakesMT, fakesTauMuon, restrict_positive=True)
    qcd = QCD.Get("m_t_CollinearMass")
    qcd.SetName('Fakes')
    mfakes = fakesMuon.Get("m_t_CollinearMass")
    tfakes = fakesTau.Get("m_t_CollinearMass")
    mtfakes = fakesTauMuon.Get("m_t_CollinearMass")
    tfakesup = fakesTau.Get("TauFakeUp/m_t_CollinearMass")
    tfakesdown = fakesTau.Get("TauFakeDown/m_t_CollinearMass")
    mfakesup = fakesMuon.Get("MuonFakeUp/m_t_CollinearMass")
    mfakesdown = fakesMuon.Get("MuonFakeDown/m_t_CollinearMass")
    mttfakesup = fakesTauMuon.Get("TauFakeUp/m_t_CollinearMass")
    mttfakesdown = fakesTauMuon.Get("TauFakeDown/m_t_CollinearMass")
    mtmfakesup = fakesTauMuon.Get("MuonFakeUp/m_t_CollinearMass")
    mtmfakesdown = fakesTauMuon.Get("MuonFakeDown/m_t_CollinearMass")
    f1 = tfakesup.Clone()
    f1.add(mfakes)
    f1.add(mttfakesup, -1)
    f1.SetName("Fakes_TauFakesUp")
    f2 = tfakesdown.Clone()
    f2.add(mfakes)
    f2.add(mttfakesdown, -1)
    f2.SetName("Fakes_TauFakesDown")
    f3 = tfakes.Clone()
    f3.add(mfakesup)
    f3.add(mtmfakesup, -1)
    f3.SetName("Fakes_MuonFakesUp")
    f4 = tfakes.Clone()
    f4.add(mfakesdown)
    f4.add(mtmfakesdown, -1)
    f4.SetName("Fakes_MuonFakesDown")
    tfakes.Delete()
    mfakes.Delete()
    mtfakes.Delete()
    tfakesup.Delete()
    tfakesdown.Delete()
    mfakesup.Delete()
    mfakesdown.Delete()
    mttfakesup.Delete()
    mttfakesdown.Delete()
    mtmfakesup.Delete()
    mtmfakesdown.Delete()
    for i in range(8):
        DYtotal = v[i]
        DYall = views.SubdirectoryView(DYtotal, 'TightOS'+di)
        DYtfakes = views.SubdirectoryView(DYtotal, 'TauLooseOS'+di)
        DYmfakes = views.SubdirectoryView(DYtotal, 'MuonLooseOS'+di)
        DYmtfakes = views.SubdirectoryView(DYtotal, 'MuonLooseTauLooseOS'+di)
        DYmt = views.SumView(DYtfakes, DYmfakes)
        DYfakes = SubtractionView(DYmt, DYmtfakes, restrict_positive=True)
        DY = SubtractionView(DYall, DYfakes, restrict_positive=True)
        dy = DY.Get("m_t_CollinearMass")
        dy.SetName(b[i])
        dypuup = DY.Get("puUp/m_t_CollinearMass")
        dypuup.SetName(b[i]+"_PU_UncertaintyUp")
        dypudown = DY.Get("puDown/m_t_CollinearMass")
        dypudown.SetName(b[i]+"_PU_UncertaintyDown")
        dytrup = DY.Get("trUp/m_t_CollinearMass")
        dytrup.SetName(b[i]+"_Trigger_UncertaintyUp")
        dytrdown = DY.Get("trDown/m_t_CollinearMass")
        dytrdown.SetName(b[i]+"_Trigger_UncertaintyDown")
        dytes0up = DY.Get("scaletDM0Up/m_t_CollinearMass")
        dytes0up.SetName(b[i]+"_TESDM0Up")
        dytes0down = DY.Get("scaletDM0Down/m_t_CollinearMass")
        dytes0down.SetName(b[i]+"_TESDM0Down")
        dytes1up = DY.Get("scaletDM1Up/m_t_CollinearMass")
        dytes1up.SetName(b[i]+"_TESDM1Up")
        dytes1down = DY.Get("scaletDM1Down/m_t_CollinearMass")
        dytes1down.SetName(b[i]+"_TESDM1Down")
        dytes10up = DY.Get("scaletDM10Up/m_t_CollinearMass")
        dytes10up.SetName(b[i]+"_TESDM10Up")
        dytes10down = DY.Get("scaletDM10Down/m_t_CollinearMass")
        dytes10down.SetName(b[i]+"_TESDM10Down")
        dymesup = DY.Get("mesUp/m_t_CollinearMass")
        dymesup.SetName(b[i]+"_MESUp")
        dymesdown = DY.Get("mesDown/m_t_CollinearMass")
        dymesdown.SetName(b[i]+"_MESDown")
        dyuesup = DY.Get("UnclusteredEnUp/m_t_CollinearMass")
        dyuesup.SetName(b[i]+"_UnclusteredEnUp")
        dyuesdown = DY.Get("UnclusteredEnDown/m_t_CollinearMass")
        dyuesdown.SetName(b[i]+"_UnclusteredEnDown")
        dyjetenup = DY.Get("JetEnUp/m_t_CollinearMass")
        dyjetenup.SetName(b[i]+"_JetEnUp")
        dyjetendown = DY.Get("JetEnDown/m_t_CollinearMass")
        dyjetendown.SetName(b[i]+"_JetEnDown")
        dyjetresup = DY.Get("JetResUp/m_t_CollinearMass")
        dyjetresup.SetName(b[i]+"_JetResUp")
        dyjetresdown = DY.Get("JetResDown/m_t_CollinearMass")
        dyjetresdown.SetName(b[i]+"_JetResDown")
        dyall = DYall.Get("m_t_CollinearMass")
        dytfakes = DYmfakes.Get("m_t_CollinearMass")
        dymfakes = DYtfakes.Get("m_t_CollinearMass")
        dymtfakes = DYmtfakes.Get("m_t_CollinearMass")
        dytfakesup = DYtfakes.Get("TauFakeUp/m_t_CollinearMass") 
        dytfakesdown = DYtfakes.Get("TauFakeDown/m_t_CollinearMass")
        dymfakesup = DYmfakes.Get("MuonFakeUp/m_t_CollinearMass")
        dymfakesdown = DYmfakes.Get("MuonFakeDown/m_t_CollinearMass")
        dymttfakesup = DYmtfakes.Get("TauFakeUp/m_t_CollinearMass")
        dymttfakesdown = DYmtfakes.Get("TauFakeDown/m_t_CollinearMass")
        dymtmfakesup = DYmtfakes.Get("MuonFakeUp/m_t_CollinearMass")
        dymtmfakesdown = DYmtfakes.Get("MuonFakeDown/m_t_CollinearMass")
        dy1 = dyall.Clone()
        dy1.add(dytfakesup, -1)
        dy1.add(dymfakes, -1)
        dy1.add(dymttfakesup)
        dy1.SetName(b[i]+"_TauFakesUp")
        dy2 = dyall.Clone()
        dy2.add(dytfakesdown, -1)
        dy2.add(dymfakes, -1)
        dy2.add(dymttfakesdown)
        dy2.SetName(b[i]+"_TauFakesDown")
        dy3 = dyall.Clone()
        dy3.add(dytfakes, -1)
        dy3.add(dymfakesup, -1)
        dy3.add(dymtmfakesup)
        dy3.SetName(b[i]+"_MuonFakesUp")
        dy4 = dyall.Clone()
        dy4.add(dytfakes, -1)
        dy4.add(dymfakesdown, -1)
        dy4.add(dymtmfakesdown)
        dy4.SetName(b[i]+"_MuonFakesDown")
        dyall.Delete()
        dytfakes.Delete()
        dymfakes.Delete()
        dymtfakes.Delete()
        dytfakesup.Delete()
        dytfakesdown.Delete()
        dymfakesup.Delete()
        dymfakesdown.Delete()
        dymttfakesup.Delete()
        dymttfakesdown.Delete()
        dymtmfakesup.Delete()
        dymtmfakesdown.Delete()
        if i==1:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1.Delete()
            f2.Delete()
            f3.Delete()
            f4.Delete()
            e1.Delete()
            e2.Delete()
            e3.Delete()
            e4.Delete()
        f.Write()
