import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'mt'
period = '13TeV'
sqrts = 13

def positivize(histogram):
    output = histogram.Clone()
    for i in range(output.GetSize()):
        if output.GetArray()[i] < 0:
            output.AddAt(0, i)
    return output

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('results/%s/AnalyzeMuTauSysNN/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = 'plots/%s/AnalyzeMuTauSysNN/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'shapesMuTauNN.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') or x.startswith('DYJetsToLL_M-10to50'), mc_samples )]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('EWK') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGluHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBFHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('WminusHToTauTau') or x.startswith('WplusHToTauTau') or x.startswith('ZHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ttHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGlu_LFV') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBF_LFV') , mc_samples)])
]

b = ['Zll', 'EWK', 'GluGluH', 'VBFH', 'VH', 'ttH', 'TT', 'ST', 'EWKDiboson', 'GluGlu125', 'VBF125']

for di in dirs:
    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    DataAll = views.SubdirectoryView(DataTotal, 'TightOS'+di)
    data = DataAll.Get("sigDiscriminator")
    data.SetName('data_obs')

    embedtotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    embedall = views.SubdirectoryView(embedtotal, 'TightOS'+di)
    embedmfakes = views.SubdirectoryView(embedtotal, 'MuonLooseOS'+di)
    embed = SubtractionView(embedall, embedmfakes, restrict_positive=True)
    emb = embed.Get("sigDiscriminator")
    emb.SetName('embed')

    embtrup = embed.Get("trUp/sigDiscriminator")
    embtrup.SetName("embed_Trigger_UncertaintyUp")
    embtrdown = embed.Get("trDown/sigDiscriminator")
    embtrdown.SetName("embed_Trigger_UncertaintyDown")

    embseltrup = embed.Get("embtrUp/sigDiscriminator")
    embseltrup.SetName("embed_SelectionTrigger_UncertaintyUp")
    embseltrdown = embed.Get("embtrDown/sigDiscriminator")
    embseltrdown.SetName("embed_SelectionTrigger_UncertaintyDown")

    embtrkup = embed.Get("embtrkUp/sigDiscriminator")
    embtrkup.SetName("embed_TauTracking_UncertaintyUp")
    embtrkdown = embed.Get("embtrkDown/sigDiscriminator")
    embtrkdown.SetName("embed_TauTracking_UncertaintyDown")

    embtes0up = embed.Get("scaletDM0Up/sigDiscriminator")
    embtes0up.SetName("embed_TESDM0Up")
    embtes0down = embed.Get("scaletDM0Down/sigDiscriminator")
    embtes0down.SetName("embed_TESDM0Down")
    embtes1up = embed.Get("scaletDM1Up/sigDiscriminator")
    embtes1up.SetName("embed_TESDM1Up")
    embtes1down = embed.Get("scaletDM1Down/sigDiscriminator")
    embtes1down.SetName("embed_TESDM1Down")
    embtes10up = embed.Get("scaletDM10Up/sigDiscriminator")
    embtes10up.SetName("embed_TESDM10Up")
    embtes10down = embed.Get("scaletDM10Down/sigDiscriminator")
    embtes10down.SetName("embed_TESDM10Down")
    
    embmfakesup = embedmfakes.Get("MuonFakeUp/sigDiscriminator")
    embmfakesdown = embedmfakes.Get("MuonFakeDown/sigDiscriminator")
    emball = embedall.Get("sigDiscriminator")
    e1 = emball.Clone()
    e1.add(embmfakesup, -1)
    e1 = positivize(e1)
    e1.SetName("embed_MuonFakesUp")
    e2 = emball.Clone()
    e2.add(embmfakesdown, -1)
    e2 = positivize(e2)
    e2.SetName("embed_MuonFakesDown")
    emball.Delete()
    embmfakesup.Delete()
    embmfakesdown.Delete()

    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    fakesTau = views.SubdirectoryView(QCD, 'TauLooseOS'+di)
    fakesMuon = views.SubdirectoryView(QCD, 'MuonLooseOS'+di)
    fakesTauMuon = views.SubdirectoryView(QCD, 'MuonLooseTauLooseOS'+di)
    fakesMT = views.SumView(fakesTau, fakesMuon)
    QCD = SubtractionView(fakesMT, fakesTauMuon, restrict_positive=True)
    qcd = QCD.Get("sigDiscriminator")
    qcd.SetName('Fakes')
    mfakes = fakesMuon.Get("sigDiscriminator")
    tfakes = fakesTau.Get("sigDiscriminator")
    mtfakes = fakesTauMuon.Get("sigDiscriminator")
    tfakesup = fakesTau.Get("TauFakeUp/sigDiscriminator")
    tfakesdown = fakesTau.Get("TauFakeDown/sigDiscriminator")
    mfakesup = fakesMuon.Get("MuonFakeUp/sigDiscriminator")
    mfakesdown = fakesMuon.Get("MuonFakeDown/sigDiscriminator")
    mttfakesup = fakesTauMuon.Get("TauFakeUp/sigDiscriminator")
    mttfakesdown = fakesTauMuon.Get("TauFakeDown/sigDiscriminator")
    mtmfakesup = fakesTauMuon.Get("MuonFakeUp/sigDiscriminator")
    mtmfakesdown = fakesTauMuon.Get("MuonFakeDown/sigDiscriminator")
    f1 = tfakesup.Clone()
    f1.add(mfakes)
    f1.add(mttfakesup, -1)
    f1 = positivize(f1)
    f1.SetName("Fakes_TauFakesUp")
    f2 = tfakesdown.Clone()
    f2.add(mfakes)
    f2.add(mttfakesdown, -1)
    f2 = positivize(f2)
    f2.SetName("Fakes_TauFakesDown")
    f3 = tfakes.Clone()
    f3.add(mfakesup)
    f3.add(mtmfakesup, -1)
    f3 = positivize(f3)
    f3.SetName("Fakes_MuonFakesUp")
    f4 = tfakes.Clone()
    f4.add(mfakesdown)
    f4.add(mtmfakesdown, -1)
    f4 = positivize(f4)
    f4.SetName("Fakes_MuonFakesDown")
    tfakes.Delete()
    mfakes.Delete()
    mtfakes.Delete()
    tfakesup.Delete()
    tfakesdown.Delete()
    mfakesup.Delete()
    mfakesdown.Delete()
    mttfakesup.Delete()
    mttfakesdown.Delete()
    mtmfakesup.Delete()
    mtmfakesdown.Delete()

    for i in range(11):
        DYtotal = v[i]
        DYall = views.SubdirectoryView(DYtotal, 'TightOS'+di)
        DYtfakes = views.SubdirectoryView(DYtotal, 'TauLooseOS'+di)
        DYmfakes = views.SubdirectoryView(DYtotal, 'MuonLooseOS'+di)
        DYmtfakes = views.SubdirectoryView(DYtotal, 'MuonLooseTauLooseOS'+di)
        DYmt = views.SumView(DYtfakes, DYmfakes)
        DYfakes = SubtractionView(DYmt, DYmtfakes, restrict_positive=True)
        DY = SubtractionView(DYall, DYfakes, restrict_positive=True)
        dy = DY.Get("sigDiscriminator")
        dy.SetName(b[i])

        dypuup = DY.Get("puUp/sigDiscriminator")
        dypuup.SetName(b[i]+"_PU_UncertaintyUp")
        dypudown = DY.Get("puDown/sigDiscriminator")
        dypudown.SetName(b[i]+"_PU_UncertaintyDown")

        dytrup = DY.Get("trUp/sigDiscriminator")
        dytrup.SetName(b[i]+"_Trigger_UncertaintyUp")
        dytrdown = DY.Get("trDown/sigDiscriminator")
        dytrdown.SetName(b[i]+"_Trigger_UncertaintyDown")

        dyrecrespup = DY.Get("recrespUp/sigDiscriminator")
        dyrecrespup.SetName(b[i]+"_RecoilResponse_UncertaintyUp")
        dyrecrespdown = DY.Get("recrespDown/sigDiscriminator")
        dyrecrespdown.SetName(b[i]+"_RecoilResponse_UncertaintyDown")

        dyrecresoup = DY.Get("recresoUp/sigDiscriminator")
        dyrecresoup.SetName(b[i]+"_RecoilResolution_UncertaintyUp")
        dyrecresodown = DY.Get("recresoDown/sigDiscriminator")
        dyrecresodown.SetName(b[i]+"_RecoilResolution_UncertaintyDown")

        dyptup = DY.Get("DYptreweightUp/sigDiscriminator")
        dyptup.SetName(b[i]+"_pTreweight_UncertaintyUp")
        dyptdown = DY.Get("DYptreweightDown/sigDiscriminator")
        dyptdown.SetName(b[i]+"_pTreweight_UncertaintyDown")

        dymtfakeup = DY.Get("mtfakeUp/sigDiscriminator")
        dymtfakeup.SetName(b[i]+"_mtfake_UncertaintyUp")
        dymtfakedown = DY.Get("mtfakeDown/sigDiscriminator")
        dymtfakedown.SetName(b[i]+"_mtfake_UncertaintyDown")

        dyetfakeup = DY.Get("etfakeUp/sigDiscriminator")
        dyetfakeup.SetName(b[i]+"_etfake_UncertaintyUp")
        dyetfakedown = DY.Get("etfakeDown/sigDiscriminator")
        dyetfakedown.SetName(b[i]+"_etfake_UncertaintyDown")

        dyetefakeup = DY.Get("etefakeUp/sigDiscriminator")
        dyetefakeup.SetName(b[i]+"_etefake_UncertaintyUp")
        dyetefakedown = DY.Get("etefakeDown/sigDiscriminator")
        dyetefakedown.SetName(b[i]+"_etefake_UncertaintyDown")

        dytes0up = DY.Get("scaletDM0Up/sigDiscriminator")
        dytes0up.SetName(b[i]+"_TESDM0Up")
        dytes0down = DY.Get("scaletDM0Down/sigDiscriminator")
        dytes0down.SetName(b[i]+"_TESDM0Down")
        dytes1up = DY.Get("scaletDM1Up/sigDiscriminator")
        dytes1up.SetName(b[i]+"_TESDM1Up")
        dytes1down = DY.Get("scaletDM1Down/sigDiscriminator")
        dytes1down.SetName(b[i]+"_TESDM1Down")
        dytes10up = DY.Get("scaletDM10Up/sigDiscriminator")
        dytes10up.SetName(b[i]+"_TESDM10Up")
        dytes10down = DY.Get("scaletDM10Down/sigDiscriminator")
        dytes10down.SetName(b[i]+"_TESDM10Down")

        dymesup = DY.Get("mesUp/sigDiscriminator")
        dymesup.SetName(b[i]+"_MESUp")
        dymesdown = DY.Get("mesDown/sigDiscriminator")
        dymesdown.SetName(b[i]+"_MESDown")

        dyuesup = DY.Get("UnclusteredEnUp/sigDiscriminator")
        dyuesup.SetName(b[i]+"_UnclusteredEnUp")
        dyuesdown = DY.Get("UnclusteredEnDown/sigDiscriminator")
        dyuesdown.SetName(b[i]+"_UnclusteredEnDown")

        dyjetAFMup = DY.Get("AbsoluteFlavMapUp/sigDiscriminator")
        dyjetAFMup.SetName(b[i]+"_AbsoluteFlavMapUp")
        dyjetAFMdown = DY.Get("AbsoluteFlavMapDown/sigDiscriminator")
        dyjetAFMdown.SetName(b[i]+"_AbsoluteFlavMapDown")
        dyjetAMPFBup = DY.Get("AbsoluteMPFBiasUp/sigDiscriminator")
        dyjetAMPFBup.SetName(b[i]+"_AbsoluteMPFBiasUp")
        dyjetAMPFBdown = DY.Get("AbsoluteMPFBiasDown/sigDiscriminator")
        dyjetAMPFBdown.SetName(b[i]+"_AbsoluteMPFBiasDown")
        dyjetASup = DY.Get("JetAbsoluteScaleUp/sigDiscriminator")
        dyjetASup.SetName(b[i]+"_JetAbsoluteScaleUp")
        dyjetASdown = DY.Get("JetAbsoluteScaleDown/sigDiscriminator")
        dyjetASdown.SetName(b[i]+"_JetAbsoluteScaleDown")
        dyjetAStup = DY.Get("JetAbsoluteStatUp/sigDiscriminator")
        dyjetAStup.SetName(b[i]+"_JetAbsoluteStatUp")
        dyjetAStdown = DY.Get("JetAbsoluteStatDown/sigDiscriminator")
        dyjetAStdown.SetName(b[i]+"_JetAbsoluteStatDown")
        dyjetFQCDup = DY.Get("JetFlavorQCDUp/sigDiscriminator")
        dyjetFQCDup.SetName(b[i]+"_JetFlavorQCDUp")
        dyjetFQCDdown = DY.Get("JetFlavorQCDDown/sigDiscriminator")
        dyjetFQCDdown.SetName(b[i]+"_JetFlavorQCDDown")
        dyjetFup = DY.Get("JetFragmentationUp/sigDiscriminator")
        dyjetFup.SetName(b[i]+"_JetFragmentationUp")
        dyjetFdown = DY.Get("JetFragmentationDown/sigDiscriminator")
        dyjetFdown.SetName(b[i]+"_JetFragmentationDown")
        dyjetPUDMCup = DY.Get("JetPileUpDataMCUp/sigDiscriminator")
        dyjetPUDMCup.SetName(b[i]+"_JetPileUpDataMCUp")
        dyjetPUDMCdown = DY.Get("JetPileUpDataMCDown/sigDiscriminator")
        dyjetPUDMCdown.SetName(b[i]+"_JetPileUpDataMCDown")
        dyjetPUPBBup = DY.Get("JetPileUpPtBBUp/sigDiscriminator")
        dyjetPUPBBup.SetName(b[i]+"_JetPileUpPtBBUp")
        dyjetPUPBBdown = DY.Get("JetPileUpPtBBDown/sigDiscriminator")
        dyjetPUPBBdown.SetName(b[i]+"_JetPileUpPtBBDown")
        dyjetPUPEC1up = DY.Get("JetPileUpPtEC1Up/sigDiscriminator")
        dyjetPUPEC1up.SetName(b[i]+"_JetPileUpPtEC1Up")
        dyjetPUPEC1down = DY.Get("JetPileUpPtEC1Down/sigDiscriminator")
        dyjetPUPEC1down.SetName(b[i]+"_JetPileUpPtEC1Down")
        dyjetPUPEC2up = DY.Get("JetPileUpPtEC2Up/sigDiscriminator")
        dyjetPUPEC2up.SetName(b[i]+"_JetPileUpPtEC2Up")
        dyjetPUPEC2down = DY.Get("JetPileUpPtEC2Down/sigDiscriminator")
        dyjetPUPEC2down.SetName(b[i]+"_JetPileUpPtEC2Down")
        dyjetPUPHFup = DY.Get("JetPileUpPtHFUp/sigDiscriminator")
        dyjetPUPHFup.SetName(b[i]+"_JetPileUpPtHFUp")
        dyjetPUPHFdown = DY.Get("JetPileUpPtHFDown/sigDiscriminator")
        dyjetPUPHFdown.SetName(b[i]+"_JetPileUpPtHFDown")
        dyjetPUPRup = DY.Get("JetPileUpPtRefUp/sigDiscriminator")
        dyjetPUPRup.SetName(b[i]+"_JetPileUpPtRefUp")
        dyjetPUPRdown = DY.Get("JetPileUpPtRefDown/sigDiscriminator")
        dyjetPUPRdown.SetName(b[i]+"_JetPileUpPtRefDown")
        dyjetRFSRup = DY.Get("JetRelativeFSRUp/sigDiscriminator")
        dyjetRFSRup.SetName(b[i]+"_JetRelativeFSRUp")
        dyjetRFSRdown = DY.Get("JetRelativeFSRDown/sigDiscriminator")
        dyjetRFSRdown.SetName(b[i]+"_JetRelativeFSRDown")
        dyjetRJEREC1up = DY.Get("JetRelativeJEREC1Up/sigDiscriminator")
        dyjetRJEREC1up.SetName(b[i]+"_JetRelativeJEREC1Up")
        dyjetRJEREC1down = DY.Get("JetRelativeJEREC1Down/sigDiscriminator")
        dyjetRJEREC1down.SetName(b[i]+"_JetRelativeJEREC1Down")
        dyjetRJEREC2up = DY.Get("JetRelativeJEREC2Up/sigDiscriminator")
        dyjetRJEREC2up.SetName(b[i]+"_JetRelativeJEREC2Up")
        dyjetRJEREC2down = DY.Get("JetRelativeJEREC2Down/sigDiscriminator")
        dyjetRJEREC2down.SetName(b[i]+"_JetRelativeJEREC2Down")
        dyjetRJERHFup = DY.Get("JetRelativeJERHFUp/sigDiscriminator")
        dyjetRJERHFup.SetName(b[i]+"_JetRelativeJERHFUp")
        dyjetRJERHFdown = DY.Get("JetRelativeJERHFDown/sigDiscriminator")
        dyjetRJERHFdown.SetName(b[i]+"_JetRelativeJERHFDown")
        dyjetRPBBup = DY.Get("JetRelativePtBBUp/sigDiscriminator")
        dyjetRPBBup.SetName(b[i]+"_JetRelativePtBBUp")
        dyjetRPBBdown = DY.Get("JetRelativePtBBDown/sigDiscriminator")
        dyjetRPBBdown.SetName(b[i]+"_JetRelativePtBBDown")
        dyjetRPEC1up = DY.Get("JetRelativePtEC1Up/sigDiscriminator")
        dyjetRPEC1up.SetName(b[i]+"_JetRelativePtEC1Up")
        dyjetRPEC1down = DY.Get("JetRelativePtEC1Down/sigDiscriminator")
        dyjetRPEC1down.SetName(b[i]+"_JetRelativePtEC1Down")
        dyjetRPEC2up = DY.Get("JetRelativePtEC2Up/sigDiscriminator")
        dyjetRPEC2up.SetName(b[i]+"_JetRelativePtEC2Up")
        dyjetRPEC2down = DY.Get("JetRelativePtEC2Down/sigDiscriminator")
        dyjetRPEC2down.SetName(b[i]+"_JetRelativePtEC2Down")
        dyjetRPHFup = DY.Get("JetRelativePtHFUp/sigDiscriminator")
        dyjetRPHFup.SetName(b[i]+"_JetRelativePtHFUp")
        dyjetRPHFdown = DY.Get("JetRelativePtHFDown/sigDiscriminator")
        dyjetRPHFdown.SetName(b[i]+"_JetRelativePtHFDown")
        dyjetRSECup = DY.Get("JetRelativeStatECUp/sigDiscriminator")
        dyjetRSECup.SetName(b[i]+"_JetRelativeStatECUp")
        dyjetRSECdown = DY.Get("JetRelativeStatECDown/sigDiscriminator")
        dyjetRSECdown.SetName(b[i]+"_JetRelativeStatECDown")
        dyjetRSFSRup = DY.Get("JetRelativeStatFSRUp/sigDiscriminator")
        dyjetRSFSRup.SetName(b[i]+"_JetRelativeStatFSRUp")
        dyjetRSFSRdown = DY.Get("JetRelativeStatFSRDown/sigDiscriminator")
        dyjetRSFSRdown.SetName(b[i]+"_JetRelativeStatFSRDown")
        dyjetRSHFup = DY.Get("JetRelativeStatHFUp/sigDiscriminator")
        dyjetRSHFup.SetName(b[i]+"_JetRelativeStatHFUp")
        dyjetRSHFdown = DY.Get("JetRelativeStatHFDown/sigDiscriminator")
        dyjetRSHFdown.SetName(b[i]+"_JetRelativeStatHFDown")
        dyjetSPEup = DY.Get("JetSinglePionECALUp/sigDiscriminator")
        dyjetSPEup.SetName(b[i]+"_JetSinglePionECALUp")
        dyjetSPEdown = DY.Get("JetSinglePionECALDown/sigDiscriminator")
        dyjetSPEdown.SetName(b[i]+"_JetSinglePionECALDown")
        dyjetSPHup = DY.Get("JetSinglePionHCALUp/sigDiscriminator")
        dyjetSPHup.SetName(b[i]+"_JetSinglePionHCALUp")
        dyjetSPHdown = DY.Get("JetSinglePionHCALDown/sigDiscriminator")
        dyjetSPHdown.SetName(b[i]+"_JetSinglePionHCALDown")
        dyjetTPEup = DY.Get("JetTimePtEtaUp/sigDiscriminator")
        dyjetTPEup.SetName(b[i]+"_JetTimePtEtaUp")
        dyjetTPEdown = DY.Get("JetTimePtEtaDown/sigDiscriminator")
        dyjetTPEdown.SetName(b[i]+"_JetTimePtEtaDown")
        dyjetRBup = DY.Get("JetRelativeBalUp/sigDiscriminator")
        dyjetRBup.SetName(b[i]+"_JetRelativeBalUp")
        dyjetRBdown = DY.Get("JetRelativeBalDown/sigDiscriminator")
        dyjetRBdown.SetName(b[i]+"_JetRelativeBalDown")
        dyjetRSup = DY.Get("JetRelativeSampleUp/sigDiscriminator")
        dyjetRSup.SetName(b[i]+"_JetRelativeSampleUp")
        dyjetRSdown = DY.Get("JetRelativeSampleDown/sigDiscriminator")
        dyjetRSdown.SetName(b[i]+"_JetRelativeSampleDown")

        dyall = DYall.Get("sigDiscriminator")
        dytfakes = DYtfakes.Get("sigDiscriminator")
        dymfakes = DYmfakes.Get("sigDiscriminator")
        dymtfakes = DYmtfakes.Get("sigDiscriminator")
        dytfakesup = DYtfakes.Get("TauFakeUp/sigDiscriminator") 
        dytfakesdown = DYtfakes.Get("TauFakeDown/sigDiscriminator")
        dymfakesup = DYmfakes.Get("MuonFakeUp/sigDiscriminator")
        dymfakesdown = DYmfakes.Get("MuonFakeDown/sigDiscriminator")
        dymttfakesup = DYmtfakes.Get("TauFakeUp/sigDiscriminator")
        dymttfakesdown = DYmtfakes.Get("TauFakeDown/sigDiscriminator")
        dymtmfakesup = DYmtfakes.Get("MuonFakeUp/sigDiscriminator")
        dymtmfakesdown = DYmtfakes.Get("MuonFakeDown/sigDiscriminator")
        dy1 = dyall.Clone()
        dy1t = dytfakesup.Clone()
        dy1t.add(dymfakes)
        dy1t.add(dymttfakesup, -1)
        dy1t = positivize(dy1t)
        dy1.add(dy1t, -1)
        dy1 = positivize(dy1)
        dy1.SetName(b[i]+"_TauFakesUp")
        dy2 = dyall.Clone()
        dy2t = dytfakesdown.Clone()
        dy2t.add(dymfakes)
        dy2t.add(dymttfakesdown, -1)
        dy2t = positivize(dy2t)
        dy2.add(dy2t, -1)
        dy2 = positivize(dy2)
        dy2.SetName(b[i]+"_TauFakesDown")
        dy3 = dyall.Clone()
        dy3t = dytfakes.Clone()
        dy3t.add(dymfakesup)
        dy3t.add(dymtmfakesup, -1)
        dy3t = positivize(dy3t)
        dy3.add(dy3t, -1)
        dy3 = positivize(dy3)
        dy3.SetName(b[i]+"_MuonFakesUp")
        dy4 = dyall.Clone()
        dy4t = dytfakes.Clone()
        dy4t.add(dymfakesdown)
        dy4t.add(dymtmfakesdown, -1)
        dy4t = positivize(dy4t)
        dy4.add(dy4t, -1)
        dy4 = positivize(dy4)
        dy4.SetName(b[i]+"_MuonFakesDown")
        dyall.Delete()
        dy1t.Delete()
        dy2t.Delete()
        dy3t.Delete()
        dy4t.Delete()
        dytfakes.Delete()
        dymfakes.Delete()
        dymtfakes.Delete()
        dytfakesup.Delete()
        dytfakesdown.Delete()
        dymfakesup.Delete()
        dymfakesdown.Delete()
        dymttfakesup.Delete()
        dymttfakesdown.Delete()
        dymtmfakesup.Delete()
        dymtmfakesdown.Delete()
        if i==1:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1.Delete()
            f2.Delete()
            f3.Delete()
            f4.Delete()
            e1.Delete()
            e2.Delete()
            embtrup.Delete()
            embtrdown.Delete()
            embseltrup.Delete()
            embseltrdown.Delete()
            embtrkup.Delete()
            embtrkdown.Delete()
            embtes0up.Delete()
            embtes0down.Delete()
            embtes1up.Delete()
            embtes1down.Delete()
            embtes10up.Delete()
            embtes10down.Delete()
        f.Write()
