import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'mt'
period = '13TeV'
sqrts = 13

def positivize(histogram):
    output = histogram.Clone()
    for i in range(output.GetSize()):
        if output.GetArray()[i] < 0:
            output.AddAt(0, i)
    return output

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'GluGluHToWW*', 'VBFHToWW*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('../results/%s/AnalyzeMuTauSysBDT/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('../inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = '../plots/%s/AnalyzeMuTauSysBDT/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'Shapes/shapesMTBDT.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') or x.startswith('DYJetsToLL_M-10to50'), mc_samples )]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('EWK') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGluHToTauTau') or x.startswith('GluGluHToWW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBFHToTauTau') or x.startswith('VBFHToWW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('WminusHToTauTau') or x.startswith('WplusHToTauTau') or x.startswith('ZHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGlu_LFV') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBF_LFV') , mc_samples)])
]

b = ['Zll', 'EWK', 'GluGluH', 'VBFH', 'VH', 'TT', 'ST', 'EWKDiboson', 'GluGlu125', 'VBF125']

for di in dirs:

    if di=='0Jet':
        binning = array.array('d', [-0.7, -0.55, -0.5, -0.45, -0.40, -0.35, -0.30, -0.25, -0.20, -0.15, -0.10, -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25])
    elif di=='1Jet':
        binning = array.array('d', [-0.65, -0.5, -0.45, -0.40, -0.35, -0.30, -0.25, -0.20, -0.15, -0.14, -0.13, -0.12, -0.11, -0.10, -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23])
    elif di=='2Jet':
        binning = array.array('d', [-0.65, -0.5, -0.45, -0.40, -0.35, -0.30, -0.25, -0.20, -0.15, -0.10, -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23])
    else:
        binning = array.array('d', [-0.55, -0.40, -0.35, -0.30, -0.29, -0.28, -0.27, -0.26, -0.25, -0.24, -0.23, -0.22, -0.21, -0.20, -0.19, -0.18, -0.17, -0.16, -0.15, -0.14, -0.13, -0.12, -0.11, -0.10, -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.22])

    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    data = DataTotal.Get('TightOS'+di+'/bdtDiscriminator')
    data = data.Rebin(len(binning)-1, 'data_obs', binning)

    embed = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    emball = embed.Get('TightOS'+di+'/bdtDiscriminator')
    embtfakes = embed.Get('TauLooseOS'+di+'/bdtDiscriminator')
    embmfakes = embed.Get('MuonLooseOS'+di+'/bdtDiscriminator')
    embmtfakes = embed.Get('MuonLooseTauLooseOS'+di+'/bdtDiscriminator')
    embfakes = embtfakes.Clone()
    embfakes.Add(embmfakes)
    embfakes.Add(embmtfakes, -1)
    embfakes = positivize(embfakes)
    emb = emball.Clone()
    emb.Add(embfakes, -1)
    emb = positivize(emb)
    emb = emb.Rebin(len(binning)-1, 'embed', binning)

    embtrkup = embed.Get('TightOS'+di+'/embtrkUp/bdtDiscriminator')
    embtrkup.Add(embfakes, -1)
    embtrkup = positivize(embtrkup)
    embtrkup = embtrkup.Rebin(len(binning)-1, 'embed_CMS_tracking_tauUp', binning)
    embtrkdown = embed.Get('TightOS'+di+'/embtrkDown/bdtDiscriminator')
    embtrkdown.Add(embfakes, -1)
    embtrkdown = positivize(embtrkdown)
    embtrkdown = embtrkdown.Rebin(len(binning)-1, 'embed_CMS_tracking_tauDown', binning)

    embtes0up = embed.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
    embtes0up.Add(embfakes, -1)
    embtes0up = positivize(embtes0up)
    embtes0up = embtes0up.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong_13TeVUp', binning)
    embtes0down = embed.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
    embtes0down.Add(embfakes, -1)
    embtes0down = positivize(embtes0down)
    embtes0down = embtes0down.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong_13TeVDown', binning)

    embtes1up = embed.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
    embtes1up.Add(embfakes, -1)
    embtes1up = positivize(embtes1up)
    embtes1up = embtes1up.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong1pizero_13TeVUp', binning)
    embtes1down = embed.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
    embtes1down.Add(embfakes, -1)
    embtes1down = positivize(embtes1down)
    embtes1down = embtes1down.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong1pizero_13TeVDown', binning)

    embtes10up = embed.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
    embtes10up.Add(embfakes, -1)
    embtes10up = positivize(embtes10up)
    embtes10up = embtes10up.Rebin(len(binning)-1, 'embed_CMS_scale_t_3prong_13TeVUp', binning)
    embtes10down = embed.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
    embtes10down.Add(embfakes, -1)
    embtes10down = positivize(embtes10down)
    embtes10down = embtes10down.Rebin(len(binning)-1, 'embed_CMS_scale_t_3prong_13TeVDown', binning)

    embtb0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    embtb0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    embtb1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    embtb1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    embtb10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    embtb10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    embte0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    embte0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    embte1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    embte1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    embte10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    embte10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    embmfakesup = embed.Get('MuonLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
    embmfakesdown = embed.Get('MuonLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
    embmttb0fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    embmttb0fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    embmttb1fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    embmttb1fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    embmttb10fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    embmttb10fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    embmtte0fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    embmtte0fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    embmtte1fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    embmtte1fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    embmtte10fakesup = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    embmtte10fakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    embmtmfakesup = embed.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
    embmtmfakesdown = embed.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
    emb1b0 = emball.Clone()
    emb1tb0 = embtb0fakesup.Clone()
    emb1tb0.add(embmfakes)
    emb1tb0.add(embmttb0fakesup, -1)
    emb1tb0 = positivize(emb1tb0)
    emb1b0.add(emb1tb0, -1)
    emb1b0 = positivize(emb1b0)
    emb1b0 = emb1b0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
    emb2b0 = emball.Clone()
    emb2tb0 = embtb0fakesdown.Clone()
    emb2tb0.add(embmfakes)
    emb2tb0.add(embmttb0fakesdown, -1)
    emb2tb0 = positivize(emb2tb0)
    emb2b0.add(emb2tb0, -1)
    emb2b0 = positivize(emb2b0)
    emb2b0 = emb2b0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
    emb1b1 = emball.Clone()
    emb1tb1 = embtb1fakesup.Clone()
    emb1tb1.add(embmfakes)
    emb1tb1.add(embmttb1fakesup, -1)
    emb1tb1 = positivize(emb1tb1)
    emb1b1.add(emb1tb1, -1)
    emb1b1 = positivize(emb1b1)
    emb1b1 = emb1b1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
    emb2b1 = emball.Clone()
    emb2tb1 = embtb1fakesdown.Clone()
    emb2tb1.add(embmfakes)
    emb2tb1.add(embmttb1fakesdown, -1)
    emb2tb1 = positivize(emb2tb1)
    emb2b1.add(emb2tb1, -1)
    emb2b1 = positivize(emb2b1)
    emb2b1 = emb2b1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
    emb1b10 = emball.Clone()
    emb1tb10 = embtb10fakesup.Clone()
    emb1tb10.add(embmfakes)
    emb1tb10.add(embmttb10fakesup, -1)
    emb1tb10 = positivize(emb1tb10)
    emb1b10.add(emb1tb10, -1)
    emb1b10 = positivize(emb1b10)
    emb1b10 = emb1b10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
    emb2b10 = emball.Clone()
    emb2tb10 = embtb10fakesdown.Clone()
    emb2tb10.add(embmfakes)
    emb2tb10.add(embmttb10fakesdown, -1)
    emb2tb10 = positivize(emb2tb10)
    emb2b10.add(emb2tb10, -1)
    emb2b10 = positivize(emb2b10)
    emb2b10 = emb2b10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
    emb1e0 = emball.Clone()
    emb1te0 = embte0fakesup.Clone()
    emb1te0.add(embmfakes)
    emb1te0.add(embmtte0fakesup, -1)
    emb1te0 = positivize(emb1te0)
    emb1e0.add(emb1te0, -1)
    emb1e0 = positivize(emb1e0)
    emb1e0 = emb1e0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
    emb2e0 = emball.Clone()
    emb2te0 = embte0fakesdown.Clone()
    emb2te0.add(embmfakes)
    emb2te0.add(embmtte0fakesdown, -1)
    emb2te0 = positivize(emb2te0)
    emb2e0.add(emb2te0, -1)
    emb2e0 = positivize(emb2e0)
    emb2e0 = emb2e0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
    emb1e1 = emball.Clone()
    emb1te1 = embte1fakesup.Clone()
    emb1te1.add(embmfakes)
    emb1te1.add(embmtte1fakesup, -1)
    emb1te1 = positivize(emb1te1)
    emb1e1.add(emb1te1, -1)
    emb1e1 = positivize(emb1e1)
    emb1e1 = emb1e1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
    emb2e1 = emball.Clone()
    emb2te1 = embte1fakesdown.Clone()
    emb2te1.add(embmfakes)
    emb2te1.add(embmtte1fakesdown, -1)
    emb2te1 = positivize(emb2te1)
    emb2e1.add(emb2te1, -1)
    emb2e1 = positivize(emb2e1)
    emb2e1 = emb2e1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
    emb1e10 = emball.Clone()
    emb1te10 = embte10fakesup.Clone()
    emb1te10.add(embmfakes)
    emb1te10.add(embmtte10fakesup, -1)
    emb1te10 = positivize(emb1te10)
    emb1e10.add(emb1te10, -1)
    emb1e10 = positivize(emb1e10)
    emb1e10 = emb1e10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
    emb2e10 = emball.Clone()
    emb2te10 = embte10fakesdown.Clone()
    emb2te10.add(embmfakes)
    emb2te10.add(embmtte10fakesdown, -1)
    emb2te10 = positivize(emb2te10)
    emb2e10.add(emb2te10, -1)
    emb2e10 = positivize(emb2e10)
    emb2e10 = emb2e10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
    emb3 = emball.Clone()
    emb3t = embtfakes.Clone()
    emb3t.add(embmfakesup)
    emb3t.add(embmtmfakesup, -1)
    emb3t = positivize(emb3t)
    emb3.add(emb3t, -1)
    emb3 = positivize(emb3)
    emb3 = emb3.Rebin(len(binning)-1, 'embed_CMS_MuonFakeRate_13TeVUp', binning)
    emb4 = emball.Clone()
    emb4t = embtfakes.Clone()
    emb4t.add(embmfakesdown)
    emb4t.add(embmtmfakesdown, -1)
    emb4t = positivize(emb4t)
    emb4.add(emb4t, -1)
    emb4 = positivize(emb4)
    emb4 = emb4.Rebin(len(binning)-1, 'embed_CMS_MuonFakeRate_13TeVDown', binning)
    emball.Delete()
    emb1tb0.Delete()
    emb2tb0.Delete()
    emb1tb1.Delete()
    emb2tb1.Delete()
    emb1tb10.Delete()
    emb2tb10.Delete()
    emb1te0.Delete()
    emb2te0.Delete()
    emb1te1.Delete()
    emb2te1.Delete()
    emb1te10.Delete()
    emb2te10.Delete()
    emb3t.Delete()
    emb4t.Delete()
    embfakes.Delete()
    embtfakes.Delete()
    embmfakes.Delete()
    embmtfakes.Delete()
    embte0fakesup.Delete()
    embte0fakesdown.Delete()
    embte1fakesup.Delete()
    embte1fakesdown.Delete()
    embte10fakesup.Delete()
    embte10fakesdown.Delete()
    embtb0fakesup.Delete()
    embtb0fakesdown.Delete()
    embtb1fakesup.Delete()
    embtb1fakesdown.Delete()
    embtb10fakesup.Delete()
    embtb10fakesdown.Delete()
    embmfakesup.Delete()
    embmfakesdown.Delete()
    embmtte0fakesup.Delete()
    embmtte0fakesdown.Delete()
    embmtte1fakesup.Delete()
    embmtte1fakesdown.Delete()
    embmtte10fakesup.Delete()
    embmtte10fakesdown.Delete()
    embmttb0fakesup.Delete()
    embmttb0fakesdown.Delete()
    embmttb1fakesup.Delete()
    embmttb1fakesdown.Delete()
    embmttb10fakesup.Delete()
    embmttb10fakesdown.Delete()
    embmtmfakesup.Delete()
    embmtmfakesdown.Delete()

    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    tfakes = QCD.Get('TauLooseOS'+di+'/bdtDiscriminator')
    mfakes = QCD.Get('MuonLooseOS'+di+'/bdtDiscriminator')
    mtfakes = QCD.Get('MuonLooseTauLooseOS'+di+'/bdtDiscriminator')
    qcd = tfakes.Clone()
    qcd.Add(mfakes)
    qcd.Add(mtfakes, -1)
    qcd = positivize(qcd)
    qcd.SetName('Fakes')
    te0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    te0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    te1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    te1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    te10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    te10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    tb0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    tb0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    tb1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    tb1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    tb10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    tb10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    mfakesup = QCD.Get('MuonLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
    mfakesdown = QCD.Get('MuonLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
    mtte0fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
    mtte0fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
    mtte1fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
    mtte1fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
    mtte10fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
    mtte10fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
    mttb0fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
    mttb0fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
    mttb1fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
    mttb1fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
    mttb10fakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
    mttb10fakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
    mtmfakesup = QCD.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
    mtmfakesdown = QCD.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
    f1e0 = te0fakesup.Clone()
    f1e0.add(mfakes)
    f1e0.add(mtte0fakesup, -1)
    f1e0 = positivize(f1e0)
    f1e0 = f1e0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
    f2e0 = te0fakesdown.Clone()
    f2e0.add(mfakes)
    f2e0.add(mtte0fakesdown, -1)
    f2e0 = positivize(f2e0)
    f2e0 = f2e0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
    f1e1 = te1fakesup.Clone()
    f1e1.add(mfakes)
    f1e1.add(mtte1fakesup, -1)
    f1e1 = positivize(f1e1)
    f1e1 = f1e1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
    f2e1 = te1fakesdown.Clone()
    f2e1.add(mfakes)
    f2e1.add(mtte1fakesdown, -1)
    f2e1 = positivize(f2e1)
    f2e1 = f2e1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
    f1e10 = te10fakesup.Clone()
    f1e10.add(mfakes)
    f1e10.add(mtte10fakesup, -1)
    f1e10 = positivize(f1e10)
    f1e10 = f1e10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
    f2e10 = te10fakesdown.Clone()
    f2e10.add(mfakes)
    f2e10.add(mtte10fakesdown, -1)
    f2e10 = positivize(f2e10)
    f2e10 = f2e10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
    f1b0 = tb0fakesup.Clone()
    f1b0.add(mfakes)
    f1b0.add(mttb0fakesup, -1)
    f1b0 = positivize(f1b0)
    f1b0 = f1b0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
    f2b0 = tb0fakesdown.Clone()
    f2b0.add(mfakes)
    f2b0.add(mttb0fakesdown, -1)
    f2b0 = positivize(f2b0)
    f2b0 = f2b0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
    f1b1 = tb1fakesup.Clone()
    f1b1.add(mfakes)
    f1b1.add(mttb1fakesup, -1)
    f1b1 = positivize(f1b1)
    f1b1 = f1b1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
    f2b1 = tb1fakesdown.Clone()
    f2b1.add(mfakes)
    f2b1.add(mttb1fakesdown, -1)
    f2b1 = positivize(f2b1)
    f2b1 = f2b1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
    f1b10 = tb10fakesup.Clone()
    f1b10.add(mfakes)
    f1b10.add(mttb10fakesup, -1)
    f1b10 = positivize(f1b10)
    f1b10 = f1b10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
    f2b10 = tb10fakesdown.Clone()
    f2b10.add(mfakes)
    f2b10.add(mttb10fakesdown, -1)
    f2b10 = positivize(f2b10)
    f2b10 = f2b10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
    f3 = tfakes.Clone()
    f3.add(mfakesup)
    f3.add(mtmfakesup, -1)
    f3 = positivize(f3)
    f3 = f3.Rebin(len(binning)-1, 'Fakes_CMS_MuonFakeRate_13TeVUp', binning)
    f4 = tfakes.Clone()
    f4.add(mfakesdown)
    f4.add(mtmfakesdown, -1)
    f4 = positivize(f4)
    f4 = f4.Rebin(len(binning)-1, 'Fakes_CMS_MuonFakeRate_13TeVDown', binning)
    tfakes.Delete()
    mfakes.Delete()
    mtfakes.Delete()
    te0fakesup.Delete()
    te0fakesdown.Delete()
    te1fakesup.Delete()
    te1fakesdown.Delete()
    te10fakesup.Delete()
    te10fakesdown.Delete()
    tb0fakesup.Delete()
    tb0fakesdown.Delete()
    tb1fakesup.Delete()
    tb1fakesdown.Delete()
    tb10fakesup.Delete()
    tb10fakesdown.Delete()
    mfakesup.Delete()
    mfakesdown.Delete()
    mtte0fakesup.Delete()
    mtte0fakesdown.Delete()
    mtte1fakesup.Delete()
    mtte1fakesdown.Delete()
    mtte10fakesup.Delete()
    mtte10fakesdown.Delete()
    mttb0fakesup.Delete()
    mttb0fakesdown.Delete()
    mttb1fakesup.Delete()
    mttb1fakesdown.Delete()
    mttb10fakesup.Delete()
    mttb10fakesdown.Delete()
    mtmfakesup.Delete()
    mtmfakesdown.Delete()

    for i in range(10):
        DY = v[i]
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dy = dy.Rebin(len(binning)-1, b[i], binning)

            dypuup = DY.Get('TightOS'+di+'/puUp/bdtDiscriminator')
            dypuup = dypuup.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVUp', binning)
            dypudown = DY.Get('TightOS'+di+'/puDown/bdtDiscriminator')
            dypudown = dypudown.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVDown', binning)

            dypfup = DY.Get('TightOS'+di+'/pfUp/bdtDiscriminator')
            dypfup = dypfup.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVUp', binning)
            dypfdown = DY.Get('TightOS'+di+'/pfDown/bdtDiscriminator')
            dypfdown = dypfdown.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVDown', binning)

            dytidup = DY.Get('TightOS'+di+'/tidUp/bdtDiscriminator')
            dytidup = dytidup.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauUp', binning)
            dytiddown = DY.Get('TightOS'+di+'/tidDown/bdtDiscriminator')
            dytiddown = dytiddown.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauDown', binning)

            dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/bdtDiscriminator')
            dyrecrespup = dyrecrespup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVUp', binning)
            dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/bdtDiscriminator')
            dyrecrespdown = dyrecrespdown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVDown', binning)

            dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/bdtDiscriminator')
            dyrecresoup = dyrecresoup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVUp', binning)
            dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/bdtDiscriminator')
            dyrecresodown = dyrecresodown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVDown', binning)

            dymtfakeup = DY.Get('TightOS'+di+'/mtfakeUp/bdtDiscriminator')
            dymtfakeup = dymtfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVUp', binning)
            dymtfakedown = DY.Get('TightOS'+di+'/mtfakeDown/bdtDiscriminator')
            dymtfakedown = dymtfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVDown', binning)

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dyetfakeup = dyetfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVUp', binning)
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dyetfakedown = dyetfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVDown', binning)

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/bdtDiscriminator')
            dyetefakeup = dyetefakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVUp', binning)
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/bdtDiscriminator')
            dyetefakedown = dyetefakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVDown', binning)

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
            dytes0up = dytes0up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVUp', binning)
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
            dytes0down = dytes0down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVDown', binning)

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
            dytes1up = dytes1up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp', binning)
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
            dytes1down = dytes1down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown', binning)

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
            dytes10up = dytes10up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVUp', binning)
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
            dytes10down = dytes10down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVDown', binning)

            dymesup = DY.Get('TightOS'+di+'/mesUp/bdtDiscriminator')
            dymesup = dymesup.Rebin(len(binning)-1, b[i]+'_CMS_MES_13TeVUp', binning)
            dymesdown = DY.Get('TightOS'+di+'/mesDown/bdtDiscriminator')
            dymesdown = dymesdown.Rebin(len(binning)-1, b[i]+'_CMS_MES_13TeVDown', binning)

        else:
            dyall = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dytfakes = DY.Get('TauLooseOS'+di+'/bdtDiscriminator')
            dymfakes = DY.Get('MuonLooseOS'+di+'/bdtDiscriminator')
            dymtfakes = DY.Get('MuonLooseTauLooseOS'+di+'/bdtDiscriminator')
            dyfakes = dytfakes.Clone()
            dyfakes.Add(dymfakes)
            dyfakes.Add(dymtfakes, -1)
            dyfakes = positivize(dyfakes)
            dyall.Add(dyfakes, -1)
            dy = positivize(dyall)
            dy = dy.Rebin(len(binning)-1, b[i], binning)

            dypuup = DY.Get('TightOS'+di+'/puUp/bdtDiscriminator')
            dypuup.Add(dyfakes, -1)
            dypuup = positivize(dypuup)
            dypuup = dypuup.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVUp', binning)
            dypudown = DY.Get('TightOS'+di+'/puDown/bdtDiscriminator')
            dypudown.Add(dyfakes, -1)
            dypudown = positivize(dypudown)
            dypudown = dypudown.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVDown', binning)

            dypfup = DY.Get('TightOS'+di+'/pfUp/bdtDiscriminator')
            dypfup.Add(dyfakes, -1)
            dypfup = positivize(dypfup)
            dypfup = dypfup.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVUp', binning)
            dypfdown = DY.Get('TightOS'+di+'/pfDown/bdtDiscriminator')
            dypfdown.Add(dyfakes, -1)
            dypfdown = positivize(dypfdown)
            dypfdown = dypfdown.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVDown', binning)

            dytidup = DY.Get('TightOS'+di+'/tidUp/bdtDiscriminator')
            dytidup.Add(dyfakes, -1)
            dytidup = positivize(dytidup)
            dytidup = dytidup.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauUp', binning)
            dytiddown = DY.Get('TightOS'+di+'/tidDown/bdtDiscriminator')
            dytiddown.Add(dyfakes, -1)
            dytiddown = positivize(dytiddown)
            dytiddown = dytiddown.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauDown', binning)

            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/bdtDiscriminator')
                dyrecrespup.Add(dyfakes, -1)
                dyrecrespup = positivize(dyrecrespup)
                dyrecrespup = dyrecrespup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVUp', binning)
                dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/bdtDiscriminator')
                dyrecrespdown.Add(dyfakes, -1)
                dyrecrespdown = positivize(dyrecrespdown)
                dyrecrespdown = dyrecrespdown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVDown', binning)

                dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/bdtDiscriminator')
                dyrecresoup.Add(dyfakes, -1)
                dyrecresoup = positivize(dyrecresoup)
                dyrecresoup = dyrecresoup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVUp', binning)
                dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/bdtDiscriminator')
                dyrecresodown.Add(dyfakes, -1)
                dyrecresodown = positivize(dyrecresodown)
                dyrecresodown = dyrecresodown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVDown', binning)

            if b[i]=='Zll':
                dyptup = DY.Get('TightOS'+di+'/DYptreweightUp/bdtDiscriminator')
                dyptup.Add(dyfakes, -1)
                dyptup = positivize(dyptup)
                dyptup = dyptup.Rebin(len(binning)-1, b[i]+'_CMS_DYpTreweight_13TeVUp', binning)
                dyptdown = DY.Get('TightOS'+di+'/DYptreweightDown/bdtDiscriminator')
                dyptdown.Add(dyfakes, -1)
                dyptdown = positivize(dyptdown)
                dyptdown = dyptdown.Rebin(len(binning)-1, b[i]+'_CMS_DYpTreweight_13TeVDown', binning)

            if b[i]=='TT' or b[i]=='ST':
                dybtagup = DY.Get('TightOS'+di+'/bTagUp/bdtDiscriminator')
                dybtagup.Add(dyfakes, -1)
                dybtagup = positivize(dybtagup)
                dybtagup = dybtagup.Rebin(len(binning)-1, b[i]+'_CMS_eff_btag_13TeVUp', binning)
                dybtagdown = DY.Get('TightOS'+di+'/bTagDown/bdtDiscriminator')
                dybtagdown.Add(dyfakes, -1)
                dybtagdown = positivize(dybtagdown)
                dybtagdown = dybtagdown.Rebin(len(binning)-1, b[i]+'_CMS_eff_btag_13TeVDown', binning)

            if b[i]=='TT':
                dytptup = DY.Get('TightOS'+di+'/TopptreweightUp/bdtDiscriminator')
                dytptup.Add(dyfakes, -1)
                dytptup = positivize(dytptup)
                dytptup = dytptup.Rebin(len(binning)-1, b[i]+'_CMS_ToppTreweight_13TeVUp', binning)
                dytptdown = DY.Get('TightOS'+di+'/TopptreweightDown/bdtDiscriminator')
                dytptdown.Add(dyfakes, -1)
                dytptdown = positivize(dytptdown)
                dytptdown = dytptdown.Rebin(len(binning)-1, b[i]+'_CMS_ToppTreweight_13TeVDown', binning)

            dymtfakeup = DY.Get('TightOS'+di+'/mtfakeUp/bdtDiscriminator')
            dymtfakeup.Add(dyfakes, -1)
            dymtfakeup = positivize(dymtfakeup)
            dymtfakeup = dymtfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVUp', binning)
            dymtfakedown = DY.Get('TightOS'+di+'/mtfakeDown/bdtDiscriminator')
            dymtfakedown.Add(dyfakes, -1)
            dymtfakedown = positivize(dymtfakedown)
            dymtfakedown = dymtfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVDown', binning)

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/bdtDiscriminator')
            dyetfakeup.Add(dyfakes, -1)
            dyetfakeup = positivize(dyetfakeup)
            dyetfakeup = dyetfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVUp', binning)
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/bdtDiscriminator')
            dyetfakedown.Add(dyfakes, -1)
            dyetfakedown = positivize(dyetfakedown)
            dyetfakedown = dyetfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVDown', binning)

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/bdtDiscriminator')
            dyetefakeup.Add(dyfakes, -1)
            dyetefakeup = positivize(dyetefakeup)
            dyetefakeup = dyetefakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVUp', binning)
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/bdtDiscriminator')
            dyetefakedown.Add(dyfakes, -1)
            dyetefakedown = positivize(dyetefakedown)
            dyetefakedown = dyetefakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVDown', binning)

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/bdtDiscriminator')
            dytes0up.Add(dyfakes, -1)
            dytes0up = positivize(dytes0up)
            dytes0up = dytes0up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVUp', binning)
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/bdtDiscriminator')
            dytes0down.Add(dyfakes, -1)
            dytes0down = positivize(dytes0down)
            dytes0down = dytes0down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVDown', binning)

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/bdtDiscriminator')
            dytes1up.Add(dyfakes, -1)
            dytes1up = positivize(dytes1up)
            dytes1up = dytes1up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp', binning)
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/bdtDiscriminator')
            dytes1down.Add(dyfakes, -1)
            dytes1down = positivize(dytes1down)
            dytes1down = dytes1down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown', binning)

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/bdtDiscriminator')
            dytes10up.Add(dyfakes, -1)
            dytes10up = positivize(dytes10up)
            dytes10up = dytes10up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVUp', binning)
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/bdtDiscriminator')
            dytes10down.Add(dyfakes, -1)
            dytes10down = positivize(dytes10down)
            dytes10down = dytes10down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVDown', binning)

            dymesup = DY.Get('TightOS'+di+'/mesUp/bdtDiscriminator')
            dymesup.Add(dyfakes, -1)
            dymesup = positivize(dymesup)
            dymesup = dymesup.Rebin(len(binning)-1, b[i]+'_CMS_MES_13TeVUp', binning)
            dymesdown = DY.Get('TightOS'+di+'/mesDown/bdtDiscriminator')
            dymesdown.Add(dyfakes, -1)
            dymesdown = positivize(dymesdown)
            dymesdown = dymesdown.Rebin(len(binning)-1, b[i]+'_CMS_MES_13TeVDown', binning)

            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup = DY.Get('TightOS'+di+'/UnclusteredEnUp/bdtDiscriminator')
                dyuesup.Add(dyfakes, -1)
                dyuesup = positivize(dyuesup)
                dyuesup = dyuesup.Rebin(len(binning)-1, b[i]+'_CMS_MET_Ues_13TeVUp', binning)
                dyuesdown = DY.Get('TightOS'+di+'/UnclusteredEnDown/bdtDiscriminator')
                dyuesdown.Add(dyfakes, -1)
                dyuesdown = positivize(dyuesdown)
                dyuesdown = dyuesdown.Rebin(len(binning)-1, b[i]+'_CMS_MET_Ues_13TeVDown', binning)

                dyjetAFMup = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapUp/bdtDiscriminator')
                dyjetAFMup.Add(dyfakes, -1)
                dyjetAFMup = positivize(dyjetAFMup)
                dyjetAFMup = dyjetAFMup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVUp', binning)
                dyjetAFMdown = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapDown/bdtDiscriminator')
                dyjetAFMdown.Add(dyfakes, -1)
                dyjetAFMdown = positivize(dyjetAFMdown)
                dyjetAFMdown = dyjetAFMdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVDown', binning)

                dyjetAMPFBup = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasUp/bdtDiscriminator')
                dyjetAMPFBup.Add(dyfakes, -1)
                dyjetAMPFBup = positivize(dyjetAMPFBup)
                dyjetAMPFBup = dyjetAMPFBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVUp', binning)
                dyjetAMPFBdown = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasDown/bdtDiscriminator')
                dyjetAMPFBdown.Add(dyfakes, -1)
                dyjetAMPFBdown = positivize(dyjetAMPFBdown)
                dyjetAMPFBdown = dyjetAMPFBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVDown', binning)

                dyjetASup = DY.Get('TightOS'+di+'/JetAbsoluteScaleUp/bdtDiscriminator')
                dyjetASup.Add(dyfakes, -1)
                dyjetASup = positivize(dyjetASup)
                dyjetASup = dyjetASup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVUp', binning)
                dyjetASdown = DY.Get('TightOS'+di+'/JetAbsoluteScaleDown/bdtDiscriminator')
                dyjetASdown.Add(dyfakes, -1)
                dyjetASdown = positivize(dyjetASdown)
                dyjetASdown = dyjetASdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVDown', binning)

                dyjetAStup = DY.Get('TightOS'+di+'/JetAbsoluteStatUp/bdtDiscriminator')
                dyjetAStup.Add(dyfakes, -1)
                dyjetAStup = positivize(dyjetAStup)
                dyjetAStup = dyjetAStup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVUp', binning)
                dyjetAStdown = DY.Get('TightOS'+di+'/JetAbsoluteStatDown/bdtDiscriminator')
                dyjetAStdown.Add(dyfakes, -1)
                dyjetAStdown = positivize(dyjetAStdown)
                dyjetAStdown = dyjetAStdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVDown', binning)

                dyjetFQCDup = DY.Get('TightOS'+di+'/JetFlavorQCDUp/bdtDiscriminator')
                dyjetFQCDup.Add(dyfakes, -1)
                dyjetFQCDup = positivize(dyjetFQCDup)
                dyjetFQCDup = dyjetFQCDup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFlavorQCD_13TeVUp', binning)
                dyjetFQCDdown = DY.Get('TightOS'+di+'/JetFlavorQCDDown/bdtDiscriminator')
                dyjetFQCDdown.Add(dyfakes, -1)
                dyjetFQCDdown = positivize(dyjetFQCDdown)
                dyjetFQCDdown = dyjetFQCDdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFlavorQCD_13TeVDown', binning)

                dyjetFup = DY.Get('TightOS'+di+'/JetFragmentationUp/bdtDiscriminator')
                dyjetFup.Add(dyfakes, -1)
                dyjetFup = positivize(dyjetFup)
                dyjetFup = dyjetFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFragmentation_13TeVUp', binning)
                dyjetFdown = DY.Get('TightOS'+di+'/JetFragmentationDown/bdtDiscriminator')
                dyjetFdown.Add(dyfakes, -1)
                dyjetFdown = positivize(dyjetFdown)
                dyjetFdown = dyjetFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFragmentation_13TeVDown', binning)

                dyjetPUDMCup = DY.Get('TightOS'+di+'/JetPileUpDataMCUp/bdtDiscriminator')
                dyjetPUDMCup.Add(dyfakes, -1)
                dyjetPUDMCup = positivize(dyjetPUDMCup)
                dyjetPUDMCup = dyjetPUDMCup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVUp', binning)
                dyjetPUDMCdown = DY.Get('TightOS'+di+'/JetPileUpDataMCDown/bdtDiscriminator')
                dyjetPUDMCdown.Add(dyfakes, -1)
                dyjetPUDMCdown = positivize(dyjetPUDMCdown)
                dyjetPUDMCdown = dyjetPUDMCdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVDown', binning)

                dyjetPUPBBup = DY.Get('TightOS'+di+'/JetPileUpPtBBUp/bdtDiscriminator')
                dyjetPUPBBup.Add(dyfakes, -1)
                dyjetPUPBBup = positivize(dyjetPUPBBup)
                dyjetPUPBBup = dyjetPUPBBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVUp', binning)
                dyjetPUPBBdown = DY.Get('TightOS'+di+'/JetPileUpPtBBDown/bdtDiscriminator')
                dyjetPUPBBdown.Add(dyfakes, -1)
                dyjetPUPBBdown = positivize(dyjetPUPBBdown)
                dyjetPUPBBdown = dyjetPUPBBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVDown', binning)

                dyjetPUPEC1up = DY.Get('TightOS'+di+'/JetPileUpPtEC1Up/bdtDiscriminator')
                dyjetPUPEC1up.Add(dyfakes, -1)
                dyjetPUPEC1up = positivize(dyjetPUPEC1up)
                dyjetPUPEC1up = dyjetPUPEC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVUp', binning)
                dyjetPUPEC1down = DY.Get('TightOS'+di+'/JetPileUpPtEC1Down/bdtDiscriminator')
                dyjetPUPEC1down.Add(dyfakes, -1)
                dyjetPUPEC1down = positivize(dyjetPUPEC1down)
                dyjetPUPEC1down = dyjetPUPEC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVDown', binning)

                dyjetPUPEC2up = DY.Get('TightOS'+di+'/JetPileUpPtEC2Up/bdtDiscriminator')
                dyjetPUPEC2up.Add(dyfakes, -1)
                dyjetPUPEC2up = positivize(dyjetPUPEC2up)
                dyjetPUPEC2up = dyjetPUPEC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVUp', binning)
                dyjetPUPEC2down = DY.Get('TightOS'+di+'/JetPileUpPtEC2Down/bdtDiscriminator')
                dyjetPUPEC2down.Add(dyfakes, -1)
                dyjetPUPEC2down = positivize(dyjetPUPEC2down)
                dyjetPUPEC2down = dyjetPUPEC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVDown', binning)

                dyjetPUPHFup = DY.Get('TightOS'+di+'/JetPileUpPtHFUp/bdtDiscriminator')
                dyjetPUPHFup.Add(dyfakes, -1)
                dyjetPUPHFup = positivize(dyjetPUPHFup)
                dyjetPUPHFup = dyjetPUPHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVUp', binning)
                dyjetPUPHFdown = DY.Get('TightOS'+di+'/JetPileUpPtHFDown/bdtDiscriminator')
                dyjetPUPHFdown.Add(dyfakes, -1)
                dyjetPUPHFdown = positivize(dyjetPUPHFdown)
                dyjetPUPHFdown = dyjetPUPHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVDown', binning)

                dyjetPUPRup = DY.Get('TightOS'+di+'/JetPileUpPtRefUp/bdtDiscriminator')
                dyjetPUPRup.Add(dyfakes, -1)
                dyjetPUPRup = positivize(dyjetPUPRup)
                dyjetPUPRup = dyjetPUPRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVUp', binning)
                dyjetPUPRdown = DY.Get('TightOS'+di+'/JetPileUpPtRefDown/bdtDiscriminator')
                dyjetPUPRdown.Add(dyfakes, -1)
                dyjetPUPRdown = positivize(dyjetPUPRdown)
                dyjetPUPRdown = dyjetPUPRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVDown', binning)

                dyjetRFSRup = DY.Get('TightOS'+di+'/JetRelativeFSRUp/bdtDiscriminator')
                dyjetRFSRup.Add(dyfakes, -1)
                dyjetRFSRup = positivize(dyjetRFSRup)
                dyjetRFSRup = dyjetRFSRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeFSR_13TeVUp', binning)
                dyjetRFSRdown = DY.Get('TightOS'+di+'/JetRelativeFSRDown/bdtDiscriminator')
                dyjetRFSRdown.Add(dyfakes, -1)
                dyjetRFSRdown = positivize(dyjetRFSRdown)
                dyjetRFSRdown = dyjetRFSRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeFSR_13TeVDown', binning)

                dyjetRJEREC1up = DY.Get('TightOS'+di+'/JetRelativeJEREC1Up/bdtDiscriminator')
                dyjetRJEREC1up.Add(dyfakes, -1)
                dyjetRJEREC1up = positivize(dyjetRJEREC1up)
                dyjetRJEREC1up = dyjetRJEREC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVUp', binning)
                dyjetRJEREC1down = DY.Get('TightOS'+di+'/JetRelativeJEREC1Down/bdtDiscriminator')
                dyjetRJEREC1down.Add(dyfakes, -1)
                dyjetRJEREC1down = positivize(dyjetRJEREC1down)
                dyjetRJEREC1down = dyjetRJEREC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVDown', binning)

                dyjetRJEREC2up = DY.Get('TightOS'+di+'/JetRelativeJEREC2Up/bdtDiscriminator')
                dyjetRJEREC2up.Add(dyfakes, -1)
                dyjetRJEREC2up = positivize(dyjetRJEREC2up)
                dyjetRJEREC2up = dyjetRJEREC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVUp', binning)
                dyjetRJEREC2down = DY.Get('TightOS'+di+'/JetRelativeJEREC2Down/bdtDiscriminator')
                dyjetRJEREC2down.Add(dyfakes, -1)
                dyjetRJEREC2down = positivize(dyjetRJEREC2down)
                dyjetRJEREC2down = dyjetRJEREC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVDown', binning)

                dyjetRJERHFup = DY.Get('TightOS'+di+'/JetRelativeJERHFUp/bdtDiscriminator')
                dyjetRJERHFup.Add(dyfakes, -1)
                dyjetRJERHFup = positivize(dyjetRJERHFup)
                dyjetRJERHFup = dyjetRJERHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVUp', binning)
                dyjetRJERHFdown = DY.Get('TightOS'+di+'/JetRelativeJERHFDown/bdtDiscriminator')
                dyjetRJERHFdown.Add(dyfakes, -1)
                dyjetRJERHFdown = positivize(dyjetRJERHFdown)
                dyjetRJERHFdown = dyjetRJERHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVDown', binning)

                dyjetRPBBup = DY.Get('TightOS'+di+'/JetRelativePtBBUp/bdtDiscriminator')
                dyjetRPBBup.Add(dyfakes, -1)
                dyjetRPBBup = positivize(dyjetRPBBup)
                dyjetRPBBup = dyjetRPBBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtBB_13TeVUp', binning)
                dyjetRPBBdown = DY.Get('TightOS'+di+'/JetRelativePtBBDown/bdtDiscriminator')
                dyjetRPBBdown.Add(dyfakes, -1)
                dyjetRPBBdown = positivize(dyjetRPBBdown)
                dyjetRPBBdown = dyjetRPBBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtBB_13TeVDown', binning)

                dyjetRPEC1up = DY.Get('TightOS'+di+'/JetRelativePtEC1Up/bdtDiscriminator')
                dyjetRPEC1up.Add(dyfakes, -1)
                dyjetRPEC1up = positivize(dyjetRPEC1up)
                dyjetRPEC1up = dyjetRPEC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVUp', binning)
                dyjetRPEC1down = DY.Get('TightOS'+di+'/JetRelativePtEC1Down/bdtDiscriminator')
                dyjetRPEC1down.Add(dyfakes, -1)
                dyjetRPEC1down = positivize(dyjetRPEC1down)
                dyjetRPEC1down = dyjetRPEC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVDown', binning)

                dyjetRPEC2up = DY.Get('TightOS'+di+'/JetRelativePtEC2Up/bdtDiscriminator')
                dyjetRPEC2up.Add(dyfakes, -1)
                dyjetRPEC2up = positivize(dyjetRPEC2up)
                dyjetRPEC2up = dyjetRPEC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVUp', binning)
                dyjetRPEC2down = DY.Get('TightOS'+di+'/JetRelativePtEC2Down/bdtDiscriminator')
                dyjetRPEC2down.Add(dyfakes, -1)
                dyjetRPEC2down = positivize(dyjetRPEC2down)
                dyjetRPEC2down = dyjetRPEC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVDown', binning)

                dyjetRPHFup = DY.Get('TightOS'+di+'/JetRelativePtHFUp/bdtDiscriminator')
                dyjetRPHFup.Add(dyfakes, -1)
                dyjetRPHFup = positivize(dyjetRPHFup)
                dyjetRPHFup = dyjetRPHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtHF_13TeVUp', binning)
                dyjetRPHFdown = DY.Get('TightOS'+di+'/JetRelativePtHFDown/bdtDiscriminator')
                dyjetRPHFdown.Add(dyfakes, -1)
                dyjetRPHFdown = positivize(dyjetRPHFdown)
                dyjetRPHFdown = dyjetRPHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtHF_13TeVDown', binning)

                dyjetRSECup = DY.Get('TightOS'+di+'/JetRelativeStatECUp/bdtDiscriminator')
                dyjetRSECup.Add(dyfakes, -1)
                dyjetRSECup = positivize(dyjetRSECup)
                dyjetRSECup = dyjetRSECup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVUp', binning)
                dyjetRSECdown = DY.Get('TightOS'+di+'/JetRelativeStatECDown/bdtDiscriminator')
                dyjetRSECdown.Add(dyfakes, -1)
                dyjetRSECdown = positivize(dyjetRSECdown)
                dyjetRSECdown = dyjetRSECdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVDown', binning)

                dyjetRSFSRup = DY.Get('TightOS'+di+'/JetRelativeStatFSRUp/bdtDiscriminator')
                dyjetRSFSRup.Add(dyfakes, -1)
                dyjetRSFSRup = positivize(dyjetRSFSRup)
                dyjetRSFSRup = dyjetRSFSRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVUp', binning)
                dyjetRSFSRdown = DY.Get('TightOS'+di+'/JetRelativeStatFSRDown/bdtDiscriminator')
                dyjetRSFSRdown.Add(dyfakes, -1)
                dyjetRSFSRdown = positivize(dyjetRSFSRdown)
                dyjetRSFSRdown = dyjetRSFSRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVDown', binning)

                dyjetRSHFup = DY.Get('TightOS'+di+'/JetRelativeStatHFUp/bdtDiscriminator')
                dyjetRSHFup.Add(dyfakes, -1)
                dyjetRSHFup = positivize(dyjetRSHFup)
                dyjetRSHFup = dyjetRSHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVUp', binning)
                dyjetRSHFdown = DY.Get('TightOS'+di+'/JetRelativeStatHFDown/bdtDiscriminator')
                dyjetRSHFdown.Add(dyfakes, -1)
                dyjetRSHFdown = positivize(dyjetRSHFdown)
                dyjetRSHFdown = dyjetRSHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVDown', binning)

                dyjetSPEup = DY.Get('TightOS'+di+'/JetSinglePionECALUp/bdtDiscriminator')
                dyjetSPEup.Add(dyfakes, -1)
                dyjetSPEup = positivize(dyjetSPEup)
                dyjetSPEup = dyjetSPEup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVUp', binning)
                dyjetSPEdown = DY.Get('TightOS'+di+'/JetSinglePionECALDown/bdtDiscriminator')
                dyjetSPEdown.Add(dyfakes, -1)
                dyjetSPEdown = positivize(dyjetSPEdown)
                dyjetSPEdown = dyjetSPEdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVDown', binning)

                dyjetSPHup = DY.Get('TightOS'+di+'/JetSinglePionHCALUp/bdtDiscriminator')
                dyjetSPHup.Add(dyfakes, -1)
                dyjetSPHup = positivize(dyjetSPHup)
                dyjetSPHup = dyjetSPHup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVUp', binning)
                dyjetSPHdown = DY.Get('TightOS'+di+'/JetSinglePionHCALDown/bdtDiscriminator')
                dyjetSPHdown.Add(dyfakes, -1)
                dyjetSPHdown = positivize(dyjetSPHdown)
                dyjetSPHdown = dyjetSPHdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVDown', binning)

                dyjetTPEup = DY.Get('TightOS'+di+'/JetTimePtEtaUp/bdtDiscriminator')
                dyjetTPEup.Add(dyfakes, -1)
                dyjetTPEup = positivize(dyjetTPEup)
                dyjetTPEup = dyjetTPEup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetTimePtEta_13TeVUp', binning)
                dyjetTPEdown = DY.Get('TightOS'+di+'/JetTimePtEtaDown/bdtDiscriminator')
                dyjetTPEdown.Add(dyfakes, -1)
                dyjetTPEdown = positivize(dyjetTPEdown)
                dyjetTPEdown = dyjetTPEdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetTimePtEta_13TeVDown', binning)

                dyjetRBup = DY.Get('TightOS'+di+'/JetRelativeBalUp/bdtDiscriminator')
                dyjetRBup.Add(dyfakes, -1)
                dyjetRBup = positivize(dyjetRBup)
                dyjetRBup = dyjetRBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeBal_13TeVUp', binning)
                dyjetRBdown = DY.Get('TightOS'+di+'/JetRelativeBalDown/bdtDiscriminator')
                dyjetRBdown.Add(dyfakes, -1)
                dyjetRBdown = positivize(dyjetRBdown)
                dyjetRBdown = dyjetRBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeBal_13TeVDown', binning)

                dyjetRSup = DY.Get('TightOS'+di+'/JetRelativeSampleUp/bdtDiscriminator')
                dyjetRSup.Add(dyfakes, -1)
                dyjetRSup = positivize(dyjetRSup)
                dyjetRSup = dyjetRSup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeSample_13TeVUp', binning)
                dyjetRSdown = DY.Get('TightOS'+di+'/JetRelativeSampleDown/bdtDiscriminator')
                dyjetRSdown.Add(dyfakes, -1)
                dyjetRSdown = positivize(dyjetRSdown)
                dyjetRSdown = dyjetRSdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeSample_13TeVDown', binning)

            dyall = DY.Get('TightOS'+di+'/bdtDiscriminator')
            dyte0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
            dyte0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
            dyte1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
            dyte1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
            dyte10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
            dyte10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
            dytb0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
            dytb0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
            dytb1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
            dytb1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
            dytb10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
            dytb10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
            dymfakesup = DY.Get('MuonLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
            dymfakesdown = DY.Get('MuonLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
            dymtte0fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Up/bdtDiscriminator')
            dymtte0fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM0Down/bdtDiscriminator')
            dymtte1fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Up/bdtDiscriminator')
            dymtte1fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM1Down/bdtDiscriminator')
            dymtte10fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Up/bdtDiscriminator')
            dymtte10fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEEDM10Down/bdtDiscriminator')
            dymttb0fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Up/bdtDiscriminator')
            dymttb0fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM0Down/bdtDiscriminator')
            dymttb1fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Up/bdtDiscriminator')
            dymttb1fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM1Down/bdtDiscriminator')
            dymttb10fakesup = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Up/bdtDiscriminator')
            dymttb10fakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/TauFakeEBDM10Down/bdtDiscriminator')
            dymtmfakesup = DY.Get('MuonLooseTauLooseOS'+di+'/MuonFakeUp/bdtDiscriminator')
            dymtmfakesdown = DY.Get('MuonLooseTauLooseOS'+di+'/MuonFakeDown/bdtDiscriminator')
            dy1e0 = dyall.Clone()
            dy1te0 = dyte0fakesup.Clone()
            dy1te0.add(dymfakes)
            dy1te0.add(dymtte0fakesup, -1)
            dy1te0 = positivize(dy1te0)
            dy1e0.add(dy1te0, -1)
            dy1e0 = positivize(dy1e0)
            dy1e0 = dy1e0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
            dy2e0 = dyall.Clone()
            dy2te0 = dyte0fakesdown.Clone()
            dy2te0.add(dymfakes)
            dy2te0.add(dymtte0fakesdown, -1)
            dy2te0 = positivize(dy2te0)
            dy2e0.add(dy2te0, -1)
            dy2e0 = positivize(dy2e0)
            dy2e0 = dy2e0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
            dy1e1 = dyall.Clone()
            dy1te1 = dyte1fakesup.Clone()
            dy1te1.add(dymfakes)
            dy1te1.add(dymtte1fakesup, -1)
            dy1te1 = positivize(dy1te1)
            dy1e1.add(dy1te1, -1)
            dy1e1 = positivize(dy1e1)
            dy1e1 = dy1e1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
            dy2e1 = dyall.Clone()
            dy2te1 = dyte1fakesdown.Clone()
            dy2te1.add(dymfakes)
            dy2te1.add(dymtte1fakesdown, -1)
            dy2te1 = positivize(dy2te1)
            dy2e1.add(dy2te1, -1)
            dy2e1 = positivize(dy2e1)
            dy2e1 = dy2e1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
            dy1e10 = dyall.Clone()
            dy1te10 = dyte10fakesup.Clone()
            dy1te10.add(dymfakes)
            dy1te10.add(dymtte10fakesup, -1)
            dy1te10 = positivize(dy1te10)
            dy1e10.add(dy1te10, -1)
            dy1e10 = positivize(dy1e10)
            dy1e10 = dy1e10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
            dy2e10 = dyall.Clone()
            dy2te10 = dyte10fakesdown.Clone()
            dy2te10.add(dymfakes)
            dy2te10.add(dymtte10fakesdown, -1)
            dy2te10 = positivize(dy2te10)
            dy2e10.add(dy2te10, -1)
            dy2e10 = positivize(dy2e10)
            dy2e10 = dy2e10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
            dy1b0 = dyall.Clone()
            dy1tb0 = dytb0fakesup.Clone()
            dy1tb0.add(dymfakes)
            dy1tb0.add(dymttb0fakesup, -1)
            dy1tb0 = positivize(dy1tb0)
            dy1b0.add(dy1tb0, -1)
            dy1b0 = positivize(dy1b0)
            dy1b0 = dy1b0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
            dy2b0 = dyall.Clone()
            dy2tb0 = dytb0fakesdown.Clone()
            dy2tb0.add(dymfakes)
            dy2tb0.add(dymttb0fakesdown, -1)
            dy2tb0 = positivize(dy2tb0)
            dy2b0.add(dy2tb0, -1)
            dy2b0 = positivize(dy2b0)
            dy2b0 = dy2b0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
            dy1b1 = dyall.Clone()
            dy1tb1 = dytb1fakesup.Clone()
            dy1tb1.add(dymfakes)
            dy1tb1.add(dymttb1fakesup, -1)
            dy1tb1 = positivize(dy1tb1)
            dy1b1.add(dy1tb1, -1)
            dy1b1 = positivize(dy1b1)
            dy1b1 = dy1b1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
            dy2b1 = dyall.Clone()
            dy2tb1 = dytb1fakesdown.Clone()
            dy2tb1.add(dymfakes)
            dy2tb1.add(dymttb1fakesdown, -1)
            dy2tb1 = positivize(dy2tb1)
            dy2b1.add(dy2tb1, -1)
            dy2b1 = positivize(dy2b1)
            dy2b1 = dy2b1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
            dy1b10 = dyall.Clone()
            dy1tb10 = dytb10fakesup.Clone()
            dy1tb10.add(dymfakes)
            dy1tb10.add(dymttb10fakesup, -1)
            dy1tb10 = positivize(dy1tb10)
            dy1b10.add(dy1tb10, -1)
            dy1b10 = positivize(dy1b10)
            dy1b10 = dy1b10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
            dy2b10 = dyall.Clone()
            dy2tb10 = dytb10fakesdown.Clone()
            dy2tb10.add(dymfakes)
            dy2tb10.add(dymttb10fakesdown, -1)
            dy2tb10 = positivize(dy2tb10)
            dy2b10.add(dy2tb10, -1)
            dy2b10 = positivize(dy2b10)
            dy2b10 = dy2b10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
            dy3 = dyall.Clone()
            dy3t = dytfakes.Clone()
            dy3t.add(dymfakesup)
            dy3t.add(dymtmfakesup, -1)
            dy3t = positivize(dy3t)
            dy3.add(dy3t, -1)
            dy3 = positivize(dy3)
            dy3 = dy3.Rebin(len(binning)-1, b[i]+'_CMS_MuonFakeRate_13TeVUp', binning)
            dy4 = dyall.Clone()
            dy4t = dytfakes.Clone()
            dy4t.add(dymfakesdown)
            dy4t.add(dymtmfakesdown, -1)
            dy4t = positivize(dy4t)
            dy4.add(dy4t, -1)
            dy4 = positivize(dy4)
            dy4 = dy4.Rebin(len(binning)-1, b[i]+'_CMS_MuonFakeRate_13TeVDown', binning)
            dyall.Delete()
            dy1te0.Delete()
            dy2te0.Delete()
            dy1te1.Delete()
            dy2te1.Delete()
            dy1te10.Delete()
            dy2te10.Delete()
            dy1tb0.Delete()
            dy2tb0.Delete()
            dy1tb1.Delete()
            dy2tb1.Delete()
            dy1tb10.Delete()
            dy2tb10.Delete()
            dy3t.Delete()
            dy4t.Delete()
            dyfakes.Delete()
            dytfakes.Delete()
            dymfakes.Delete()
            dymtfakes.Delete()
            dyte0fakesup.Delete()
            dyte0fakesdown.Delete()
            dyte1fakesup.Delete()
            dyte1fakesdown.Delete()
            dyte10fakesup.Delete()
            dyte10fakesdown.Delete()
            dytb0fakesup.Delete()
            dytb0fakesdown.Delete()
            dytb1fakesup.Delete()
            dytb1fakesdown.Delete()
            dytb10fakesup.Delete()
            dytb10fakesdown.Delete()
            dymfakesup.Delete()
            dymfakesdown.Delete()
            dymtte0fakesup.Delete()
            dymtte0fakesdown.Delete()
            dymtte1fakesup.Delete()
            dymtte1fakesdown.Delete()
            dymtte10fakesup.Delete()
            dymtte10fakesdown.Delete()
            dymttb0fakesup.Delete()
            dymttb0fakesdown.Delete()
            dymttb1fakesup.Delete()
            dymttb1fakesdown.Delete()
            dymttb10fakesup.Delete()
            dymttb10fakesdown.Delete()
            dymtmfakesup.Delete()
            dymtmfakesdown.Delete()

        f.Write()
        if i==0:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1e0.Delete()
            f2e0.Delete()
            f1e1.Delete()
            f2e1.Delete()
            f1e10.Delete()
            f2e10.Delete()
            f1b0.Delete()
            f2b0.Delete()
            f1b1.Delete()
            f2b1.Delete()
            f1b10.Delete()
            f2b10.Delete()
            f3.Delete()
            f4.Delete()
            emb1e0.Delete()
            emb2e0.Delete()
            emb1e1.Delete()
            emb2e1.Delete()
            emb1e10.Delete()
            emb2e10.Delete()
            emb1b0.Delete()
            emb2b0.Delete()
            emb1b1.Delete()
            emb2b1.Delete()
            emb1b10.Delete()
            emb2b10.Delete()
            emb3.Delete()
            emb4.Delete()
            embtrkup.Delete()
            embtrkdown.Delete()
            embtes0up.Delete()
            embtes0down.Delete()
            embtes1up.Delete()
            embtes1down.Delete()
            embtes10up.Delete()
            embtes10down.Delete()
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dypfup.Delete()
            dypfdown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            dyrecrespup.Delete()
            dyrecrespdown.Delete()
            dyrecresoup.Delete()
            dyrecresodown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dymesup.Delete()
            dymesdown.Delete()
        else:
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dypfup.Delete()
            dypfdown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup.Delete()
                dyrecrespdown.Delete()
                dyrecresoup.Delete()
                dyrecresodown.Delete()
            if b[i]=='Zll':
                dyptup.Delete()
                dyptdown.Delete()
            if b[i]=='TT' or b[i]=='ST':
                dybtagup.Delete()
                dybtagdown.Delete()
            if b[i]=='TT':
                dytptup.Delete()
                dytptdown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dymesup.Delete()
            dymesdown.Delete()
            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup.Delete()
                dyuesdown.Delete()
                dyjetAFMup.Delete()
                dyjetAFMdown.Delete()
                dyjetAMPFBup.Delete()
                dyjetAMPFBdown.Delete()
                dyjetASup.Delete()
                dyjetASdown.Delete()
                dyjetAStup.Delete()
                dyjetAStdown.Delete()
                dyjetFQCDup.Delete()
                dyjetFQCDdown.Delete()
                dyjetFup.Delete()
                dyjetFdown.Delete()
                dyjetPUDMCup.Delete()
                dyjetPUDMCdown.Delete()
                dyjetPUPBBup.Delete()
                dyjetPUPBBdown.Delete()
                dyjetPUPEC1up.Delete()
                dyjetPUPEC1down.Delete()
                dyjetPUPEC2up.Delete()
                dyjetPUPEC2down.Delete()
                dyjetPUPHFup.Delete()
                dyjetPUPHFdown.Delete()
                dyjetPUPRup.Delete()
                dyjetPUPRdown.Delete()
                dyjetRFSRup.Delete()
                dyjetRFSRdown.Delete()
                dyjetRJEREC1up.Delete()
                dyjetRJEREC1down.Delete()
                dyjetRJEREC2up.Delete()
                dyjetRJEREC2down.Delete()
                dyjetRJERHFup.Delete()
                dyjetRJERHFdown.Delete()
                dyjetRPBBup.Delete()
                dyjetRPBBdown.Delete()
                dyjetRPEC1up.Delete()
                dyjetRPEC1down.Delete()
                dyjetRPEC2up.Delete()
                dyjetRPEC2down.Delete()
                dyjetRPHFup.Delete()
                dyjetRPHFdown.Delete()
                dyjetRSECup.Delete()
                dyjetRSECdown.Delete()
                dyjetRSFSRup.Delete()
                dyjetRSFSRdown.Delete()
                dyjetRSHFup.Delete()
                dyjetRSHFdown.Delete()
                dyjetSPEup.Delete()
                dyjetSPEdown.Delete()
                dyjetSPHup.Delete()
                dyjetSPHdown.Delete()
                dyjetTPEup.Delete()
                dyjetTPEdown.Delete()
                dyjetRBup.Delete()
                dyjetRBdown.Delete()
                dyjetRSup.Delete()
                dyjetRSdown.Delete()
            dy1e0.Delete()
            dy2e0.Delete()
            dy1e1.Delete()
            dy2e1.Delete()
            dy1e10.Delete()
            dy2e10.Delete()
            dy1b0.Delete()
            dy2b0.Delete()
            dy1b1.Delete()
            dy2b1.Delete()
            dy1b10.Delete()
            dy2b10.Delete()
            dy3.Delete()
            dy4.Delete()
