# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'
require 'pathname'

$jobid = ENV['jobid']
$blind = ENV['blind']

# Figure out what run period we are in
$period = '13TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#
samples = Hash[
		"eraA" => get_sample_names('data_EGamma_Run2018A-17Sep2018'),	
                "eraB" => get_sample_names('data_EGamma_Run2018B-17Sep2018'),
                "eraC" => get_sample_names('data_EGamma_Run2018C-17Sep2018'),
                "eraD" => get_sample_names('data_EGamma_Run2018D-PromptReco'),
		"DY" => get_sample_names('DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_-102X_upgrade2018_realistic_v15-v1'),
                "DY1" => get_sample_names('DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_-102X_upgrade2018_realistic_v15-v2'),
                "DY2" => get_sample_names('DY2JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_-102X_upgrade2018_realistic_v15-v2'),
                "DY3" => get_sample_names('DY3JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_-102X_upgrade2018_realistic_v15-v2'),
                "DY4" => get_sample_names('DY4JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_-102X_upgrade2018_realistic_v15-v1'),
		"WW" => get_sample_names('WW_TuneCP5_13TeV-pythia8_-102X_upgrade2018_realistic_v15-v2'),
                "WZ" => get_sample_names('WZ_TuneCP5_13TeV-pythia8_-102X_upgrade2018_realistic_v15-v3'),
                "ZZ" => get_sample_names('ZZ_TuneCP5_13TeV-pythia8_-102X_upgrade2018_realistic_v15-v2'),
]


# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end
def get_plotter_results(analyzer)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
end

#task :EET => get_analyzer_results("AnalyzeEET.py", samples['DY'] + samples['DY1'] + samples['DY2'] + samples['DY3'] + samples['DY4'] + samples['WW'] + samples['WZ'] + samples['ZZ'] + samples['eraA'] + samples['eraB'] + samples['eraC'] + samples['eraD'])

task :EET => get_analyzer_results("AnalyzeEET.py", samples['DY'] + samples['DY1'] + samples['DY2'] + samples['DY3'] + samples['DY4'] + samples['WW'] + samples['WZ'] + samples['ZZ'])

$etdir = "plots/#{$jobid}/AnalyzerMuTau/mt_now/"
directory $etdir 
file  "#{$etdir}/plot#{$period}.root" do |t|
  sh "echo $jobid"
  sh "python myNewPlotterReco.py" 
  
end