# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'
require 'pathname'

$jobid = ENV['jobid']
$blind = ENV['blind']

# Figure out what run period we are in
$period = '13TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#

samples = Hash[
                "run2017Av2" => get_sample_names('data_SingleMuon_Run2017A_PromptReco-v2'),
                "run2017Av3" => get_sample_names('data_SingleMuon_Run2017A_PromptReco-v3'),
                "run2017Bv1" => get_sample_names('data_SingleMuon_Run2017B_PromptReco-v1'),
     		"run2017Bv2" => get_sample_names('data_SingleMuon_Run2017B_PromptReco-v2'),
		"run2017Cv1" => get_sample_names('data_SingleMuon_Run2017C_PromptReco-v1'),
                "run2017Cv2" => get_sample_names('data_SingleMuon_Run2017C_PromptReco-v2'),
                "run2017Cv3" => get_sample_names('data_SingleMuon_Run2017C_PromptReco-v3'),
     		"run2017Dv1" => get_sample_names('data_SingleMuon_Run2017D_PromptReco-v1'),
		"run2017Ev1" => get_sample_names('data_SingleMuon_Run2017E_PromptReco-v1')
]



# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end
def get_plotter_results(analyzer)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
end


task :MuMu => get_analyzer_results("LFVMuTauAnalyser.py", samples['run2017Av2'] + samples['run2017Av3'] + samples['run2017Bv1'] + samples['run2017Bv2'] + samples['run2017Cv1'] + samples['run2017Cv2'] + samples['run2017Cv3'] + samples['run2017Dv1'] + samples['run2017Ev1'])

$etdir = "plots/#{$jobid}/LFVMuTauAnalyzer/mt_now/"
directory $etdir 
file  "#{$etdir}/plot#{$period}.root" do |t|
  sh "echo $jobid"
  sh "python myNewPlotterReco.py" 
  
end