# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

require ENV['CMSSW_BASE'] + '/src/FinalStateAnalysis/PlotTools/rake/tools.rb'
require 'pathname'

$jobid = ENV['jobid']
$blind = ENV['blind']

# Figure out what run period we are in
$period = '13TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#$period = '8TeV'
#end

################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#

samples = Hash[
                "eraB" => get_sample_names('data_MuonEG_Run2016B'),
                "eraC" => get_sample_names('data_MuonEG_Run2016C'),
                "eraD" => get_sample_names('data_MuonEG_Run2016D'),
                "eraE" => get_sample_names('data_MuonEG_Run2016E'),
                "eraF" => get_sample_names('data_MuonEG_Run2016F'),
                "eraG" => get_sample_names('data_MuonEG_Run2016G'),
                "eraH" => get_sample_names('data_MuonEG_Run2016H'),
                "vbfHEM" => get_sample_names('VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8_v3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2'),
                "ggHEM" => get_sample_names('GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8_v3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2'),
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end
def get_plotter_results(analyzer)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
end


task :EM => get_analyzer_results("AnalyzeEMu.py", samples['eraB'] + samples['eraC'] + samples['eraD'] + samples['eraE'] + samples['eraF'] + samples['eraG'] + samples['eraH'] + samples['ggHEM'] + samples['vbfHEM'])


$etdir = "plots/#{$jobid}/AnalyzerMuTau/mt_now/"
directory $etdir
file  "#{$etdir}/plot#{$period}.root" do |t|
  sh "echo $jobid"
  sh "python myNewPlotterReco.py"

end