dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

samp = ['Zothers', 'EWK', 'ggH_htt', 'qqH_htt', 'ggH_hww', 'qqH_hww', 'vH_htt', 'TT', 'T', 'Diboson', 'LFVGG125', 'LFVVBF125']

trk = ['/embtrkUp', '/embtrkDown']

trkNames = ['ZTauTau_CMS_tracking_tauUp', 'ZTauTau_CMS_tracking_tauDown']

tauFR = ['/TauFakep0EBDM0Up', '/TauFakep0EBDM0Down', '/TauFakep0EBDM1Up', '/TauFakep0EBDM1Down', '/TauFakep0EBDM10Up', '/TauFakep0EBDM10Down', '/TauFakep0EEDM0Up', '/TauFakep0EEDM0Down', '/TauFakep0EEDM1Up', '/TauFakep0EEDM1Down', '/TauFakep0EEDM10Up', '/TauFakep0EEDM10Down', '/TauFakep1EBDM0Up', '/TauFakep1EBDM0Down', '/TauFakep1EBDM1Up', '/TauFakep1EBDM1Down', '/TauFakep1EBDM10Up', '/TauFakep1EBDM10Down', '/TauFakep1EEDM0Up', '/TauFakep1EEDM0Down', '/TauFakep1EEDM1Up', '/TauFakep1EEDM1Down', '/TauFakep1EEDM10Up', '/TauFakep1EEDM10Down']

eleFR = ['/EleFakep0EBUp', '/EleFakep0EBDown', '/EleFakep1EBUp', '/EleFakep1EBDown', '/EleFakep2EBUp', '/EleFakep2EBDown', '/EleFakep3EBUp', '/EleFakep3EBDown', '/EleFakep0EEUp', '/EleFakep0EEDown', '/EleFakep1EEUp', '/EleFakep1EEDown', '/EleFakep2EEUp', '/EleFakep2EEDown', '/EleFakep3EEUp', '/EleFakep3EEDown']

#eleFR = ['/EleFakep0EBUp', '/EleFakep0EBDown', '/EleFakep1EBUp', '/EleFakep1EBDown', '/EleFakep2EBUp', '/EleFakep2EBDown', '/EleFakep0EEUp', '/EleFakep0EEDown', '/EleFakep1EEUp', '/EleFakep1EEDown', '/EleFakep2EEUp', '/EleFakep2EEDown']

tauFRNames = ['_CMS_TauFakeRate_p0_dm0_B_13TeVUp', '_CMS_TauFakeRate_p0_dm0_B_13TeVDown', '_CMS_TauFakeRate_p0_dm1_B_13TeVUp', '_CMS_TauFakeRate_p0_dm1_B_13TeVDown', '_CMS_TauFakeRate_p0_dm10_B_13TeVUp', '_CMS_TauFakeRate_p0_dm10_B_13TeVDown', '_CMS_TauFakeRate_p0_dm0_E_13TeVUp', '_CMS_TauFakeRate_p0_dm0_E_13TeVDown', '_CMS_TauFakeRate_p0_dm1_E_13TeVUp', '_CMS_TauFakeRate_p0_dm1_E_13TeVDown', '_CMS_TauFakeRate_p0_dm10_E_13TeVUp', '_CMS_TauFakeRate_p0_dm10_E_13TeVDown', '_CMS_TauFakeRate_p1_dm0_B_13TeVUp', '_CMS_TauFakeRate_p1_dm0_B_13TeVDown', '_CMS_TauFakeRate_p1_dm1_B_13TeVUp', '_CMS_TauFakeRate_p1_dm1_B_13TeVDown', '_CMS_TauFakeRate_p1_dm10_B_13TeVUp', '_CMS_TauFakeRate_p1_dm10_B_13TeVDown', '_CMS_TauFakeRate_p1_dm0_E_13TeVUp', '_CMS_TauFakeRate_p1_dm0_E_13TeVDown', '_CMS_TauFakeRate_p1_dm1_E_13TeVUp', '_CMS_TauFakeRate_p1_dm1_E_13TeVDown', '_CMS_TauFakeRate_p1_dm10_E_13TeVUp', '_CMS_TauFakeRate_p1_dm10_E_13TeVDown']

eleFRNames = ['_CMS_EleFakeRate_p0_B_13TeVUp', '_CMS_EleFakeRate_p0_B_13TeVDown', '_CMS_EleFakeRate_p1_B_13TeVUp', '_CMS_EleFakeRate_p1_B_13TeVDown', '_CMS_EleFakeRate_p2_B_13TeVUp', '_CMS_EleFakeRate_p2_B_13TeVDown', '_CMS_EleFakeRate_p3_B_13TeVUp', '_CMS_EleFakeRate_p3_B_13TeVDown', '_CMS_EleFakeRate_p0_E_13TeVUp', '_CMS_EleFakeRate_p0_E_13TeVDown', '_CMS_EleFakeRate_p1_E_13TeVUp', '_CMS_EleFakeRate_p1_E_13TeVDown', '_CMS_EleFakeRate_p2_E_13TeVUp', '_CMS_EleFakeRate_p2_E_13TeVDown', '_CMS_EleFakeRate_p3_E_13TeVUp', '_CMS_EleFakeRate_p3_E_13TeVDown']

#eleFRNames = ['_CMS_EleFakeRate_p0_B_13TeVUp', '_CMS_EleFakeRate_p0_B_13TeVDown', '_CMS_EleFakeRate_p1_B_13TeVUp', '_CMS_EleFakeRate_p1_B_13TeVDown', '_CMS_EleFakeRate_p2_B_13TeVUp', '_CMS_EleFakeRate_p2_B_13TeVDown', '_CMS_EleFakeRate_p0_E_13TeVUp', '_CMS_EleFakeRate_p0_E_13TeVDown', '_CMS_EleFakeRate_p1_E_13TeVUp', '_CMS_EleFakeRate_p1_E_13TeVDown', '_CMS_EleFakeRate_p2_E_13TeVUp', '_CMS_EleFakeRate_p2_E_13TeVDown']

scaleSys = ['/scaletDM0Up', '/scaletDM0Down', '/scaletDM1Up', '/scaletDM1Down', '/scaletDM10Up', '/scaletDM10Down']

scaleSysNames = ['_CMS_scale_t_1prong_13TeVUp', '_CMS_scale_t_1prong_13TeVDown', '_CMS_scale_t_1prong1pizero_13TeVUp', '_CMS_scale_t_1prong1pizero_13TeVDown', '_CMS_scale_t_3prong_13TeVUp', '_CMS_scale_t_3prong_13TeVDown']

sigSys = ['/puUp', '/puDown', '/pfUp', '/pfDown', '/tidUp', '/tidDown', '/recrespUp', '/recrespDown', '/recresoUp', '/recresoDown', '/mtfakeUp', '/mtfakeDown', '/etfakeUp', '/etfakeDown', '/etefakeUp', '/etefakeDown', '/scaletDM0Up', '/scaletDM0Down', '/scaletDM1Up', '/scaletDM1Down', '/scaletDM10Up', '/scaletDM10Down', '/eesUp', '/eesDown']

sigSysNames = ['_CMS_Pileup_13TeVUp', '_CMS_Pileup_13TeVDown', '_CMS_Prefiring_13TeVUp', '_CMS_Prefiring_13TeVDown', '_CMS_eff_tauUp', '_CMS_eff_tauDown', '_CMS_RecoilResponse_13TeVUp', '_CMS_RecoilResponse_13TeVDown', '_CMS_RecoilResolution_13TeVUp', '_CMS_RecoilResolution_13TeVDown', '_CMS_scale_mfaketau_13TeVUp', '_CMS_scale_mfaketau_13TeVDown', '_CMS_scale_efaketau_13TeVUp', '_CMS_scale_efaketau_13TeVDown', '_CMS_scale_efaketaues_13TeVUp', '_CMS_scale_efaketaues_13TeVDown', '_CMS_scale_t_1prong_13TeVUp', '_CMS_scale_t_1prong_13TeVDown', '_CMS_scale_t_1prong1pizero_13TeVUp', '_CMS_scale_t_1prong1pizero_13TeVDown', '_CMS_scale_t_3prong_13TeVUp', '_CMS_scale_t_3prong_13TeVDown', '_CMS_EES_13TeVUp', '_CMS_EES_13TeVDown']

bacSys = ['/puUp', '/puDown', '/pfUp', '/pfDown', '/tidUp', '/tidDown', '/mtfakeUp', '/mtfakeDown', '/etfakeUp', '/etfakeDown', '/etefakeUp', '/etefakeDown', '/scaletDM0Up', '/scaletDM0Down', '/scaletDM1Up', '/scaletDM1Down', '/scaletDM10Up', '/scaletDM10Down', '/eesUp', '/eesDown']

bacSysNames = ['_CMS_Pileup_13TeVUp', '_CMS_Pileup_13TeVDown', '_CMS_Prefiring_13TeVUp', '_CMS_Prefiring_13TeVDown', '_CMS_eff_tauUp', '_CMS_eff_tauDown', '_CMS_scale_mfaketau_13TeVUp', '_CMS_scale_mfaketau_13TeVDown', '_CMS_scale_efaketau_13TeVUp', '_CMS_scale_efaketau_13TeVDown', '_CMS_scale_efaketaues_13TeVUp', '_CMS_scale_efaketaues_13TeVDown', '_CMS_scale_t_1prong_13TeVUp', '_CMS_scale_t_1prong_13TeVDown', '_CMS_scale_t_1prong1pizero_13TeVUp', '_CMS_scale_t_1prong1pizero_13TeVDown', '_CMS_scale_t_3prong_13TeVUp', '_CMS_scale_t_3prong_13TeVDown', '_CMS_EES_13TeVUp', '_CMS_EES_13TeVDown']

recSys = ['/recrespUp', '/recrespDown', '/recresoUp', '/recresoDown']

recSysNames = ['_CMS_RecoilResponse_13TeVUp', '_CMS_RecoilResponse_13TeVDown', '_CMS_RecoilResolution_13TeVUp', '_CMS_RecoilResolution_13TeVDown']

dyptSys = ['/DYptreweightUp', '/DYptreweightDown']

dyptSysNames = ['_CMS_DYpTreweight_13TeVUp', '_CMS_DYpTreweight_13TeVDown']

ttSys = ['/TopptreweightUp', '/TopptreweightDown']

ttSysNames = ['_CMS_TTpTreweight_13TeVUp', '_CMS_TTpTreweight_13TeVDown']

jesSys = ['/UnclusteredEnUp', '/UnclusteredEnDown', '/JetAbsoluteFlavMapUp', '/JetAbsoluteFlavMapDown', '/JetAbsoluteMPFBiasUp', '/JetAbsoluteMPFBiasDown', '/JetAbsoluteScaleUp', '/JetAbsoluteScaleDown', '/JetAbsoluteStatUp', '/JetAbsoluteStatDown', '/JetFlavorQCDUp', '/JetFlavorQCDDown', '/JetFragmentationUp', '/JetFragmentationDown', '/JetPileUpDataMCUp', '/JetPileUpDataMCDown', '/JetPileUpPtBBUp', '/JetPileUpPtBBDown', '/JetPileUpPtEC1Up', '/JetPileUpPtEC1Down', '/JetPileUpPtEC2Up', '/JetPileUpPtEC2Down', '/JetPileUpPtHFUp', '/JetPileUpPtHFDown', '/JetPileUpPtRefUp', '/JetPileUpPtRefDown', '/JetRelativeFSRUp', '/JetRelativeFSRDown', '/JetRelativeJEREC1Up', '/JetRelativeJEREC1Down', '/JetRelativeJEREC2Up', '/JetRelativeJEREC2Down', '/JetRelativeJERHFUp', '/JetRelativeJERHFDown', '/JetRelativePtBBUp', '/JetRelativePtBBDown', '/JetRelativePtEC1Up', '/JetRelativePtEC1Down', '/JetRelativePtEC2Up', '/JetRelativePtEC2Down', '/JetRelativePtHFUp', '/JetRelativePtHFDown', '/JetRelativeStatECUp', '/JetRelativeStatECDown', '/JetRelativeStatFSRUp', '/JetRelativeStatFSRDown', '/JetRelativeStatHFUp', '/JetRelativeStatHFDown', '/JetSinglePionECALUp', '/JetSinglePionECALDown', '/JetSinglePionHCALUp', '/JetSinglePionHCALDown', '/JetTimePtEtaUp', '/JetTimePtEtaDown', '/JetRelativeBalUp', '/JetRelativeBalDown', '/JetRelativeSampleUp', '/JetRelativeSampleDown']

jesSysNames = ['_CMS_MET_Ues_13TeVUp', '_CMS_MET_Ues_13TeVDown', '_CMS_Jes_JetAbsoluteFlavMap_13TeVUp', '_CMS_Jes_JetAbsoluteFlavMap_13TeVDown', '_CMS_Jes_JetAbsoluteMPFBias_13TeVUp', '_CMS_Jes_JetAbsoluteMPFBias_13TeVDown', '_CMS_Jes_JetAbsoluteScale_13TeVUp', '_CMS_Jes_JetAbsoluteScale_13TeVDown', '_CMS_Jes_JetAbsoluteStat_13TeVUp', '_CMS_Jes_JetAbsoluteStat_13TeVDown', '_CMS_Jes_JetFlavorQCD_13TeVUp', '_CMS_Jes_JetFlavorQCD_13TeVDown', '_CMS_Jes_JetFragmentation_13TeVUp', '_CMS_Jes_JetFragmentation_13TeVDown', '_CMS_Jes_JetPileUpDataMC_13TeVUp', '_CMS_Jes_JetPileUpDataMC_13TeVDown', '_CMS_Jes_JetPileUpPtBB_13TeVUp', '_CMS_Jes_JetPileUpPtBB_13TeVDown', '_CMS_Jes_JetPileUpPtEC1_13TeVUp', '_CMS_Jes_JetPileUpPtEC1_13TeVDown', '_CMS_Jes_JetPileUpPtEC2_13TeVUp', '_CMS_Jes_JetPileUpPtEC2_13TeVDown', '_CMS_Jes_JetPileUpPtHF_13TeVUp', '_CMS_Jes_JetPileUpPtHF_13TeVDown', '_CMS_Jes_JetPileUpPtRef_13TeVUp', '_CMS_Jes_JetPileUpPtRef_13TeVDown', '_CMS_Jes_JetRelativeFSR_13TeVUp', '_CMS_Jes_JetRelativeFSR_13TeVDown', '_CMS_Jes_JetRelativeJEREC1_13TeVUp', '_CMS_Jes_JetRelativeJEREC1_13TeVDown', '_CMS_Jes_JetRelativeJEREC2_13TeVUp', '_CMS_Jes_JetRelativeJEREC2_13TeVDown', '_CMS_Jes_JetRelativeJERHF_13TeVUp', '_CMS_Jes_JetRelativeJERHF_13TeVDown', '_CMS_Jes_JetRelativePtBB_13TeVUp', '_CMS_Jes_JetRelativePtBB_13TeVDown', '_CMS_Jes_JetRelativePtEC1_13TeVUp', '_CMS_Jes_JetRelativePtEC1_13TeVDown', '_CMS_Jes_JetRelativePtEC2_13TeVUp', '_CMS_Jes_JetRelativePtEC2_13TeVDown', '_CMS_Jes_JetRelativePtHF_13TeVUp', '_CMS_Jes_JetRelativePtHF_13TeVDown', '_CMS_Jes_JetRelativeStatEC_13TeVUp', '_CMS_Jes_JetRelativeStatEC_13TeVDown', '_CMS_Jes_JetRelativeStatFSR_13TeVUp', '_CMS_Jes_JetRelativeStatFSR_13TeVDown', '_CMS_Jes_JetRelativeStatHF_13TeVUp', '_CMS_Jes_JetRelativeStatHF_13TeVDown', '_CMS_Jes_JetSinglePionECAL_13TeVUp', '_CMS_Jes_JetSinglePionECAL_13TeVDown', '_CMS_Jes_JetSinglePionHCAL_13TeVUp', '_CMS_Jes_JetSinglePionHCAL_13TeVDown', '_CMS_Jes_JetTimePtEta_13TeVUp', '_CMS_Jes_JetTimePtEta_13TeVDown', '_CMS_Jes_JetRelativeBal_13TeVUp', '_CMS_Jes_JetRelativeBal_13TeVDown', '_CMS_Jes_JetRelativeSample_13TeVUp', '_CMS_Jes_JetRelativeSample_13TeVDown']
