import rootpy.plotting.views as views
from FinalStateAnalysis.PlotTools.Plotter import Plotter
from FinalStateAnalysis.PlotTools.BlindView      import BlindView
from FinalStateAnalysis.PlotTools.PoissonView    import PoissonView
from FinalStateAnalysis.PlotTools.MedianView     import MedianView
from FinalStateAnalysis.PlotTools.ProjectionView import ProjectionView
from FinalStateAnalysis.PlotTools.RebinView  import RebinView
from FinalStateAnalysis.MetaData.data_styles import data_styles, colors
from FinalStateAnalysis.PlotTools.decorators import memo
from FinalStateAnalysis.MetaData.datacommon  import br_w_leptons, br_z_leptons
from FinalStateAnalysis.PlotTools.SubtractionView      import SubtractionView, PositiveView
from optparse import OptionParser
import os
import itertools
import ROOT
import glob
import math
import logging
import pdb
import array
from fnmatch import fnmatch
from yellowhiggs import xs, br, xsbr
from BasePlotter import BasePlotter
from argparse import ArgumentParser

ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
jobid = os.environ['jobid']
files = []
lumifiles = []
channel = 'et'
period = '13TeV'
sqrts = 13

def positivize(histogram):
    output = histogram.Clone()
    for i in range(output.GetSize()):
        if output.GetArray()[i] < 0:
            output.AddAt(0, i)
    return output

mc_samples = ['DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM*', 'DYJetsToLL_M-10to50*', 'DY1JetsToLL*', 'DY2JetsToLL*', 'DY3JetsToLL*', 'DY4JetsToLL*', 'GluGlu_LFV*', 'VBF_LFV*', 'GluGluHToTauTau*', 'VBFHToTauTau*', 'GluGluHToWW*', 'VBFHToWW*', 'WminusHToTauTau*', 'WplusHToTauTau*', 'ttHToTauTau*', 'ZHToTauTau*', 'TTTo2L2Nu*', 'TTToSemiLeptonic*', 'TTToHadronic*', 'ST_tW_antitop*', 'ST_tW_top*', 'ST_t-channel_antitop*', 'ST_t-channel_top*', 'QCD*', 'WZ*', 'WW*', 'ZZ*', 'EWKWMinus2Jets*', 'EWKWPlus2Jets*', 'EWKZ2Jets_ZToLL*', 'EWKZ2Jets_ZToNuNu*', 'embed*', 'data*']

for x in mc_samples:
    files.extend(glob.glob('../results/%s/AnalyzeETauSys/%s.root' % (jobid, x)))
    lumifiles.extend(glob.glob('../inputs/%s/%s.lumicalc.sum' % (jobid, x)))

outputdir = '../plots/%s/AnalyzeETauSys/' % (jobid)
if not os.path.exists(outputdir):
    os.makedirs(outputdir)

plotter = Plotter(files, lumifiles, outputdir)

f = ROOT.TFile( 'Shapes/shapesETau.root', 'RECREATE')

dirs = ['0Jet', '1Jet', '2Jet', '2JetVBF']

v = [
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('DY1') or x.startswith('DY2') or x.startswith('DY3') or x.startswith('DY4') or x.startswith('DYJetsToLL_M-50') or x.startswith('DYJetsToLL_M-10to50'), mc_samples )]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('EWK') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGluHToTauTau') or x.startswith('GluGluHToWW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBFHToTauTau') or x.startswith('VBFHToWW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('WminusHToTauTau') or x.startswith('WplusHToTauTau') or x.startswith('ZHToTauTau') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('TT'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ST'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('ZZ') or x.startswith('WZ') or x.startswith('WW'), mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('GluGlu_LFV') , mc_samples)]),
views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('VBF_LFV') , mc_samples)])
]

b = ['Zll', 'EWK', 'GluGluH', 'VBFH', 'VH', 'TT', 'ST', 'EWKDiboson', 'GluGlu125', 'VBF125']

for di in dirs:

    if di=='0Jet' or di=='1Jet':
        binning = array.array('d', (range(0, 100, 25) + range(100, 200, 10) + range(200, 300, 25)))
    else:
        binning = array.array('d', (range(0, 300, 25)))

    d = f.mkdir(di)
    d.cd()
    DataTotal = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    data = DataTotal.Get('TightOS'+di+'/e_t_CollinearMass')
    data = data.Rebin(len(binning)-1, 'data_obs', binning)

    embed = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('embed'), mc_samples)])
    emball = embed.Get('TightOS'+di+'/e_t_CollinearMass')
    embtfakes = embed.Get('TauLooseOS'+di+'/e_t_CollinearMass')
    embefakes = embed.Get('EleLooseOS'+di+'/e_t_CollinearMass')
    embetfakes = embed.Get('EleLooseTauLooseOS'+di+'/e_t_CollinearMass')
    embfakes = embtfakes.Clone()
    embfakes.Add(embefakes)
    embfakes.Add(embetfakes, -1)
    embfakes = positivize(embfakes)
    emb = emball.Clone()
    emb.Add(embfakes, -1)
    emb = positivize(emb)
    emb = emb.Rebin(len(binning)-1, 'embed', binning)

    embtrkup = embed.Get('TightOS'+di+'/embtrkUp/e_t_CollinearMass')
    embtrkup.Add(embfakes, -1)
    embtrkup = positivize(embtrkup)
    embtrkup = embtrkup.Rebin(len(binning)-1, 'embed_CMS_tracking_tauUp', binning)
    embtrkdown = embed.Get('TightOS'+di+'/embtrkDown/e_t_CollinearMass')
    embtrkdown.Add(embfakes, -1)
    embtrkdown = positivize(embtrkdown)
    embtrkdown = embtrkdown.Rebin(len(binning)-1, 'embed_CMS_tracking_tauDown', binning)

    embtes0up = embed.Get('TightOS'+di+'/scaletDM0Up/e_t_CollinearMass')
    embtes0up.Add(embfakes, -1)
    embtes0up = positivize(embtes0up)
    embtes0up = embtes0up.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong_13TeVUp', binning)
    embtes0down = embed.Get('TightOS'+di+'/scaletDM0Down/e_t_CollinearMass')
    embtes0down.Add(embfakes, -1)
    embtes0down = positivize(embtes0down)
    embtes0down = embtes0down.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong_13TeVDown', binning)

    embtes1up = embed.Get('TightOS'+di+'/scaletDM1Up/e_t_CollinearMass')
    embtes1up.Add(embfakes, -1)
    embtes1up = positivize(embtes1up)
    embtes1up = embtes1up.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong1pizero_13TeVUp', binning)
    embtes1down = embed.Get('TightOS'+di+'/scaletDM1Down/e_t_CollinearMass')
    embtes1down.Add(embfakes, -1)
    embtes1down = positivize(embtes1down)
    embtes1down = embtes1down.Rebin(len(binning)-1, 'embed_CMS_scale_t_1prong1pizero_13TeVDown', binning)

    embtes10up = embed.Get('TightOS'+di+'/scaletDM10Up/e_t_CollinearMass')
    embtes10up.Add(embfakes, -1)
    embtes10up = positivize(embtes10up)
    embtes10up = embtes10up.Rebin(len(binning)-1, 'embed_CMS_scale_t_3prong_13TeVUp', binning)
    embtes10down = embed.Get('TightOS'+di+'/scaletDM10Down/e_t_CollinearMass')
    embtes10down.Add(embfakes, -1)
    embtes10down = positivize(embtes10down)
    embtes10down = embtes10down.Rebin(len(binning)-1, 'embed_CMS_scale_t_3prong_13TeVDown', binning)

    embtb0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
    embtb0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
    embtb1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
    embtb1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
    embtb10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
    embtb10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
    embte0fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
    embte0fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
    embte1fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
    embte1fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
    embte10fakesup = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
    embte10fakesdown = embed.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
    embefakesup = embed.Get('EleLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
    embefakesdown = embed.Get('EleLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
    embettb0fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
    embettb0fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
    embettb1fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
    embettb1fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
    embettb10fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
    embettb10fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
    embette0fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
    embette0fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
    embette1fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
    embette1fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
    embette10fakesup = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
    embette10fakesdown = embed.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
    embetefakesup = embed.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
    embetefakesdown = embed.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
    emb1b0 = emball.Clone()
    emb1tb0 = embtb0fakesup.Clone()
    emb1tb0.add(embefakes)
    emb1tb0.add(embettb0fakesup, -1)
    emb1tb0 = positivize(emb1tb0)
    emb1b0.add(emb1tb0, -1)
    emb1b0 = positivize(emb1b0)
    emb1b0 = emb1b0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
    emb2b0 = emball.Clone()
    emb2tb0 = embtb0fakesdown.Clone()
    emb2tb0.add(embefakes)
    emb2tb0.add(embettb0fakesdown, -1)
    emb2tb0 = positivize(emb2tb0)
    emb2b0.add(emb2tb0, -1)
    emb2b0 = positivize(emb2b0)
    emb2b0 = emb2b0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
    emb1b1 = emball.Clone()
    emb1tb1 = embtb1fakesup.Clone()
    emb1tb1.add(embefakes)
    emb1tb1.add(embettb1fakesup, -1)
    emb1tb1 = positivize(emb1tb1)
    emb1b1.add(emb1tb1, -1)
    emb1b1 = positivize(emb1b1)
    emb1b1 = emb1b1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
    emb2b1 = emball.Clone()
    emb2tb1 = embtb1fakesdown.Clone()
    emb2tb1.add(embefakes)
    emb2tb1.add(embettb1fakesdown, -1)
    emb2tb1 = positivize(emb2tb1)
    emb2b1.add(emb2tb1, -1)
    emb2b1 = positivize(emb2b1)
    emb2b1 = emb2b1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
    emb1b10 = emball.Clone()
    emb1tb10 = embtb10fakesup.Clone()
    emb1tb10.add(embefakes)
    emb1tb10.add(embettb10fakesup, -1)
    emb1tb10 = positivize(emb1tb10)
    emb1b10.add(emb1tb10, -1)
    emb1b10 = positivize(emb1b10)
    emb1b10 = emb1b10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
    emb2b10 = emball.Clone()
    emb2tb10 = embtb10fakesdown.Clone()
    emb2tb10.add(embefakes)
    emb2tb10.add(embettb10fakesdown, -1)
    emb2tb10 = positivize(emb2tb10)
    emb2b10.add(emb2tb10, -1)
    emb2b10 = positivize(emb2b10)
    emb2b10 = emb2b10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
    emb1e0 = emball.Clone()
    emb1te0 = embte0fakesup.Clone()
    emb1te0.add(embefakes)
    emb1te0.add(embette0fakesup, -1)
    emb1te0 = positivize(emb1te0)
    emb1e0.add(emb1te0, -1)
    emb1e0 = positivize(emb1e0)
    emb1e0 = emb1e0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
    emb2e0 = emball.Clone()
    emb2te0 = embte0fakesdown.Clone()
    emb2te0.add(embefakes)
    emb2te0.add(embette0fakesdown, -1)
    emb2te0 = positivize(emb2te0)
    emb2e0.add(emb2te0, -1)
    emb2e0 = positivize(emb2e0)
    emb2e0 = emb2e0.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
    emb1e1 = emball.Clone()
    emb1te1 = embte1fakesup.Clone()
    emb1te1.add(embefakes)
    emb1te1.add(embette1fakesup, -1)
    emb1te1 = positivize(emb1te1)
    emb1e1.add(emb1te1, -1)
    emb1e1 = positivize(emb1e1)
    emb1e1 = emb1e1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
    emb2e1 = emball.Clone()
    emb2te1 = embte1fakesdown.Clone()
    emb2te1.add(embefakes)
    emb2te1.add(embette1fakesdown, -1)
    emb2te1 = positivize(emb2te1)
    emb2e1.add(emb2te1, -1)
    emb2e1 = positivize(emb2e1)
    emb2e1 = emb2e1.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
    emb1e10 = emball.Clone()
    emb1te10 = embte10fakesup.Clone()
    emb1te10.add(embefakes)
    emb1te10.add(embette10fakesup, -1)
    emb1te10 = positivize(emb1te10)
    emb1e10.add(emb1te10, -1)
    emb1e10 = positivize(emb1e10)
    emb1e10 = emb1e10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
    emb2e10 = emball.Clone()
    emb2te10 = embte10fakesdown.Clone()
    emb2te10.add(embefakes)
    emb2te10.add(embette10fakesdown, -1)
    emb2te10 = positivize(emb2te10)
    emb2e10.add(emb2te10, -1)
    emb2e10 = positivize(emb2e10)
    emb2e10 = emb2e10.Rebin(len(binning)-1, 'embed_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
    emb3 = emball.Clone()
    emb3t = embtfakes.Clone()
    emb3t.add(embefakesup)
    emb3t.add(embetefakesup, -1)
    emb3t = positivize(emb3t)
    emb3.add(emb3t, -1)
    emb3 = positivize(emb3)
    emb3 = emb3.Rebin(len(binning)-1, 'embed_CMS_EleFakeRate_13TeVUp', binning)
    emb4 = emball.Clone()
    emb4t = embtfakes.Clone()
    emb4t.add(embefakesdown)
    emb4t.add(embetefakesdown, -1)
    emb4t = positivize(emb4t)
    emb4.add(emb4t, -1)
    emb4 = positivize(emb4)
    emb4 = emb4.Rebin(len(binning)-1, 'embed_CMS_EleFakeRate_13TeVDown', binning)
    emball.Delete()
    emb1tb0.Delete()
    emb2tb0.Delete()
    emb1tb1.Delete()
    emb2tb1.Delete()
    emb1tb10.Delete()
    emb2tb10.Delete()
    emb1te0.Delete()
    emb2te0.Delete()
    emb1te1.Delete()
    emb2te1.Delete()
    emb1te10.Delete()
    emb2te10.Delete()
    emb3t.Delete()
    emb4t.Delete()
    embfakes.Delete()
    embtfakes.Delete()
    embefakes.Delete()
    embetfakes.Delete()
    embte0fakesup.Delete()
    embte0fakesdown.Delete()
    embte1fakesup.Delete()
    embte1fakesdown.Delete()
    embte10fakesup.Delete()
    embte10fakesdown.Delete()
    embtb0fakesup.Delete()
    embtb0fakesdown.Delete()
    embtb1fakesup.Delete()
    embtb1fakesdown.Delete()
    embtb10fakesup.Delete()
    embtb10fakesdown.Delete()
    embefakesup.Delete()
    embefakesdown.Delete()
    embette0fakesup.Delete()
    embette0fakesdown.Delete()
    embette1fakesup.Delete()
    embette1fakesdown.Delete()
    embette10fakesup.Delete()
    embette10fakesdown.Delete()
    embettb0fakesup.Delete()
    embettb0fakesdown.Delete()
    embettb1fakesup.Delete()
    embettb1fakesdown.Delete()
    embettb10fakesup.Delete()
    embettb10fakesdown.Delete()
    embetefakesup.Delete()
    embetefakesdown.Delete()

    QCD = views.SumView( *[ plotter.get_view(regex) for regex in filter(lambda x : x.startswith('QCD'), mc_samples)])
    tfakes = QCD.Get('TauLooseOS'+di+'/e_t_CollinearMass')
    efakes = QCD.Get('EleLooseOS'+di+'/e_t_CollinearMass')
    etfakes = QCD.Get('EleLooseTauLooseOS'+di+'/e_t_CollinearMass')
    qcd = tfakes.Clone()
    qcd.Add(efakes)
    qcd.Add(etfakes, -1)
    qcd = positivize(qcd)
    qcd = qcd.Rebin(len(binning)-1, 'Fakes', binning)
    te0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
    te0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
    te1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
    te1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
    te10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
    te10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
    tb0fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
    tb0fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
    tb1fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
    tb1fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
    tb10fakesup = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
    tb10fakesdown = QCD.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
    efakesup = QCD.Get('EleLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
    efakesdown = QCD.Get('EleLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
    ette0fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
    ette0fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
    ette1fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
    ette1fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
    ette10fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
    ette10fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
    ettb0fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
    ettb0fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
    ettb1fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
    ettb1fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
    ettb10fakesup = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
    ettb10fakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
    etefakesup = QCD.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
    etefakesdown = QCD.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
    f1e0 = te0fakesup.Clone()
    f1e0.add(efakes)
    f1e0.add(ette0fakesup, -1)
    f1e0 = positivize(f1e0)
    f1e0 = f1e0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
    f2e0 = te0fakesdown.Clone()
    f2e0.add(efakes)
    f2e0.add(ette0fakesdown, -1)
    f2e0 = positivize(f2e0)
    f2e0 = f2e0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
    f1e1 = te1fakesup.Clone()
    f1e1.add(efakes)
    f1e1.add(ette1fakesup, -1)
    f1e1 = positivize(f1e1)
    f1e1 = f1e1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
    f2e1 = te1fakesdown.Clone()
    f2e1.add(efakes)
    f2e1.add(ette1fakesdown, -1)
    f2e1 = positivize(f2e1)
    f2e1 = f2e1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
    f1e10 = te10fakesup.Clone()
    f1e10.add(efakes)
    f1e10.add(ette10fakesup, -1)
    f1e10 = positivize(f1e10)
    f1e10 = f1e10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
    f2e10 = te10fakesdown.Clone()
    f2e10.add(efakes)
    f2e10.add(ette10fakesdown, -1)
    f2e10 = positivize(f2e10)
    f2e10 = f2e10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
    f1b0 = tb0fakesup.Clone()
    f1b0.add(efakes)
    f1b0.add(ettb0fakesup, -1)
    f1b0 = positivize(f1b0)
    f1b0 = f1b0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
    f2b0 = tb0fakesdown.Clone()
    f2b0.add(efakes)
    f2b0.add(ettb0fakesdown, -1)
    f2b0 = positivize(f2b0)
    f2b0 = f2b0.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
    f1b1 = tb1fakesup.Clone()
    f1b1.add(efakes)
    f1b1.add(ettb1fakesup, -1)
    f1b1 = positivize(f1b1)
    f1b1 = f1b1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
    f2b1 = tb1fakesdown.Clone()
    f2b1.add(efakes)
    f2b1.add(ettb1fakesdown, -1)
    f2b1 = positivize(f2b1)
    f2b1 = f2b1.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
    f1b10 = tb10fakesup.Clone()
    f1b10.add(efakes)
    f1b10.add(ettb10fakesup, -1)
    f1b10 = positivize(f1b10)
    f1b10 = f1b10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
    f2b10 = tb10fakesdown.Clone()
    f2b10.add(efakes)
    f2b10.add(ettb10fakesdown, -1)
    f2b10 = positivize(f2b10)
    f2b10 = f2b10.Rebin(len(binning)-1, 'Fakes_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
    f3 = tfakes.Clone()
    f3.add(efakesup)
    f3.add(etefakesup, -1)
    f3 = positivize(f3)
    f3 = f3.Rebin(len(binning)-1, 'Fakes_CMS_EleFakeRate_13TeVUp', binning)
    f4 = tfakes.Clone()
    f4.add(efakesdown)
    f4.add(etefakesdown, -1)
    f4 = positivize(f4)
    f4 = f4.Rebin(len(binning)-1, 'Fakes_CMS_EleFakeRate_13TeVDown', binning)
    tfakes.Delete()
    efakes.Delete()
    etfakes.Delete()
    te0fakesup.Delete()
    te0fakesdown.Delete()
    te1fakesup.Delete()
    te1fakesdown.Delete()
    te10fakesup.Delete()
    te10fakesdown.Delete()
    tb0fakesup.Delete()
    tb0fakesdown.Delete()
    tb1fakesup.Delete()
    tb1fakesdown.Delete()
    tb10fakesup.Delete()
    tb10fakesdown.Delete()
    efakesup.Delete()
    efakesdown.Delete()
    ette0fakesup.Delete()
    ette0fakesdown.Delete()
    ette1fakesup.Delete()
    ette1fakesdown.Delete()
    ette10fakesup.Delete()
    ette10fakesdown.Delete()
    ettb0fakesup.Delete()
    ettb0fakesdown.Delete()
    ettb1fakesup.Delete()
    ettb1fakesdown.Delete()
    ettb10fakesup.Delete()
    ettb10fakesdown.Delete()
    etefakesup.Delete()
    etefakesdown.Delete()

    for i in range(10):
        DY = v[i]
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy = DY.Get('TightOS'+di+'/e_t_CollinearMass')
            dy = dy.Rebin(len(binning)-1, b[i], binning)

            dypuup = DY.Get('TightOS'+di+'/puUp/e_t_CollinearMass')
            dypuup = dypuup.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVUp', binning)
            dypudown = DY.Get('TightOS'+di+'/puDown/e_t_CollinearMass')
            dypudown = dypudown.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVDown', binning)

            dypfup = DY.Get('TightOS'+di+'/pfUp/e_t_CollinearMass')
            dypfup = dypfup.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVUp', binning)
            dypfdown = DY.Get('TightOS'+di+'/pfDown/e_t_CollinearMass')
            dypfdown = dypfdown.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVDown', binning)

            dytidup = DY.Get('TightOS'+di+'/tidUp/e_t_CollinearMass')
            dytidup = dytidup.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauUp', binning)
            dytiddown = DY.Get('TightOS'+di+'/tidDown/e_t_CollinearMass')
            dytiddown = dytiddown.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauDown', binning)

            dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/e_t_CollinearMass')
            dyrecrespup = dyrecrespup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVUp', binning)
            dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/e_t_CollinearMass')
            dyrecrespdown = dyrecrespdown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVDown', binning)

            dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/e_t_CollinearMass')
            dyrecresoup = dyrecresoup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVUp', binning)
            dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/e_t_CollinearMass')
            dyrecresodown = dyrecresodown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVDown', binning)

            dymtfakeup = DY.Get('TightOS'+di+'/etfakeUp/e_t_CollinearMass')
            dymtfakeup = dymtfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVUp', binning)
            dymtfakedown = DY.Get('TightOS'+di+'/etfakeDown/e_t_CollinearMass')
            dymtfakedown = dymtfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVDown', binning)

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/e_t_CollinearMass')
            dyetfakeup = dyetfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVUp', binning)
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/e_t_CollinearMass')
            dyetfakedown = dyetfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVDown', binning)

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/e_t_CollinearMass')
            dyetefakeup = dyetefakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVUp', binning)
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/e_t_CollinearMass')
            dyetefakedown = dyetefakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVDown', binning)

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/e_t_CollinearMass')
            dytes0up = dytes0up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVUp', binning)
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/e_t_CollinearMass')
            dytes0down = dytes0down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVDown', binning)

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/e_t_CollinearMass')
            dytes1up = dytes1up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp', binning)
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/e_t_CollinearMass')
            dytes1down = dytes1down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown', binning)

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/e_t_CollinearMass')
            dytes10up = dytes10up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVUp', binning)
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/e_t_CollinearMass')
            dytes10down = dytes10down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVDown', binning)

            #Electron Energy Scale
            dyeescup = DY.Get('TightOS'+di+'/eescUp/e_t_CollinearMass')
            dyeescup = dyeescup.Rebin(len(binning)-1, b[i]+'_CMS_EEScale_13TeVUp', binning)
            dyeescdown = DY.Get('TightOS'+di+'/eescDown/e_t_CollinearMass')
            dyeescdown = dyeescdown.Rebin(len(binning)-1, b[i]+'_CMS_EEScale_13TeVDown', binning)

            #Electron Energy Sigma
            dyeesiup = DY.Get('TightOS'+di+'/eesiUp/e_t_CollinearMass')
            dyeesiup = dyeesiup.Rebin(len(binning)-1, b[i]+'_CMS_EESigma_13TeVUp', binning)
            dyeesidown = DY.Get('TightOS'+di+'/eesiDown/e_t_CollinearMass')
            dyeesidown = dyeesidown.Rebin(len(binning)-1, b[i]+'_CMS_EESigma_13TeVDown', binning)

        else:
            dyall = DY.Get('TightOS'+di+'/e_t_CollinearMass')
            dytfakes = DY.Get('TauLooseOS'+di+'/e_t_CollinearMass')
            dyefakes = DY.Get('EleLooseOS'+di+'/e_t_CollinearMass')
            dyetfakes = DY.Get('EleLooseTauLooseOS'+di+'/e_t_CollinearMass')
            dyfakes = dytfakes.Clone()
            dyfakes.Add(dyefakes)
            dyfakes.Add(dyetfakes, -1)
            dyfakes = positivize(dyfakes)
            dyall.Add(dyfakes, -1)
            dy = positivize(dyall)
            dy = dy.Rebin(len(binning)-1, b[i], binning)

            dypuup = DY.Get('TightOS'+di+'/puUp/e_t_CollinearMass')
            dypuup.Add(dyfakes, -1)
            dypuup = positivize(dypuup)
            dypuup = dypuup.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVUp', binning)
            dypudown = DY.Get('TightOS'+di+'/puDown/e_t_CollinearMass')
            dypudown.Add(dyfakes, -1)
            dypudown = positivize(dypudown)
            dypudown = dypudown.Rebin(len(binning)-1, b[i]+'_CMS_Pileup_13TeVDown', binning)

            dypfup = DY.Get('TightOS'+di+'/pfUp/e_t_CollinearMass')
            dypfup.Add(dyfakes, -1)
            dypfup = positivize(dypfup)
            dypfup = dypfup.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVUp', binning)
            dypfdown = DY.Get('TightOS'+di+'/pfDown/e_t_CollinearMass')
            dypfdown.Add(dyfakes, -1)
            dypfdown = positivize(dypfdown)
            dypfdown = dypfdown.Rebin(len(binning)-1, b[i]+'_CMS_Prefiring_13TeVDown', binning)

            dytidup = DY.Get('TightOS'+di+'/tidUp/e_t_CollinearMass')
            dytidup.Add(dyfakes, -1)
            dytidup = positivize(dytidup)
            dytidup = dytidup.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauUp', binning)
            dytiddown = DY.Get('TightOS'+di+'/tidDown/e_t_CollinearMass')
            dytiddown.Add(dyfakes, -1)
            dytiddown = positivize(dytiddown)
            dytiddown = dytiddown.Rebin(len(binning)-1, b[i]+'_CMS_eff_tauDown', binning)

            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup = DY.Get('TightOS'+di+'/recrespUp/e_t_CollinearMass')
                dyrecrespup.Add(dyfakes, -1)
                dyrecrespup = positivize(dyrecrespup)
                dyrecrespup = dyrecrespup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVUp', binning)
                dyrecrespdown = DY.Get('TightOS'+di+'/recrespDown/e_t_CollinearMass')
                dyrecrespdown.Add(dyfakes, -1)
                dyrecrespdown = positivize(dyrecrespdown)
                dyrecrespdown = dyrecrespdown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResponse_13TeVDown', binning)

                dyrecresoup = DY.Get('TightOS'+di+'/recresoUp/e_t_CollinearMass')
                dyrecresoup.Add(dyfakes, -1)
                dyrecresoup = positivize(dyrecresoup)
                dyrecresoup = dyrecresoup.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVUp', binning)
                dyrecresodown = DY.Get('TightOS'+di+'/recresoDown/e_t_CollinearMass')
                dyrecresodown.Add(dyfakes, -1)
                dyrecresodown = positivize(dyrecresodown)
                dyrecresodown = dyrecresodown.Rebin(len(binning)-1, b[i]+'_CMS_RecoilResolution_13TeVDown', binning)

            if b[i]=='Zll':
                dyptup = DY.Get('TightOS'+di+'/DYptreweightUp/e_t_CollinearMass')
                dyptup.Add(dyfakes, -1)
                dyptup = positivize(dyptup)
                dyptup = dyptup.Rebin(len(binning)-1, b[i]+'_CMS_DYpTreweight_13TeVUp', binning)
                dyptdown = DY.Get('TightOS'+di+'/DYptreweightDown/e_t_CollinearMass')
                dyptdown.Add(dyfakes, -1)
                dyptdown = positivize(dyptdown)
                dyptdown = dyptdown.Rebin(len(binning)-1, b[i]+'_CMS_DYpTreweight_13TeVDown', binning)

            if b[i]=='TT':
                dytptup = DY.Get('TightOS'+di+'/TopptreweightUp/e_t_CollinearMass')
                dytptup.Add(dyfakes, -1)
                dytptup = positivize(dytptup)
                dytptup = dytptup.Rebin(len(binning)-1, b[i]+'_CMS_ToppTreweight_13TeVUp', binning)
                dytptdown = DY.Get('TightOS'+di+'/TopptreweightDown/e_t_CollinearMass')
                dytptdown.Add(dyfakes, -1)
                dytptdown = positivize(dytptdown)
                dytptdown = dytptdown.Rebin(len(binning)-1, b[i]+'_CMS_ToppTreweight_13TeVDown', binning)

            dymtfakeup = DY.Get('TightOS'+di+'/etfakeUp/e_t_CollinearMass')
            dymtfakeup.Add(dyfakes, -1)
            dymtfakeup = positivize(dymtfakeup)
            dymtfakeup = dymtfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVUp', binning)
            dymtfakedown = DY.Get('TightOS'+di+'/etfakeDown/e_t_CollinearMass')
            dymtfakedown.Add(dyfakes, -1)
            dymtfakedown = positivize(dymtfakedown)
            dymtfakedown = dymtfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_mfaketau_13TeVDown', binning)

            dyetfakeup = DY.Get('TightOS'+di+'/etfakeUp/e_t_CollinearMass')
            dyetfakeup.Add(dyfakes, -1)
            dyetfakeup = positivize(dyetfakeup)
            dyetfakeup = dyetfakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVUp', binning)
            dyetfakedown = DY.Get('TightOS'+di+'/etfakeDown/e_t_CollinearMass')
            dyetfakedown.Add(dyfakes, -1)
            dyetfakedown = positivize(dyetfakedown)
            dyetfakedown = dyetfakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketau_13TeVDown', binning)

            dyetefakeup = DY.Get('TightOS'+di+'/etefakeUp/e_t_CollinearMass')
            dyetefakeup.Add(dyfakes, -1)
            dyetefakeup = positivize(dyetefakeup)
            dyetefakeup = dyetefakeup.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVUp', binning)
            dyetefakedown = DY.Get('TightOS'+di+'/etefakeDown/e_t_CollinearMass')
            dyetefakedown.Add(dyfakes, -1)
            dyetefakedown = positivize(dyetefakedown)
            dyetefakedown = dyetefakedown.Rebin(len(binning)-1, b[i]+'_CMS_scale_efaketaues_13TeVDown', binning)

            dytes0up = DY.Get('TightOS'+di+'/scaletDM0Up/e_t_CollinearMass')
            dytes0up.Add(dyfakes, -1)
            dytes0up = positivize(dytes0up)
            dytes0up = dytes0up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVUp', binning)
            dytes0down = DY.Get('TightOS'+di+'/scaletDM0Down/e_t_CollinearMass')
            dytes0down.Add(dyfakes, -1)
            dytes0down = positivize(dytes0down)
            dytes0down = dytes0down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong_13TeVDown', binning)

            dytes1up = DY.Get('TightOS'+di+'/scaletDM1Up/e_t_CollinearMass')
            dytes1up.Add(dyfakes, -1)
            dytes1up = positivize(dytes1up)
            dytes1up = dytes1up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVUp', binning)
            dytes1down = DY.Get('TightOS'+di+'/scaletDM1Down/e_t_CollinearMass')
            dytes1down.Add(dyfakes, -1)
            dytes1down = positivize(dytes1down)
            dytes1down = dytes1down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_1prong1pizero_13TeVDown', binning)

            dytes10up = DY.Get('TightOS'+di+'/scaletDM10Up/e_t_CollinearMass')
            dytes10up.Add(dyfakes, -1)
            dytes10up = positivize(dytes10up)
            dytes10up = dytes10up.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVUp', binning)
            dytes10down = DY.Get('TightOS'+di+'/scaletDM10Down/e_t_CollinearMass')
            dytes10down.Add(dyfakes, -1)
            dytes10down = positivize(dytes10down)
            dytes10down = dytes10down.Rebin(len(binning)-1, b[i]+'_CMS_scale_t_3prong_13TeVDown', binning)

            #Electron Energy Scale
            dyeescup = DY.Get('TightOS'+di+'/eescUp/e_t_CollinearMass')
            dyeescup.Add(dyfakes, -1)
            dyeescup = positivize(dyeescup)
            dyeescup = dyeescup.Rebin(len(binning)-1, b[i]+'_CMS_EEScale_13TeVUp', binning)
            dyeescdown = DY.Get('TightOS'+di+'/eescDown/e_t_CollinearMass')
            dyeescdown.Add(dyfakes, -1)
            dyeescdown = positivize(dyeescdown)
            dyeescdown = dyeescdown.Rebin(len(binning)-1, b[i]+'_CMS_EEScale_13TeVDown', binning)

            #Electron Energy Sigma
            dyeesiup = DY.Get('TightOS'+di+'/eesiUp/e_t_CollinearMass')
            dyeesiup.Add(dyfakes, -1)
            dyeesiup = positivize(dyeesiup)
            dyeesiup = dyeesiup.Rebin(len(binning)-1, b[i]+'_CMS_EESigma_13TeVUp', binning)
            dyeesidown = DY.Get('TightOS'+di+'/eesiDown/e_t_CollinearMass')
            dyeesidown.Add(dyfakes, -1)
            dyeesidown = positivize(dyeesidown)
            dyeesidown = dyeesidown.Rebin(len(binning)-1, b[i]+'_CMS_EESigma_13TeVDown', binning)

            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup = DY.Get('TightOS'+di+'/UnclusteredEnUp/e_t_CollinearMass')
                dyuesup.Add(dyfakes, -1)
                dyuesup = positivize(dyuesup)
                dyuesup = dyuesup.Rebin(len(binning)-1, b[i]+'_CMS_MET_Ues_13TeVUp', binning)
                dyuesdown = DY.Get('TightOS'+di+'/UnclusteredEnDown/e_t_CollinearMass')
                dyuesdown.Add(dyfakes, -1)
                dyuesdown = positivize(dyuesdown)
                dyuesdown = dyuesdown.Rebin(len(binning)-1, b[i]+'_CMS_MET_Ues_13TeVDown', binning)

                dyjetAFMup = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapUp/e_t_CollinearMass')
                dyjetAFMup.Add(dyfakes, -1)
                dyjetAFMup = positivize(dyjetAFMup)
                dyjetAFMup = dyjetAFMup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVUp', binning)
                dyjetAFMdown = DY.Get('TightOS'+di+'/JetAbsoluteFlavMapDown/e_t_CollinearMass')
                dyjetAFMdown.Add(dyfakes, -1)
                dyjetAFMdown = positivize(dyjetAFMdown)
                dyjetAFMdown = dyjetAFMdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteFlavMap_13TeVDown', binning)

                dyjetAMPFBup = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasUp/e_t_CollinearMass')
                dyjetAMPFBup.Add(dyfakes, -1)
                dyjetAMPFBup = positivize(dyjetAMPFBup)
                dyjetAMPFBup = dyjetAMPFBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVUp', binning)
                dyjetAMPFBdown = DY.Get('TightOS'+di+'/JetAbsoluteMPFBiasDown/e_t_CollinearMass')
                dyjetAMPFBdown.Add(dyfakes, -1)
                dyjetAMPFBdown = positivize(dyjetAMPFBdown)
                dyjetAMPFBdown = dyjetAMPFBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteMPFBias_13TeVDown', binning)

                dyjetASup = DY.Get('TightOS'+di+'/JetAbsoluteScaleUp/e_t_CollinearMass')
                dyjetASup.Add(dyfakes, -1)
                dyjetASup = positivize(dyjetASup)
                dyjetASup = dyjetASup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVUp', binning)
                dyjetASdown = DY.Get('TightOS'+di+'/JetAbsoluteScaleDown/e_t_CollinearMass')
                dyjetASdown.Add(dyfakes, -1)
                dyjetASdown = positivize(dyjetASdown)
                dyjetASdown = dyjetASdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteScale_13TeVDown', binning)

                dyjetAStup = DY.Get('TightOS'+di+'/JetAbsoluteStatUp/e_t_CollinearMass')
                dyjetAStup.Add(dyfakes, -1)
                dyjetAStup = positivize(dyjetAStup)
                dyjetAStup = dyjetAStup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVUp', binning)
                dyjetAStdown = DY.Get('TightOS'+di+'/JetAbsoluteStatDown/e_t_CollinearMass')
                dyjetAStdown.Add(dyfakes, -1)
                dyjetAStdown = positivize(dyjetAStdown)
                dyjetAStdown = dyjetAStdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetAbsoluteStat_13TeVDown', binning)

                dyjetFQCDup = DY.Get('TightOS'+di+'/JetFlavorQCDUp/e_t_CollinearMass')
                dyjetFQCDup.Add(dyfakes, -1)
                dyjetFQCDup = positivize(dyjetFQCDup)
                dyjetFQCDup = dyjetFQCDup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFlavorQCD_13TeVUp', binning)
                dyjetFQCDdown = DY.Get('TightOS'+di+'/JetFlavorQCDDown/e_t_CollinearMass')
                dyjetFQCDdown.Add(dyfakes, -1)
                dyjetFQCDdown = positivize(dyjetFQCDdown)
                dyjetFQCDdown = dyjetFQCDdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFlavorQCD_13TeVDown', binning)

                dyjetFup = DY.Get('TightOS'+di+'/JetFragmentationUp/e_t_CollinearMass')
                dyjetFup.Add(dyfakes, -1)
                dyjetFup = positivize(dyjetFup)
                dyjetFup = dyjetFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFragmentation_13TeVUp', binning)
                dyjetFdown = DY.Get('TightOS'+di+'/JetFragmentationDown/e_t_CollinearMass')
                dyjetFdown.Add(dyfakes, -1)
                dyjetFdown = positivize(dyjetFdown)
                dyjetFdown = dyjetFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetFragmentation_13TeVDown', binning)

                dyjetPUDMCup = DY.Get('TightOS'+di+'/JetPileUpDataMCUp/e_t_CollinearMass')
                dyjetPUDMCup.Add(dyfakes, -1)
                dyjetPUDMCup = positivize(dyjetPUDMCup)
                dyjetPUDMCup = dyjetPUDMCup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVUp', binning)
                dyjetPUDMCdown = DY.Get('TightOS'+di+'/JetPileUpDataMCDown/e_t_CollinearMass')
                dyjetPUDMCdown.Add(dyfakes, -1)
                dyjetPUDMCdown = positivize(dyjetPUDMCdown)
                dyjetPUDMCdown = dyjetPUDMCdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpDataMC_13TeVDown', binning)

                dyjetPUPBBup = DY.Get('TightOS'+di+'/JetPileUpPtBBUp/e_t_CollinearMass')
                dyjetPUPBBup.Add(dyfakes, -1)
                dyjetPUPBBup = positivize(dyjetPUPBBup)
                dyjetPUPBBup = dyjetPUPBBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVUp', binning)
                dyjetPUPBBdown = DY.Get('TightOS'+di+'/JetPileUpPtBBDown/e_t_CollinearMass')
                dyjetPUPBBdown.Add(dyfakes, -1)
                dyjetPUPBBdown = positivize(dyjetPUPBBdown)
                dyjetPUPBBdown = dyjetPUPBBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtBB_13TeVDown', binning)

                dyjetPUPEC1up = DY.Get('TightOS'+di+'/JetPileUpPtEC1Up/e_t_CollinearMass')
                dyjetPUPEC1up.Add(dyfakes, -1)
                dyjetPUPEC1up = positivize(dyjetPUPEC1up)
                dyjetPUPEC1up = dyjetPUPEC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVUp', binning)
                dyjetPUPEC1down = DY.Get('TightOS'+di+'/JetPileUpPtEC1Down/e_t_CollinearMass')
                dyjetPUPEC1down.Add(dyfakes, -1)
                dyjetPUPEC1down = positivize(dyjetPUPEC1down)
                dyjetPUPEC1down = dyjetPUPEC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC1_13TeVDown', binning)

                dyjetPUPEC2up = DY.Get('TightOS'+di+'/JetPileUpPtEC2Up/e_t_CollinearMass')
                dyjetPUPEC2up.Add(dyfakes, -1)
                dyjetPUPEC2up = positivize(dyjetPUPEC2up)
                dyjetPUPEC2up = dyjetPUPEC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVUp', binning)
                dyjetPUPEC2down = DY.Get('TightOS'+di+'/JetPileUpPtEC2Down/e_t_CollinearMass')
                dyjetPUPEC2down.Add(dyfakes, -1)
                dyjetPUPEC2down = positivize(dyjetPUPEC2down)
                dyjetPUPEC2down = dyjetPUPEC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtEC2_13TeVDown', binning)

                dyjetPUPHFup = DY.Get('TightOS'+di+'/JetPileUpPtHFUp/e_t_CollinearMass')
                dyjetPUPHFup.Add(dyfakes, -1)
                dyjetPUPHFup = positivize(dyjetPUPHFup)
                dyjetPUPHFup = dyjetPUPHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVUp', binning)
                dyjetPUPHFdown = DY.Get('TightOS'+di+'/JetPileUpPtHFDown/e_t_CollinearMass')
                dyjetPUPHFdown.Add(dyfakes, -1)
                dyjetPUPHFdown = positivize(dyjetPUPHFdown)
                dyjetPUPHFdown = dyjetPUPHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtHF_13TeVDown', binning)

                dyjetPUPRup = DY.Get('TightOS'+di+'/JetPileUpPtRefUp/e_t_CollinearMass')
                dyjetPUPRup.Add(dyfakes, -1)
                dyjetPUPRup = positivize(dyjetPUPRup)
                dyjetPUPRup = dyjetPUPRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVUp', binning)
                dyjetPUPRdown = DY.Get('TightOS'+di+'/JetPileUpPtRefDown/e_t_CollinearMass')
                dyjetPUPRdown.Add(dyfakes, -1)
                dyjetPUPRdown = positivize(dyjetPUPRdown)
                dyjetPUPRdown = dyjetPUPRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetPileUpPtRef_13TeVDown', binning)

                dyjetRFSRup = DY.Get('TightOS'+di+'/JetRelativeFSRUp/e_t_CollinearMass')
                dyjetRFSRup.Add(dyfakes, -1)
                dyjetRFSRup = positivize(dyjetRFSRup)
                dyjetRFSRup = dyjetRFSRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeFSR_13TeVUp', binning)
                dyjetRFSRdown = DY.Get('TightOS'+di+'/JetRelativeFSRDown/e_t_CollinearMass')
                dyjetRFSRdown.Add(dyfakes, -1)
                dyjetRFSRdown = positivize(dyjetRFSRdown)
                dyjetRFSRdown = dyjetRFSRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeFSR_13TeVDown', binning)

                dyjetRJEREC1up = DY.Get('TightOS'+di+'/JetRelativeJEREC1Up/e_t_CollinearMass')
                dyjetRJEREC1up.Add(dyfakes, -1)
                dyjetRJEREC1up = positivize(dyjetRJEREC1up)
                dyjetRJEREC1up = dyjetRJEREC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVUp', binning)
                dyjetRJEREC1down = DY.Get('TightOS'+di+'/JetRelativeJEREC1Down/e_t_CollinearMass')
                dyjetRJEREC1down.Add(dyfakes, -1)
                dyjetRJEREC1down = positivize(dyjetRJEREC1down)
                dyjetRJEREC1down = dyjetRJEREC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC1_13TeVDown', binning)

                dyjetRJEREC2up = DY.Get('TightOS'+di+'/JetRelativeJEREC2Up/e_t_CollinearMass')
                dyjetRJEREC2up.Add(dyfakes, -1)
                dyjetRJEREC2up = positivize(dyjetRJEREC2up)
                dyjetRJEREC2up = dyjetRJEREC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVUp', binning)
                dyjetRJEREC2down = DY.Get('TightOS'+di+'/JetRelativeJEREC2Down/e_t_CollinearMass')
                dyjetRJEREC2down.Add(dyfakes, -1)
                dyjetRJEREC2down = positivize(dyjetRJEREC2down)
                dyjetRJEREC2down = dyjetRJEREC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJEREC2_13TeVDown', binning)

                dyjetRJERHFup = DY.Get('TightOS'+di+'/JetRelativeJERHFUp/e_t_CollinearMass')
                dyjetRJERHFup.Add(dyfakes, -1)
                dyjetRJERHFup = positivize(dyjetRJERHFup)
                dyjetRJERHFup = dyjetRJERHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVUp', binning)
                dyjetRJERHFdown = DY.Get('TightOS'+di+'/JetRelativeJERHFDown/e_t_CollinearMass')
                dyjetRJERHFdown.Add(dyfakes, -1)
                dyjetRJERHFdown = positivize(dyjetRJERHFdown)
                dyjetRJERHFdown = dyjetRJERHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeJERHF_13TeVDown', binning)

                dyjetRPBBup = DY.Get('TightOS'+di+'/JetRelativePtBBUp/e_t_CollinearMass')
                dyjetRPBBup.Add(dyfakes, -1)
                dyjetRPBBup = positivize(dyjetRPBBup)
                dyjetRPBBup = dyjetRPBBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtBB_13TeVUp', binning)
                dyjetRPBBdown = DY.Get('TightOS'+di+'/JetRelativePtBBDown/e_t_CollinearMass')
                dyjetRPBBdown.Add(dyfakes, -1)
                dyjetRPBBdown = positivize(dyjetRPBBdown)
                dyjetRPBBdown = dyjetRPBBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtBB_13TeVDown', binning)

                dyjetRPEC1up = DY.Get('TightOS'+di+'/JetRelativePtEC1Up/e_t_CollinearMass')
                dyjetRPEC1up.Add(dyfakes, -1)
                dyjetRPEC1up = positivize(dyjetRPEC1up)
                dyjetRPEC1up = dyjetRPEC1up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVUp', binning)
                dyjetRPEC1down = DY.Get('TightOS'+di+'/JetRelativePtEC1Down/e_t_CollinearMass')
                dyjetRPEC1down.Add(dyfakes, -1)
                dyjetRPEC1down = positivize(dyjetRPEC1down)
                dyjetRPEC1down = dyjetRPEC1down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC1_13TeVDown', binning)

                dyjetRPEC2up = DY.Get('TightOS'+di+'/JetRelativePtEC2Up/e_t_CollinearMass')
                dyjetRPEC2up.Add(dyfakes, -1)
                dyjetRPEC2up = positivize(dyjetRPEC2up)
                dyjetRPEC2up = dyjetRPEC2up.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVUp', binning)
                dyjetRPEC2down = DY.Get('TightOS'+di+'/JetRelativePtEC2Down/e_t_CollinearMass')
                dyjetRPEC2down.Add(dyfakes, -1)
                dyjetRPEC2down = positivize(dyjetRPEC2down)
                dyjetRPEC2down = dyjetRPEC2down.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtEC2_13TeVDown', binning)

                dyjetRPHFup = DY.Get('TightOS'+di+'/JetRelativePtHFUp/e_t_CollinearMass')
                dyjetRPHFup.Add(dyfakes, -1)
                dyjetRPHFup = positivize(dyjetRPHFup)
                dyjetRPHFup = dyjetRPHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtHF_13TeVUp', binning)
                dyjetRPHFdown = DY.Get('TightOS'+di+'/JetRelativePtHFDown/e_t_CollinearMass')
                dyjetRPHFdown.Add(dyfakes, -1)
                dyjetRPHFdown = positivize(dyjetRPHFdown)
                dyjetRPHFdown = dyjetRPHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativePtHF_13TeVDown', binning)

                dyjetRSECup = DY.Get('TightOS'+di+'/JetRelativeStatECUp/e_t_CollinearMass')
                dyjetRSECup.Add(dyfakes, -1)
                dyjetRSECup = positivize(dyjetRSECup)
                dyjetRSECup = dyjetRSECup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVUp', binning)
                dyjetRSECdown = DY.Get('TightOS'+di+'/JetRelativeStatECDown/e_t_CollinearMass')
                dyjetRSECdown.Add(dyfakes, -1)
                dyjetRSECdown = positivize(dyjetRSECdown)
                dyjetRSECdown = dyjetRSECdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatEC_13TeVDown', binning)

                dyjetRSFSRup = DY.Get('TightOS'+di+'/JetRelativeStatFSRUp/e_t_CollinearMass')
                dyjetRSFSRup.Add(dyfakes, -1)
                dyjetRSFSRup = positivize(dyjetRSFSRup)
                dyjetRSFSRup = dyjetRSFSRup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVUp', binning)
                dyjetRSFSRdown = DY.Get('TightOS'+di+'/JetRelativeStatFSRDown/e_t_CollinearMass')
                dyjetRSFSRdown.Add(dyfakes, -1)
                dyjetRSFSRdown = positivize(dyjetRSFSRdown)
                dyjetRSFSRdown = dyjetRSFSRdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatFSR_13TeVDown', binning)

                dyjetRSHFup = DY.Get('TightOS'+di+'/JetRelativeStatHFUp/e_t_CollinearMass')
                dyjetRSHFup.Add(dyfakes, -1)
                dyjetRSHFup = positivize(dyjetRSHFup)
                dyjetRSHFup = dyjetRSHFup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVUp', binning)
                dyjetRSHFdown = DY.Get('TightOS'+di+'/JetRelativeStatHFDown/e_t_CollinearMass')
                dyjetRSHFdown.Add(dyfakes, -1)
                dyjetRSHFdown = positivize(dyjetRSHFdown)
                dyjetRSHFdown = dyjetRSHFdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeStatHF_13TeVDown', binning)

                dyjetSPEup = DY.Get('TightOS'+di+'/JetSinglePionECALUp/e_t_CollinearMass')
                dyjetSPEup.Add(dyfakes, -1)
                dyjetSPEup = positivize(dyjetSPEup)
                dyjetSPEup = dyjetSPEup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVUp', binning)
                dyjetSPEdown = DY.Get('TightOS'+di+'/JetSinglePionECALDown/e_t_CollinearMass')
                dyjetSPEdown.Add(dyfakes, -1)
                dyjetSPEdown = positivize(dyjetSPEdown)
                dyjetSPEdown = dyjetSPEdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionECAL_13TeVDown', binning)

                dyjetSPHup = DY.Get('TightOS'+di+'/JetSinglePionHCALUp/e_t_CollinearMass')
                dyjetSPHup.Add(dyfakes, -1)
                dyjetSPHup = positivize(dyjetSPHup)
                dyjetSPHup = dyjetSPHup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVUp', binning)
                dyjetSPHdown = DY.Get('TightOS'+di+'/JetSinglePionHCALDown/e_t_CollinearMass')
                dyjetSPHdown.Add(dyfakes, -1)
                dyjetSPHdown = positivize(dyjetSPHdown)
                dyjetSPHdown = dyjetSPHdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetSinglePionHCAL_13TeVDown', binning)

                dyjetTPEup = DY.Get('TightOS'+di+'/JetTimePtEtaUp/e_t_CollinearMass')
                dyjetTPEup.Add(dyfakes, -1)
                dyjetTPEup = positivize(dyjetTPEup)
                dyjetTPEup = dyjetTPEup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetTimePtEta_13TeVUp', binning)
                dyjetTPEdown = DY.Get('TightOS'+di+'/JetTimePtEtaDown/e_t_CollinearMass')
                dyjetTPEdown.Add(dyfakes, -1)
                dyjetTPEdown = positivize(dyjetTPEdown)
                dyjetTPEdown = dyjetTPEdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetTimePtEta_13TeVDown', binning)

                dyjetRBup = DY.Get('TightOS'+di+'/JetRelativeBalUp/e_t_CollinearMass')
                dyjetRBup.Add(dyfakes, -1)
                dyjetRBup = positivize(dyjetRBup)
                dyjetRBup = dyjetRBup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeBal_13TeVUp', binning)
                dyjetRBdown = DY.Get('TightOS'+di+'/JetRelativeBalDown/e_t_CollinearMass')
                dyjetRBdown.Add(dyfakes, -1)
                dyjetRBdown = positivize(dyjetRBdown)
                dyjetRBdown = dyjetRBdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeBal_13TeVDown', binning)

                dyjetRSup = DY.Get('TightOS'+di+'/JetRelativeSampleUp/e_t_CollinearMass')
                dyjetRSup.Add(dyfakes, -1)
                dyjetRSup = positivize(dyjetRSup)
                dyjetRSup = dyjetRSup.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeSample_13TeVUp', binning)
                dyjetRSdown = DY.Get('TightOS'+di+'/JetRelativeSampleDown/e_t_CollinearMass')
                dyjetRSdown.Add(dyfakes, -1)
                dyjetRSdown = positivize(dyjetRSdown)
                dyjetRSdown = dyjetRSdown.Rebin(len(binning)-1, b[i]+'_CMS_Jes_JetRelativeSample_13TeVDown', binning)

            dyall = DY.Get('TightOS'+di+'/e_t_CollinearMass')
            dyte0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
            dyte0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
            dyte1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
            dyte1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
            dyte10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
            dyte10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
            dytb0fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
            dytb0fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
            dytb1fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
            dytb1fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
            dytb10fakesup = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
            dytb10fakesdown = DY.Get('TauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
            dyefakesup = DY.Get('EleLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
            dyefakesdown = DY.Get('EleLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
            dyette0fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Up/e_t_CollinearMass')
            dyette0fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM0Down/e_t_CollinearMass')
            dyette1fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Up/e_t_CollinearMass')
            dyette1fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM1Down/e_t_CollinearMass')
            dyette10fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Up/e_t_CollinearMass')
            dyette10fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEEDM10Down/e_t_CollinearMass')
            dyettb0fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Up/e_t_CollinearMass')
            dyettb0fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM0Down/e_t_CollinearMass')
            dyettb1fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Up/e_t_CollinearMass')
            dyettb1fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM1Down/e_t_CollinearMass')
            dyettb10fakesup = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Up/e_t_CollinearMass')
            dyettb10fakesdown = DY.Get('EleLooseTauLooseOS'+di+'/TauFakeEBDM10Down/e_t_CollinearMass')
            dyetefakesup = DY.Get('EleLooseTauLooseOS'+di+'/EleFakeUp/e_t_CollinearMass')
            dyetefakesdown = DY.Get('EleLooseTauLooseOS'+di+'/EleFakeDown/e_t_CollinearMass')
            dy1e0 = dyall.Clone()
            dy1te0 = dyte0fakesup.Clone()
            dy1te0.add(dyefakes)
            dy1te0.add(dyette0fakesup, -1)
            dy1te0 = positivize(dy1te0)
            dy1e0.add(dy1te0, -1)
            dy1e0 = positivize(dy1e0)
            dy1e0 = dy1e0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVUp', binning)
            dy2e0 = dyall.Clone()
            dy2te0 = dyte0fakesdown.Clone()
            dy2te0.add(dyefakes)
            dy2te0.add(dyette0fakesdown, -1)
            dy2te0 = positivize(dy2te0)
            dy2e0.add(dy2te0, -1)
            dy2e0 = positivize(dy2e0)
            dy2e0 = dy2e0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM0_13TeVDown', binning)
            dy1e1 = dyall.Clone()
            dy1te1 = dyte1fakesup.Clone()
            dy1te1.add(dyefakes)
            dy1te1.add(dyette1fakesup, -1)
            dy1te1 = positivize(dy1te1)
            dy1e1.add(dy1te1, -1)
            dy1e1 = positivize(dy1e1)
            dy1e1 = dy1e1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVUp', binning)
            dy2e1 = dyall.Clone()
            dy2te1 = dyte1fakesdown.Clone()
            dy2te1.add(dyefakes)
            dy2te1.add(dyette1fakesdown, -1)
            dy2te1 = positivize(dy2te1)
            dy2e1.add(dy2te1, -1)
            dy2e1 = positivize(dy2e1)
            dy2e1 = dy2e1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM1_13TeVDown', binning)
            dy1e10 = dyall.Clone()
            dy1te10 = dyte10fakesup.Clone()
            dy1te10.add(dyefakes)
            dy1te10.add(dyette10fakesup, -1)
            dy1te10 = positivize(dy1te10)
            dy1e10.add(dy1te10, -1)
            dy1e10 = positivize(dy1e10)
            dy1e10 = dy1e10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVUp', binning)
            dy2e10 = dyall.Clone()
            dy2te10 = dyte10fakesdown.Clone()
            dy2te10.add(dyefakes)
            dy2te10.add(dyette10fakesdown, -1)
            dy2te10 = positivize(dy2te10)
            dy2e10.add(dy2te10, -1)
            dy2e10 = positivize(dy2e10)
            dy2e10 = dy2e10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EE_DM10_13TeVDown', binning)
            dy1b0 = dyall.Clone()
            dy1tb0 = dytb0fakesup.Clone()
            dy1tb0.add(dyefakes)
            dy1tb0.add(dyettb0fakesup, -1)
            dy1tb0 = positivize(dy1tb0)
            dy1b0.add(dy1tb0, -1)
            dy1b0 = positivize(dy1b0)
            dy1b0 = dy1b0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVUp', binning)
            dy2b0 = dyall.Clone()
            dy2tb0 = dytb0fakesdown.Clone()
            dy2tb0.add(dyefakes)
            dy2tb0.add(dyettb0fakesdown, -1)
            dy2tb0 = positivize(dy2tb0)
            dy2b0.add(dy2tb0, -1)
            dy2b0 = positivize(dy2b0)
            dy2b0 = dy2b0.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM0_13TeVDown', binning)
            dy1b1 = dyall.Clone()
            dy1tb1 = dytb1fakesup.Clone()
            dy1tb1.add(dyefakes)
            dy1tb1.add(dyettb1fakesup, -1)
            dy1tb1 = positivize(dy1tb1)
            dy1b1.add(dy1tb1, -1)
            dy1b1 = positivize(dy1b1)
            dy1b1 = dy1b1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVUp', binning)
            dy2b1 = dyall.Clone()
            dy2tb1 = dytb1fakesdown.Clone()
            dy2tb1.add(dyefakes)
            dy2tb1.add(dyettb1fakesdown, -1)
            dy2tb1 = positivize(dy2tb1)
            dy2b1.add(dy2tb1, -1)
            dy2b1 = positivize(dy2b1)
            dy2b1 = dy2b1.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM1_13TeVDown', binning)
            dy1b10 = dyall.Clone()
            dy1tb10 = dytb10fakesup.Clone()
            dy1tb10.add(dyefakes)
            dy1tb10.add(dyettb10fakesup, -1)
            dy1tb10 = positivize(dy1tb10)
            dy1b10.add(dy1tb10, -1)
            dy1b10 = positivize(dy1b10)
            dy1b10 = dy1b10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVUp', binning)
            dy2b10 = dyall.Clone()
            dy2tb10 = dytb10fakesdown.Clone()
            dy2tb10.add(dyefakes)
            dy2tb10.add(dyettb10fakesdown, -1)
            dy2tb10 = positivize(dy2tb10)
            dy2b10.add(dy2tb10, -1)
            dy2b10 = positivize(dy2b10)
            dy2b10 = dy2b10.Rebin(len(binning)-1, b[i]+'_CMS_TauFakeRate_EB_DM10_13TeVDown', binning)
            dy3 = dyall.Clone()
            dy3t = dytfakes.Clone()
            dy3t.add(dyefakesup)
            dy3t.add(dyetefakesup, -1)
            dy3t = positivize(dy3t)
            dy3.add(dy3t, -1)
            dy3 = positivize(dy3)
            dy3 = dy3.Rebin(len(binning)-1, b[i]+'_CMS_EleFakeRate_13TeVUp', binning)
            dy4 = dyall.Clone()
            dy4t = dytfakes.Clone()
            dy4t.add(dyefakesdown)
            dy4t.add(dyetefakesdown, -1)
            dy4t = positivize(dy4t)
            dy4.add(dy4t, -1)
            dy4 = positivize(dy4)
            dy4 = dy4.Rebin(len(binning)-1, b[i]+'_CMS_EleFakeRate_13TeVDown', binning)
            dyall.Delete()
            dy1te0.Delete()
            dy2te0.Delete()
            dy1te1.Delete()
            dy2te1.Delete()
            dy1te10.Delete()
            dy2te10.Delete()
            dy1tb0.Delete()
            dy2tb0.Delete()
            dy1tb1.Delete()
            dy2tb1.Delete()
            dy1tb10.Delete()
            dy2tb10.Delete()
            dy3t.Delete()
            dy4t.Delete()
            dyfakes.Delete()
            dytfakes.Delete()
            dyefakes.Delete()
            dyetfakes.Delete()
            dyte0fakesup.Delete()
            dyte0fakesdown.Delete()
            dyte1fakesup.Delete()
            dyte1fakesdown.Delete()
            dyte10fakesup.Delete()
            dyte10fakesdown.Delete()
            dytb0fakesup.Delete()
            dytb0fakesdown.Delete()
            dytb1fakesup.Delete()
            dytb1fakesdown.Delete()
            dytb10fakesup.Delete()
            dytb10fakesdown.Delete()
            dyefakesup.Delete()
            dyefakesdown.Delete()
            dyette0fakesup.Delete()
            dyette0fakesdown.Delete()
            dyette1fakesup.Delete()
            dyette1fakesdown.Delete()
            dyette10fakesup.Delete()
            dyette10fakesdown.Delete()
            dyettb0fakesup.Delete()
            dyettb0fakesdown.Delete()
            dyettb1fakesup.Delete()
            dyettb1fakesdown.Delete()
            dyettb10fakesup.Delete()
            dyettb10fakesdown.Delete()
            dyetefakesup.Delete()
            dyetefakesdown.Delete()

        f.Write()
        if i==0:
            data.Delete()
            emb.Delete()
            qcd.Delete()
            f1e0.Delete()
            f2e0.Delete()
            f1e1.Delete()
            f2e1.Delete()
            f1e10.Delete()
            f2e10.Delete()
            f1b0.Delete()
            f2b0.Delete()
            f1b1.Delete()
            f2b1.Delete()
            f1b10.Delete()
            f2b10.Delete()
            f3.Delete()
            f4.Delete()
            emb1e0.Delete()
            emb2e0.Delete()
            emb1e1.Delete()
            emb2e1.Delete()
            emb1e10.Delete()
            emb2e10.Delete()
            emb1b0.Delete()
            emb2b0.Delete()
            emb1b1.Delete()
            emb2b1.Delete()
            emb1b10.Delete()
            emb2b10.Delete()
            emb3.Delete()
            emb4.Delete()
            embtrkup.Delete()
            embtrkdown.Delete()
            embtes0up.Delete()
            embtes0down.Delete()
            embtes1up.Delete()
            embtes1down.Delete()
            embtes10up.Delete()
            embtes10down.Delete()
        if b[i]=='GluGlu125' or b[i]=='VBF125':
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dypfup.Delete()
            dypfdown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            dyrecrespup.Delete()
            dyrecrespdown.Delete()
            dyrecresoup.Delete()
            dyrecresodown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dyeescup.Delete()
            dyeescdown.Delete()
            dyeesiup.Delete()
            dyeesidown.Delete()
        else:
            dy.Delete()
            dypuup.Delete()
            dypudown.Delete()
            dypfup.Delete()
            dypfdown.Delete()
            dytidup.Delete()
            dytiddown.Delete()
            if b[i]=='Zll' or b[i]=='GluGluH' or b[i]=='VBFH' or b[i]=='EWK':
                dyrecrespup.Delete()
                dyrecrespdown.Delete()
                dyrecresoup.Delete()
                dyrecresodown.Delete()
            if b[i]=='Zll':
                dyptup.Delete()
                dyptdown.Delete()
            if b[i]=='TT':
                dytptup.Delete()
                dytptdown.Delete()
            dymtfakeup.Delete()
            dymtfakedown.Delete()
            dyetfakeup.Delete()
            dyetfakedown.Delete()
            dyetefakeup.Delete()
            dyetefakedown.Delete()
            dytes0up.Delete()
            dytes0down.Delete()
            dytes1up.Delete()
            dytes1down.Delete()
            dytes10up.Delete()
            dytes10down.Delete()
            dyeescup.Delete()
            dyeescdown.Delete()
            dyeesiup.Delete()
            dyeesidown.Delete()
            if b[i]=='VH' or b[i]=='TT' or b[i]=='ST' or b[i]=='EWKDiboson':
                dyuesup.Delete()
                dyuesdown.Delete()
                dyjetAFMup.Delete()
                dyjetAFMdown.Delete()
                dyjetAMPFBup.Delete()
                dyjetAMPFBdown.Delete()
                dyjetASup.Delete()
                dyjetASdown.Delete()
                dyjetAStup.Delete()
                dyjetAStdown.Delete()
                dyjetFQCDup.Delete()
                dyjetFQCDdown.Delete()
                dyjetFup.Delete()
                dyjetFdown.Delete()
                dyjetPUDMCup.Delete()
                dyjetPUDMCdown.Delete()
                dyjetPUPBBup.Delete()
                dyjetPUPBBdown.Delete()
                dyjetPUPEC1up.Delete()
                dyjetPUPEC1down.Delete()
                dyjetPUPEC2up.Delete()
                dyjetPUPEC2down.Delete()
                dyjetPUPHFup.Delete()
                dyjetPUPHFdown.Delete()
                dyjetPUPRup.Delete()
                dyjetPUPRdown.Delete()
                dyjetRFSRup.Delete()
                dyjetRFSRdown.Delete()
                dyjetRJEREC1up.Delete()
                dyjetRJEREC1down.Delete()
                dyjetRJEREC2up.Delete()
                dyjetRJEREC2down.Delete()
                dyjetRJERHFup.Delete()
                dyjetRJERHFdown.Delete()
                dyjetRPBBup.Delete()
                dyjetRPBBdown.Delete()
                dyjetRPEC1up.Delete()
                dyjetRPEC1down.Delete()
                dyjetRPEC2up.Delete()
                dyjetRPEC2down.Delete()
                dyjetRPHFup.Delete()
                dyjetRPHFdown.Delete()
                dyjetRSECup.Delete()
                dyjetRSECdown.Delete()
                dyjetRSFSRup.Delete()
                dyjetRSFSRdown.Delete()
                dyjetRSHFup.Delete()
                dyjetRSHFdown.Delete()
                dyjetSPEup.Delete()
                dyjetSPEdown.Delete()
                dyjetSPHup.Delete()
                dyjetSPHdown.Delete()
                dyjetTPEup.Delete()
                dyjetTPEdown.Delete()
                dyjetRBup.Delete()
                dyjetRBdown.Delete()
                dyjetRSup.Delete()
                dyjetRSdown.Delete()
            dy1e0.Delete()
            dy2e0.Delete()
            dy1e1.Delete()
            dy2e1.Delete()
            dy1e10.Delete()
            dy2e10.Delete()
            dy1b0.Delete()
            dy2b0.Delete()
            dy1b1.Delete()
            dy2b1.Delete()
            dy1b10.Delete()
            dy2b10.Delete()
            dy3.Delete()
            dy4.Delete()
